/**
 * The Gruvs — Master Category Registry
 * 1000+ curated categories spanning every domain of human interest.
 * Each entry: { key, label, color, icon, group }
 */

const C = {
  purple:  '#8b5cf6', violet: '#7c3aed', indigo: '#6366f1',
  blue:    '#3b82f6', sky:    '#0ea5e9', cyan:   '#06b6d4',
  teal:    '#0d9488', green:  '#10b981', lime:   '#84cc16',
  yellow:  '#f59e0b', amber:  '#d97706', orange: '#f97316',
  red:     '#ef4444', rose:   '#f43f5e', pink:   '#ec4899',
  fuchsia: '#d946ef', slate:  '#64748b', stone:  '#78716c',
};

const cat = (key, label, color, icon, group) => ({ key, label, color, icon, group });

export const ALL_CATEGORIES = [

  // ── MUSIC ──────────────────────────────────────────────────────────────────
  cat('music',          'Music',            C.purple,  '🎵', 'Music'),
  cat('afrobeats',      'Afrobeats',        C.orange,  '🎶', 'Music'),
  cat('amapiano',       'Amapiano',         C.fuchsia, '🎹', 'Music'),
  cat('afrojuju',       'Afro Juju',        C.amber,   '🪘', 'Music'),
  cat('highlife',       'Highlife',         C.yellow,  '🎺', 'Music'),
  cat('fuji',           'Fuji',             C.orange,  '🥁', 'Music'),
  cat('afropop',        'Afropop',          C.pink,    '🎤', 'Music'),
  cat('gospel',         'Gospel',           C.indigo,  '🙏', 'Music'),
  cat('choir',          'Choir',            C.blue,    '🎼', 'Music'),
  cat('hiphop',         'Hip-Hop',          C.purple,  '🎧', 'Music'),
  cat('rap',            'Rap',              C.slate,   '🎤', 'Music'),
  cat('trap',           'Trap',             C.violet,  '🔊', 'Music'),
  cat('drill',          'Drill',            C.slate,   '🎵', 'Music'),
  cat('rnb',            'R&B',              C.rose,    '💜', 'Music'),
  cat('soul',           'Soul',             C.fuchsia, '🎶', 'Music'),
  cat('neosoul',        'Neo-Soul',         C.purple,  '🎸', 'Music'),
  cat('jazz',           'Jazz',             C.amber,   '🎷', 'Music'),
  cat('blues',          'Blues',            C.blue,    '🎸', 'Music'),
  cat('classical',      'Classical',        C.indigo,  '🎻', 'Music'),
  cat('opera',          'Opera',            C.red,     '🎭', 'Music'),
  cat('orchestral',     'Orchestral',       C.indigo,  '🎼', 'Music'),
  cat('electronic',     'Electronic',       C.cyan,    '🎛️', 'Music'),
  cat('edm',            'EDM',              C.blue,    '⚡', 'Music'),
  cat('house',          'House',            C.sky,     '🎶', 'Music'),
  cat('deephouse',      'Deep House',       C.teal,    '🎶', 'Music'),
  cat('techhouse',      'Tech House',       C.cyan,    '🎶', 'Music'),
  cat('afrohouse',      'Afro House',       C.orange,  '🎶', 'Music'),
  cat('techno',         'Techno',           C.slate,   '🔊', 'Music'),
  cat('trance',         'Trance',           C.violet,  '🌀', 'Music'),
  cat('psytrance',      'Psytrance',        C.purple,  '🌀', 'Music'),
  cat('dubstep',        'Dubstep',          C.blue,    '🔊', 'Music'),
  cat('dnb',            'Drum & Bass',      C.indigo,  '🥁', 'Music'),
  cat('jungle',         'Jungle',           C.green,   '🎶', 'Music'),
  cat('grime',          'Grime',            C.slate,   '🎤', 'Music'),
  cat('ukgarage',       'UK Garage',        C.sky,     '🎶', 'Music'),
  cat('ambient',        'Ambient',          C.teal,    '🌊', 'Music'),
  cat('lofi',           'Lo-Fi',            C.stone,   '☕', 'Music'),
  cat('chillout',       'Chillout',         C.sky,     '🌙', 'Music'),
  cat('downtempo',      'Downtempo',        C.teal,    '🎶', 'Music'),
  cat('triphop',        'Trip-Hop',         C.purple,  '🎶', 'Music'),
  cat('reggae',         'Reggae',           C.green,   '🌿', 'Music'),
  cat('dancehall',      'Dancehall',        C.yellow,  '💃', 'Music'),
  cat('soca',           'Soca',             C.orange,  '🎉', 'Music'),
  cat('calypso',        'Calypso',          C.yellow,  '🎶', 'Music'),
  cat('latin',          'Latin',            C.red,     '🌶️', 'Music'),
  cat('salsa',          'Salsa',            C.red,     '💃', 'Music'),
  cat('merengue',       'Merengue',         C.orange,  '🎶', 'Music'),
  cat('bachata',        'Bachata',          C.rose,    '💃', 'Music'),
  cat('cumbia',         'Cumbia',           C.yellow,  '🎶', 'Music'),
  cat('reggaeton',      'Reggaeton',        C.orange,  '🎤', 'Music'),
  cat('country',        'Country',          C.amber,   '🤠', 'Music'),
  cat('folk',           'Folk',             C.stone,   '🪕', 'Music'),
  cat('bluegrass',      'Bluegrass',        C.green,   '🪕', 'Music'),
  cat('americana',      'Americana',        C.amber,   '🎸', 'Music'),
  cat('indie',          'Indie',            C.purple,  '🎸', 'Music'),
  cat('alternative',    'Alternative',      C.violet,  '🎸', 'Music'),
  cat('punk',           'Punk',             C.red,     '🤘', 'Music'),
  cat('metal',          'Metal',            C.slate,   '🤘', 'Music'),
  cat('deathmetal',     'Death Metal',      C.red,     '🤘', 'Music'),
  cat('blackmetal',     'Black Metal',      C.slate,   '🤘', 'Music'),
  cat('progmetal',      'Prog Metal',       C.violet,  '🎸', 'Music'),
  cat('nymetal',        'Nu-Metal',         C.orange,  '🎸', 'Music'),
  cat('emo',            'Emo',              C.violet,  '🖤', 'Music'),
  cat('postrock',       'Post-Rock',        C.teal,    '🎸', 'Music'),
  cat('shoegaze',       'Shoegaze',         C.sky,     '🎸', 'Music'),
  cat('dreampop',       'Dream Pop',        C.pink,    '🌙', 'Music'),
  cat('synthpop',       'Synth-Pop',        C.cyan,    '🎹', 'Music'),
  cat('newwave',        'New Wave',         C.indigo,  '🎹', 'Music'),
  cat('disco',          'Disco',            C.pink,    '🪩', 'Music'),
  cat('funk',           'Funk',             C.orange,  '🎸', 'Music'),
  cat('groove',         'Groove',           C.amber,   '🎶', 'Music'),
  cat('kpop',           'K-Pop',            C.pink,    '🇰🇷', 'Music'),
  cat('jpop',           'J-Pop',            C.sky,     '🇯🇵', 'Music'),
  cat('cpop',           'C-Pop',            C.red,     '🇨🇳', 'Music'),
  cat('bollywood',      'Bollywood',        C.yellow,  '🎬', 'Music'),
  cat('qawwali',        'Qawwali',          C.amber,   '🎶', 'Music'),
  cat('bhangra',        'Bhangra',          C.orange,  '🥁', 'Music'),
  cat('carnatic',       'Carnatic',         C.amber,   '🎵', 'Music'),
  cat('hindustani',     'Hindustani',       C.yellow,  '🎵', 'Music'),
  cat('celtic',         'Celtic',           C.green,   '🍀', 'Music'),
  cat('worldmusic',     'World Music',      C.teal,    '🌍', 'Music'),
  cat('afrofusion',     'Afro-Fusion',      C.orange,  '🌍', 'Music'),
  cat('gospel_praise',  'Praise & Worship', C.indigo,  '✝️', 'Music'),
  cat('acapella',       'A Cappella',       C.blue,    '🎤', 'Music'),
  cat('karaoke',        'Karaoke',          C.pink,    '🎤', 'Music'),
  cat('open_mic',       'Open Mic',         C.amber,   '🎙️', 'Music'),
  cat('battle',         'Battle',           C.red,     '⚔️', 'Music'),
  cat('djset',          'DJ Set',           C.cyan,    '🎧', 'Music'),
  cat('liveband',       'Live Band',        C.purple,  '🎸', 'Music'),
  cat('concert',        'Concert',          C.violet,  '🎫', 'Music'),
  cat('festival_music', 'Music Festival',   C.yellow,  '🎪', 'Music'),
  cat('rave',           'Rave',             C.cyan,    '🌀', 'Music'),
  cat('club_night',     'Club Night',       C.fuchsia, '🌙', 'Music'),

  // ── DANCE ──────────────────────────────────────────────────────────────────
  cat('dance',          'Dance',            C.pink,    '💃', 'Dance'),
  cat('ballet',         'Ballet',           C.rose,    '🩰', 'Dance'),
  cat('contemporary',   'Contemporary',     C.violet,  '💃', 'Dance'),
  cat('hiphop_dance',   'Hip-Hop Dance',    C.purple,  '🕺', 'Dance'),
  cat('breakdance',     'Breakdancing',     C.orange,  '🕺', 'Dance'),
  cat('streetdance',    'Street Dance',     C.slate,   '🕺', 'Dance'),
  cat('afrobeats_dance','Afrobeats Dance',  C.orange,  '💃', 'Dance'),
  cat('amapiano_dance', 'Amapiano Dance',   C.fuchsia, '💃', 'Dance'),
  cat('gqom_dance',     'Gqom Dance',       C.cyan,    '💃', 'Dance'),
  cat('kizomba',        'Kizomba',          C.rose,    '💃', 'Dance'),
  cat('zouk',           'Zouk',             C.pink,    '💃', 'Dance'),
  cat('twerking',       'Twerk',            C.orange,  '💃', 'Dance'),
  cat('linedance',      'Line Dance',       C.amber,   '🤠', 'Dance'),
  cat('swing',          'Swing',            C.yellow,  '💃', 'Dance'),
  cat('waltz',          'Waltz',            C.indigo,  '💃', 'Dance'),
  cat('tango',          'Tango',            C.red,     '💃', 'Dance'),
  cat('tap_dance',      'Tap Dance',        C.amber,   '🎩', 'Dance'),
  cat('bollywood_dance','Bollywood Dance',  C.yellow,  '💃', 'Dance'),
  cat('kathak',         'Kathak',           C.orange,  '💃', 'Dance'),
  cat('flamenco',       'Flamenco',         C.red,     '💃', 'Dance'),
  cat('irish_dance',    'Irish Dance',      C.green,   '🍀', 'Dance'),
  cat('danceworkshop',  'Dance Workshop',   C.teal,    '🎓', 'Dance'),
  cat('dancebattle',    'Dance Battle',     C.red,     '⚔️', 'Dance'),
  cat('dancesocial',    'Social Dancing',   C.pink,    '🎉', 'Dance'),

  // ── SPORT ──────────────────────────────────────────────────────────────────
  cat('sport',          'Sport',            C.green,   '🏆', 'Sport'),
  cat('football',       'Football',         C.green,   '⚽', 'Sport'),
  cat('basketball',     'Basketball',       C.orange,  '🏀', 'Sport'),
  cat('tennis',         'Tennis',           C.lime,    '🎾', 'Sport'),
  cat('cricket',        'Cricket',          C.green,   '🏏', 'Sport'),
  cat('rugby',          'Rugby',            C.amber,   '🏉', 'Sport'),
  cat('boxing',         'Boxing',           C.red,     '🥊', 'Sport'),
  cat('mma',            'MMA',              C.red,     '🥋', 'Sport'),
  cat('wrestling',      'Wrestling',        C.orange,  '🤼', 'Sport'),
  cat('athletics',      'Athletics',        C.yellow,  '🏃', 'Sport'),
  cat('swimming',       'Swimming',         C.sky,     '🏊', 'Sport'),
  cat('cycling',        'Cycling',          C.lime,    '🚴', 'Sport'),
  cat('triathlon',      'Triathlon',        C.teal,    '🏊', 'Sport'),
  cat('marathon',       'Marathon',         C.orange,  '🏃', 'Sport'),
  cat('crossfit',       'CrossFit',         C.red,     '💪', 'Sport'),
  cat('weightlifting',  'Weightlifting',    C.slate,   '🏋️', 'Sport'),
  cat('powerlifting',   'Powerlifting',     C.stone,   '🏋️', 'Sport'),
  cat('bodybuilding',   'Bodybuilding',     C.amber,   '💪', 'Sport'),
  cat('calisthenics',   'Calisthenics',     C.green,   '💪', 'Sport'),
  cat('gymnastics',     'Gymnastics',       C.pink,    '🤸', 'Sport'),
  cat('parkour',        'Parkour',          C.slate,   '🏃', 'Sport'),
  cat('rockclimbing',   'Rock Climbing',    C.stone,   '🧗', 'Sport'),
  cat('bouldering',     'Bouldering',       C.orange,  '🧗', 'Sport'),
  cat('hiking',         'Hiking',           C.green,   '🥾', 'Sport'),
  cat('trailrunning',   'Trail Running',    C.lime,    '🏃', 'Sport'),
  cat('mountainbike',   'Mountain Biking',  C.green,   '🚵', 'Sport'),
  cat('bmx',            'BMX',              C.orange,  '🚲', 'Sport'),
  cat('skateboarding',  'Skateboarding',    C.slate,   '🛹', 'Sport'),
  cat('surfing',        'Surfing',          C.sky,     '🏄', 'Sport'),
  cat('snowboarding',   'Snowboarding',     C.sky,     '🏂', 'Sport'),
  cat('skiing',         'Skiing',           C.blue,    '⛷️', 'Sport'),
  cat('iceskating',     'Ice Skating',      C.sky,     '⛸️', 'Sport'),
  cat('icehockey',      'Ice Hockey',       C.blue,    '🏒', 'Sport'),
  cat('fieldhockey',    'Field Hockey',     C.green,   '🏑', 'Sport'),
  cat('baseball',       'Baseball',         C.red,     '⚾', 'Sport'),
  cat('softball',       'Softball',         C.yellow,  '🥎', 'Sport'),
  cat('americanfootball','American Football',C.orange, '🏈', 'Sport'),
  cat('volleyball',     'Volleyball',       C.orange,  '🏐', 'Sport'),
  cat('beachvolleyball','Beach Volleyball',  C.yellow,  '🏐', 'Sport'),
  cat('tabletennis',    'Table Tennis',     C.blue,    '🏓', 'Sport'),
  cat('badminton',      'Badminton',        C.lime,    '🏸', 'Sport'),
  cat('squash',         'Squash',           C.green,   '🎾', 'Sport'),
  cat('handball',       'Handball',         C.orange,  '🤾', 'Sport'),
  cat('netball',        'Netball',          C.teal,    '🏀', 'Sport'),
  cat('polo',           'Polo',             C.green,   '🐎', 'Sport'),
  cat('equestrian',     'Equestrian',       C.amber,   '🐎', 'Sport'),
  cat('archery',        'Archery',          C.green,   '🏹', 'Sport'),
  cat('judo',           'Judo',             C.blue,    '🥋', 'Sport'),
  cat('karate',         'Karate',           C.red,     '🥋', 'Sport'),
  cat('taekwondo',      'Taekwondo',        C.blue,    '🥋', 'Sport'),
  cat('kungfu',         'Kung Fu',          C.red,     '🥋', 'Sport'),
  cat('muaythai',       'Muay Thai',        C.orange,  '🥊', 'Sport'),
  cat('bjj',            'Brazilian Jiu-Jitsu',C.blue,  '🥋', 'Sport'),
  cat('capoeira',       'Capoeira',         C.yellow,  '🥋', 'Sport'),
  cat('kickboxing',     'Kickboxing',       C.red,     '🥊', 'Sport'),
  cat('fencing',        'Fencing',          C.blue,    '🤺', 'Sport'),
  cat('rowing',         'Rowing',           C.sky,     '🚣', 'Sport'),
  cat('kayaking',       'Kayaking',         C.cyan,    '🚣', 'Sport'),
  cat('canoeing',       'Canoeing',         C.teal,    '🚣', 'Sport'),
  cat('scuba',          'Scuba Diving',     C.blue,    '🤿', 'Sport'),
  cat('snorkeling',     'Snorkelling',      C.sky,     '🤿', 'Sport'),
  cat('kitesurf',       'Kitesurfing',      C.cyan,    '🪁', 'Sport'),
  cat('windsurfing',    'Windsurfing',      C.sky,     '🏄', 'Sport'),
  cat('golf',           'Golf',             C.lime,    '⛳', 'Sport'),
  cat('darts',          'Darts',            C.red,     '🎯', 'Sport'),
  cat('billiards',      'Billiards',        C.green,   '🎱', 'Sport'),
  cat('bowls',          'Lawn Bowls',       C.lime,    '🎳', 'Sport'),
  cat('bowling',        'Bowling',          C.orange,  '🎳', 'Sport'),
  cat('fishing',        'Fishing',          C.teal,    '🎣', 'Sport'),
  cat('hunting',        'Hunting',          C.stone,   '🦌', 'Sport'),
  cat('paintball',      'Paintball',        C.green,   '🎯', 'Sport'),
  cat('lasertagsport',  'Laser Tag',        C.cyan,    '🔫', 'Sport'),
  cat('esports_sport',  'Esports',          C.blue,    '🎮', 'Sport'),
  cat('chess',          'Chess',            C.slate,   '♟️', 'Sport'),
  cat('sportsday',      'Sports Day',       C.green,   '🏃', 'Sport'),
  cat('charity_run',    'Charity Run',      C.rose,    '🏃', 'Sport'),
  cat('fun_run',        'Fun Run',          C.orange,  '🏃', 'Sport'),

  // ── FITNESS & WELLNESS ──────────────────────────────────────────────────────
  cat('fitness',        'Fitness',          C.green,   '💪', 'Fitness & Wellness'),
  cat('yoga',           'Yoga',             C.violet,  '🧘', 'Fitness & Wellness'),
  cat('hotfyoga',       'Hot Yoga',         C.red,     '🧘', 'Fitness & Wellness'),
  cat('hatha',          'Hatha Yoga',       C.teal,    '🧘', 'Fitness & Wellness'),
  cat('vinyasa',        'Vinyasa',          C.sky,     '🧘', 'Fitness & Wellness'),
  cat('kundalini',      'Kundalini',        C.violet,  '🧘', 'Fitness & Wellness'),
  cat('ashtanga',       'Ashtanga',         C.indigo,  '🧘', 'Fitness & Wellness'),
  cat('pilates',        'Pilates',          C.pink,    '🤸', 'Fitness & Wellness'),
  cat('taichi',         'Tai Chi',          C.teal,    '🌿', 'Fitness & Wellness'),
  cat('qigong',         'Qi Gong',          C.green,   '🌿', 'Fitness & Wellness'),
  cat('meditation',     'Meditation',       C.violet,  '🧠', 'Fitness & Wellness'),
  cat('mindfulness',    'Mindfulness',      C.teal,    '🌿', 'Fitness & Wellness'),
  cat('breathwork',     'Breathwork',       C.sky,     '🌬️', 'Fitness & Wellness'),
  cat('stretching',     'Stretching',       C.lime,    '🤸', 'Fitness & Wellness'),
  cat('hiit',           'HIIT',             C.red,     '🔥', 'Fitness & Wellness'),
  cat('zumba',          'Zumba',            C.orange,  '💃', 'Fitness & Wellness'),
  cat('aerobics',       'Aerobics',         C.pink,    '🤸', 'Fitness & Wellness'),
  cat('spin',           'Spin Class',       C.red,     '🚴', 'Fitness & Wellness'),
  cat('barre',          'Barre',            C.rose,    '🩰', 'Fitness & Wellness'),
  cat('wellness',       'Wellness',         C.teal,    '💚', 'Fitness & Wellness'),
  cat('spa',            'Spa & Relaxation', C.violet,  '🧖', 'Fitness & Wellness'),
  cat('nutrition',      'Nutrition',        C.green,   '🥗', 'Fitness & Wellness'),
  cat('mentalhealth',   'Mental Health',    C.violet,  '🧠', 'Fitness & Wellness'),
  cat('therapy_group',  'Group Therapy',    C.indigo,  '💬', 'Fitness & Wellness'),
  cat('detox',          'Detox',            C.teal,    '🍃', 'Fitness & Wellness'),
  cat('fasting',        'Fasting',          C.green,   '🌿', 'Fitness & Wellness'),
  cat('naturopathy',    'Naturopathy',      C.lime,    '🌿', 'Fitness & Wellness'),
  cat('reiki',          'Reiki',            C.violet,  '✨', 'Fitness & Wellness'),
  cat('acupuncture',    'Acupuncture',      C.teal,    '🌿', 'Fitness & Wellness'),
  cat('massage',        'Massage',          C.stone,   '🧖', 'Fitness & Wellness'),
  cat('cold_therapy',   'Cold Therapy',     C.sky,     '🧊', 'Fitness & Wellness'),
  cat('sauna',          'Sauna',            C.orange,  '🔥', 'Fitness & Wellness'),

  // ── FOOD & DRINK ───────────────────────────────────────────────────────────
  cat('food',           'Food',             C.orange,  '🍜', 'Food & Drink'),
  cat('restaurant',     'Restaurant Night', C.amber,   '🍽️', 'Food & Drink'),
  cat('brunch',         'Brunch',           C.yellow,  '🥞', 'Food & Drink'),
  cat('breakfast',      'Breakfast',        C.amber,   '🍳', 'Food & Drink'),
  cat('lunch',          'Lunch',            C.orange,  '🥗', 'Food & Drink'),
  cat('dinner',         'Dinner',           C.amber,   '🍝', 'Food & Drink'),
  cat('supper',         'Supper Club',      C.red,     '🕯️', 'Food & Drink'),
  cat('braai',          'Braai / BBQ',      C.red,     '🔥', 'Food & Drink'),
  cat('picnic',         'Picnic',           C.lime,    '🧺', 'Food & Drink'),
  cat('streetfood',     'Street Food',      C.orange,  '🌮', 'Food & Drink'),
  cat('foodmarket',     'Food Market',      C.yellow,  '🛒', 'Food & Drink'),
  cat('foodfestival',   'Food Festival',    C.orange,  '🎪', 'Food & Drink'),
  cat('wine_tasting',   'Wine Tasting',     C.rose,    '🍷', 'Food & Drink'),
  cat('beer',           'Beer & Brewing',   C.amber,   '🍺', 'Food & Drink'),
  cat('cocktails',      'Cocktail Night',   C.pink,    '🍹', 'Food & Drink'),
  cat('whiskey',        'Whiskey Tasting',  C.amber,   '🥃', 'Food & Drink'),
  cat('gin',            'Gin Tasting',      C.teal,    '🍸', 'Food & Drink'),
  cat('coffee',         'Coffee',           C.stone,   '☕', 'Food & Drink'),
  cat('coffee_cupping', 'Coffee Cupping',   C.amber,   '☕', 'Food & Drink'),
  cat('tea',            'Tea Ceremony',     C.green,   '🍵', 'Food & Drink'),
  cat('cooking',        'Cooking',          C.orange,  '👨‍🍳', 'Food & Drink'),
  cat('baking',         'Baking',           C.yellow,  '🥐', 'Food & Drink'),
  cat('pastry',         'Pastry',           C.pink,    '🥐', 'Food & Drink'),
  cat('vegan',          'Vegan',            C.green,   '🌱', 'Food & Drink'),
  cat('vegetarian',     'Vegetarian',       C.lime,    '🥗', 'Food & Drink'),
  cat('sushi',          'Sushi',            C.red,     '🍣', 'Food & Drink'),
  cat('halaal',         'Halaal',           C.green,   '🌙', 'Food & Drink'),
  cat('kosher',         'Kosher',           C.blue,    '✡️', 'Food & Drink'),
  cat('african_food',   'African Cuisine',  C.orange,  '🌍', 'Food & Drink'),
  cat('asian_food',     'Asian Cuisine',    C.red,     '🍜', 'Food & Drink'),
  cat('mediterranean',  'Mediterranean',    C.sky,     '🫒', 'Food & Drink'),
  cat('mexican_food',   'Mexican Cuisine',  C.green,   '🌮', 'Food & Drink'),
  cat('indian_food',    'Indian Cuisine',   C.yellow,  '🍛', 'Food & Drink'),
  cat('masterchef',     'Cook-Off',         C.orange,  '🏆', 'Food & Drink'),
  cat('cheesetasting',  'Cheese Tasting',   C.yellow,  '🧀', 'Food & Drink'),
  cat('chocolate',      'Chocolate',        C.stone,   '🍫', 'Food & Drink'),
  cat('nonalcoholic',   'Mocktails',        C.cyan,    '🧋', 'Food & Drink'),
  cat('bubbletea',      'Bubble Tea',       C.pink,    '🧋', 'Food & Drink'),

  // ── ARTS & CULTURE ─────────────────────────────────────────────────────────
  cat('art',            'Arts & Theatre',   C.fuchsia, '🎨', 'Arts & Culture'),
  cat('painting',       'Painting',         C.pink,    '🖌️', 'Arts & Culture'),
  cat('drawing',        'Drawing',          C.violet,  '✏️', 'Arts & Culture'),
  cat('sculpture',      'Sculpture',        C.stone,   '🗿', 'Arts & Culture'),
  cat('photography',    'Photography',      C.purple,  '📸', 'Arts & Culture'),
  cat('streetphotog',   'Street Photography',C.slate,  '📷', 'Arts & Culture'),
  cat('portraitphotog', 'Portrait Photography',C.indigo,'📷', 'Arts & Culture'),
  cat('film_photog',    'Film Photography', C.stone,   '🎞️', 'Arts & Culture'),
  cat('videography',    'Videography',      C.red,     '🎬', 'Arts & Culture'),
  cat('film',           'Film',             C.red,     '🎬', 'Arts & Culture'),
  cat('cinema',         'Cinema Night',     C.slate,   '🍿', 'Arts & Culture'),
  cat('documentary',    'Documentary',      C.stone,   '🎥', 'Arts & Culture'),
  cat('shortfilm',      'Short Film',       C.red,     '🎥', 'Arts & Culture'),
  cat('theatre',        'Theatre',          C.violet,  '🎭', 'Arts & Culture'),
  cat('musicaltheatre', 'Musical Theatre',  C.pink,    '🎭', 'Arts & Culture'),
  cat('improv',         'Improv',           C.yellow,  '🎭', 'Arts & Culture'),
  cat('standup',        'Stand-Up Comedy',  C.amber,   '🎙️', 'Arts & Culture'),
  cat('comedy',         'Comedy',           C.yellow,  '😂', 'Arts & Culture'),
  cat('poetry',         'Poetry',           C.violet,  '📝', 'Arts & Culture'),
  cat('spoken_word',    'Spoken Word',      C.indigo,  '🎤', 'Arts & Culture'),
  cat('storytelling',   'Storytelling',     C.amber,   '📖', 'Arts & Culture'),
  cat('gallery',        'Art Gallery',      C.fuchsia, '🖼️', 'Arts & Culture'),
  cat('exhibition',     'Exhibition',       C.pink,    '🏛️', 'Arts & Culture'),
  cat('artwalk',        'Art Walk',         C.rose,    '🚶', 'Arts & Culture'),
  cat('mural',          'Mural Art',        C.orange,  '🎨', 'Arts & Culture'),
  cat('graffiti',       'Graffiti',         C.lime,    '🎨', 'Arts & Culture'),
  cat('digitalart',     'Digital Art',      C.cyan,    '💻', 'Arts & Culture'),
  cat('nft_art',        'NFT Art',          C.violet,  '🖼️', 'Arts & Culture'),
  cat('animation',      'Animation',        C.blue,    '🎬', 'Arts & Culture'),
  cat('manga',          'Manga & Comics',   C.orange,  '📚', 'Arts & Culture'),
  cat('anime',          'Anime',            C.purple,  '⛩️', 'Arts & Culture'),
  cat('cosplay',        'Cosplay',          C.fuchsia, '🎭', 'Arts & Culture'),
  cat('craft',          'Crafts',           C.amber,   '✂️', 'Arts & Culture'),
  cat('pottery',        'Pottery',          C.stone,   '🏺', 'Arts & Culture'),
  cat('ceramics',       'Ceramics',         C.stone,   '🏺', 'Arts & Culture'),
  cat('glassblowing',   'Glass Blowing',    C.sky,     '🫧', 'Arts & Culture'),
  cat('jewellery',      'Jewellery Making', C.yellow,  '💎', 'Arts & Culture'),
  cat('candle_making',  'Candle Making',    C.amber,   '🕯️', 'Arts & Culture'),
  cat('origami',        'Origami',          C.green,   '🦢', 'Arts & Culture'),
  cat('knitting',       'Knitting',         C.pink,    '🧶', 'Arts & Culture'),
  cat('crochet',        'Crochet',          C.rose,    '🧶', 'Arts & Culture'),
  cat('sewing',         'Sewing',           C.indigo,  '🧵', 'Arts & Culture'),
  cat('embroidery',     'Embroidery',       C.pink,    '🪡', 'Arts & Culture'),
  cat('woodwork',       'Woodwork',         C.stone,   '🪵', 'Arts & Culture'),
  cat('leatherwork',    'Leatherwork',      C.amber,   '🥾', 'Arts & Culture'),
  cat('printmaking',    'Printmaking',      C.teal,    '🖨️', 'Arts & Culture'),
  cat('calligraphy',    'Calligraphy',      C.indigo,  '🖊️', 'Arts & Culture'),
  cat('culture',        'Culture & Heritage',C.orange, '🌍', 'Arts & Culture'),
  cat('heritage',       'Heritage',         C.amber,   '🏛️', 'Arts & Culture'),
  cat('museum',         'Museum',           C.stone,   '🏛️', 'Arts & Culture'),
  cat('history',        'History',          C.amber,   '📜', 'Arts & Culture'),
  cat('archaeology',    'Archaeology',      C.stone,   '🏺', 'Arts & Culture'),

  // ── FASHION & BEAUTY ───────────────────────────────────────────────────────
  cat('fashion',        'Fashion',          C.fuchsia, '👗', 'Fashion & Beauty'),
  cat('fashionshow',    'Fashion Show',     C.pink,    '👗', 'Fashion & Beauty'),
  cat('runway',         'Runway',           C.rose,    '👠', 'Fashion & Beauty'),
  cat('streetstyle',    'Street Style',     C.slate,   '🧢', 'Fashion & Beauty'),
  cat('vintage',        'Vintage Fashion',  C.amber,   '👒', 'Fashion & Beauty'),
  cat('thriftstore',    'Thrift & Swap',    C.stone,   '♻️', 'Fashion & Beauty'),
  cat('sustainable_fashion','Sustainable Fashion',C.green,'🌿','Fashion & Beauty'),
  cat('sneakers',       'Sneaker Culture',  C.blue,    '👟', 'Fashion & Beauty'),
  cat('luxury_fashion', 'Luxury Fashion',   C.amber,   '💎', 'Fashion & Beauty'),
  cat('menswear',       'Menswear',         C.slate,   '🧥', 'Fashion & Beauty'),
  cat('womenswear',     "Women's Fashion",  C.pink,    '👗', 'Fashion & Beauty'),
  cat('kidswear',       "Kids' Fashion",    C.yellow,  '👶', 'Fashion & Beauty'),
  cat('jewellery_fashion','Jewellery',      C.yellow,  '💍', 'Fashion & Beauty'),
  cat('beauty',         'Beauty',           C.pink,    '💄', 'Fashion & Beauty'),
  cat('makeup',         'Makeup',           C.rose,    '💋', 'Fashion & Beauty'),
  cat('skincare',       'Skincare',         C.pink,    '✨', 'Fashion & Beauty'),
  cat('haircare',       'Haircare',         C.purple,  '💇', 'Fashion & Beauty'),
  cat('nailart',        'Nail Art',         C.fuchsia, '💅', 'Fashion & Beauty'),
  cat('locs',           'Locs & Braids',    C.amber,   '🪢', 'Fashion & Beauty'),
  cat('naturalhai',     'Natural Hair',     C.orange,  '💇', 'Fashion & Beauty'),
  cat('barbershop',     'Barbershop',       C.slate,   '💈', 'Fashion & Beauty'),
  cat('tattoo',         'Tattoo',           C.red,     '🎨', 'Fashion & Beauty'),
  cat('piercing',       'Piercing',         C.stone,   '💎', 'Fashion & Beauty'),
  cat('wellness_beauty','Beauty & Wellness',C.violet,  '🌸', 'Fashion & Beauty'),

  // ── TECHNOLOGY ─────────────────────────────────────────────────────────────
  cat('tech',           'Technology',       C.blue,    '💻', 'Technology'),
  cat('startup',        'Startups',         C.violet,  '🚀', 'Technology'),
  cat('hackathon',      'Hackathon',        C.blue,    '⚡', 'Technology'),
  cat('coding',         'Coding',           C.cyan,    '⌨️', 'Technology'),
  cat('webdev',         'Web Dev',          C.blue,    '🌐', 'Technology'),
  cat('mobiledev',      'Mobile Dev',       C.indigo,  '📱', 'Technology'),
  cat('ai',             'AI & Machine Learning',C.cyan, '🤖', 'Technology'),
  cat('blockchain',     'Blockchain',       C.blue,    '⛓️', 'Technology'),
  cat('crypto',         'Crypto',           C.amber,   '₿', 'Technology'),
  cat('web3',           'Web3',             C.violet,  '🌐', 'Technology'),
  cat('cybersecurity',  'Cybersecurity',    C.red,     '🔒', 'Technology'),
  cat('data_science',   'Data Science',     C.sky,     '📊', 'Technology'),
  cat('cloud',          'Cloud Computing',  C.sky,     '☁️', 'Technology'),
  cat('devops',         'DevOps',           C.teal,    '⚙️', 'Technology'),
  cat('ux_design',      'UX Design',        C.pink,    '🎨', 'Technology'),
  cat('product',        'Product',          C.indigo,  '📦', 'Technology'),
  cat('robotics',       'Robotics',         C.slate,   '🤖', 'Technology'),
  cat('iot',            'IoT',              C.teal,    '🔌', 'Technology'),
  cat('ar_vr',          'AR / VR',          C.violet,  '🥽', 'Technology'),
  cat('gaming_dev',     'Game Dev',         C.purple,  '🎮', 'Technology'),
  cat('open_source',    'Open Source',      C.green,   '💻', 'Technology'),
  cat('techworkshop',   'Tech Workshop',    C.blue,    '🛠️', 'Technology'),
  cat('techtalks',      'Tech Talks',       C.indigo,  '🎤', 'Technology'),
  cat('pitch',          'Pitch Night',      C.green,   '💡', 'Technology'),
  cat('accelerator',    'Accelerator',      C.orange,  '🚀', 'Technology'),
  cat('fintech',        'FinTech',          C.green,   '💳', 'Technology'),
  cat('healthtech',     'HealthTech',       C.teal,    '🏥', 'Technology'),
  cat('edtech',         'EdTech',           C.blue,    '📚', 'Technology'),
  cat('cleantech',      'CleanTech',        C.green,   '♻️', 'Technology'),
  cat('spacetech',      'Space & Astronomy',C.indigo,  '🚀', 'Technology'),

  // ── BUSINESS & NETWORKING ───────────────────────────────────────────────────
  cat('business',       'Business',         C.indigo,  '💼', 'Business'),
  cat('networking',     'Networking',       C.blue,    '🤝', 'Business'),
  cat('conference',     'Conference',       C.indigo,  '🎤', 'Business'),
  cat('summit',         'Summit',           C.violet,  '🏔️', 'Business'),
  cat('workshop',       'Workshop',         C.teal,    '🛠️', 'Business'),
  cat('seminar',        'Seminar',          C.blue,    '📋', 'Business'),
  cat('masterclass',    'Masterclass',      C.purple,  '🎓', 'Business'),
  cat('mentoring',      'Mentoring',        C.amber,   '🤝', 'Business'),
  cat('coaching',       'Coaching',         C.green,   '🏆', 'Business'),
  cat('leadership',     'Leadership',       C.indigo,  '👑', 'Business'),
  cat('entrepreneurship','Entrepreneurship',C.orange,  '💡', 'Business'),
  cat('investment',     'Investment',       C.green,   '📈', 'Business'),
  cat('realestate',     'Real Estate',      C.stone,   '🏠', 'Business'),
  cat('finance',        'Finance',          C.green,   '💰', 'Business'),
  cat('marketing',      'Marketing',        C.orange,  '📣', 'Business'),
  cat('branding',       'Branding',         C.red,     '🎯', 'Business'),
  cat('socialmedia',    'Social Media',     C.pink,    '📱', 'Business'),
  cat('pr',             'PR & Media',       C.violet,  '📰', 'Business'),
  cat('sales',          'Sales',            C.green,   '💵', 'Business'),
  cat('ecommerce',      'E-Commerce',       C.blue,    '🛒', 'Business'),
  cat('logistics',      'Logistics',        C.slate,   '📦', 'Business'),
  cat('legal',          'Legal',            C.indigo,  '⚖️', 'Business'),
  cat('hr',             'HR & Recruiting',  C.blue,    '👥', 'Business'),
  cat('management',     'Management',       C.slate,   '📊', 'Business'),
  cat('womeninbiz',     'Women in Business',C.pink,    '👩‍💼', 'Business'),
  cat('youthbiz',       'Youth Entrepreneurship',C.lime,'🌟','Business'),
  cat('sme',            'SME',              C.amber,   '🏪', 'Business'),
  cat('franchise',      'Franchise',        C.orange,  '🏪', 'Business'),
  cat('agribiz',        'Agri-Business',    C.lime,    '🌾', 'Business'),
  cat('creative_biz',   'Creative Business',C.fuchsia, '🎨', 'Business'),

  // ── EDUCATION ──────────────────────────────────────────────────────────────
  cat('edu',            'Education',        C.sky,     '📚', 'Education'),
  cat('school',         'School',           C.blue,    '🏫', 'Education'),
  cat('university',     'University',       C.indigo,  '🎓', 'Education'),
  cat('graduation',     'Graduation',       C.amber,   '🎓', 'Education'),
  cat('lecture',        'Lecture',          C.blue,    '📋', 'Education'),
  cat('tutorial',       'Tutorial',         C.teal,    '📖', 'Education'),
  cat('study_group',    'Study Group',      C.indigo,  '📚', 'Education'),
  cat('debate',         'Debate',           C.red,     '💬', 'Education'),
  cat('quiz',           'Quiz Night',       C.yellow,  '❓', 'Education'),
  cat('science',        'Science',          C.sky,     '🔬', 'Education'),
  cat('mathematics',    'Mathematics',      C.blue,    '🔢', 'Education'),
  cat('languages',      'Languages',        C.teal,    '🌐', 'Education'),
  cat('english',        'English',          C.blue,    '🇬🇧', 'Education'),
  cat('afrikaans',      'Afrikaans',        C.orange,  '🇿🇦', 'Education'),
  cat('zulu',           'Zulu',             C.green,   '🌍', 'Education'),
  cat('xhosa',          'Xhosa',            C.amber,   '🌍', 'Education'),
  cat('french',         'French',           C.blue,    '🇫🇷', 'Education'),
  cat('arabic',         'Arabic',           C.green,   '🇸🇦', 'Education'),
  cat('mandarin',       'Mandarin',         C.red,     '🇨🇳', 'Education'),
  cat('spanish',        'Spanish',          C.red,     '🇪🇸', 'Education'),
  cat('portuguese',     'Portuguese',       C.green,   '🇧🇷', 'Education'),
  cat('swahili',        'Swahili',          C.teal,    '🌍', 'Education'),
  cat('sign_language',  'Sign Language',    C.teal,    '🤟', 'Education'),
  cat('literacy',       'Literacy',         C.sky,     '📖', 'Education'),
  cat('tutoring',       'Tutoring',         C.blue,    '📐', 'Education'),
  cat('eduwomen',       'Girls in Education',C.pink,   '👩‍🎓', 'Education'),
  cat('stem',           'STEM',             C.blue,    '⚗️', 'Education'),
  cat('coding_kids',    'Coding for Kids',  C.lime,    '👾', 'Education'),

  // ── TRAVEL & ADVENTURE ─────────────────────────────────────────────────────
  cat('travel',         'Travel',           C.sky,     '✈️', 'Travel'),
  cat('adventure',      'Adventure',        C.green,   '🌿', 'Travel'),
  cat('camping',        'Camping',          C.lime,    '⛺', 'Travel'),
  cat('glamping',       'Glamping',         C.amber,   '🏕️', 'Travel'),
  cat('roadtrip',       'Road Trip',        C.orange,  '🚗', 'Travel'),
  cat('backpacking',    'Backpacking',      C.stone,   '🎒', 'Travel'),
  cat('safaari',        'Safari',           C.amber,   '🦁', 'Travel'),
  cat('beachtrip',      'Beach Trip',       C.sky,     '🏖️', 'Travel'),
  cat('island_hopping', 'Island Hopping',   C.cyan,    '🏝️', 'Travel'),
  cat('cruise',         'Cruise',           C.blue,    '🚢', 'Travel'),
  cat('citybreak',      'City Break',       C.indigo,  '🏙️', 'Travel'),
  cat('voluntourism',   'Voluntourism',     C.green,   '🌍', 'Travel'),
  cat('cultural_tour',  'Cultural Tour',    C.orange,  '🗺️', 'Travel'),
  cat('food_tour',      'Food Tour',        C.amber,   '🍜', 'Travel'),
  cat('wine_tour',      'Wine Tour',        C.rose,    '🍷', 'Travel'),
  cat('motorcycle',     'Motorcycle Ride',  C.red,     '🏍️', 'Travel'),
  cat('trekkings',      'Trekking',         C.green,   '🥾', 'Travel'),
  cat('skydiving',      'Skydiving',        C.sky,     '🪂', 'Travel'),
  cat('bungee',         'Bungee Jumping',   C.red,     '🪂', 'Travel'),
  cat('paragliding',    'Paragliding',      C.sky,     '🪂', 'Travel'),
  cat('whitewater',     'White-Water Rafting',C.sky,   '🌊', 'Travel'),
  cat('spelunking',     'Cave Exploration', C.stone,   '🕳️', 'Travel'),
  cat('stargazing',     'Stargazing',       C.indigo,  '⭐', 'Travel'),
  cat('birdwatching',   'Birdwatching',     C.lime,    '🦜', 'Travel'),
  cat('wildflowers',    'Nature Walk',      C.green,   '🌸', 'Travel'),
  cat('sunrise_hike',   'Sunrise Hike',     C.amber,   '🌄', 'Travel'),
  cat('night_hike',     'Night Hike',       C.indigo,  '🌙', 'Travel'),

  // ── GAMING ─────────────────────────────────────────────────────────────────
  cat('gaming',         'Gaming',           C.purple,  '🎮', 'Gaming'),
  cat('esports',        'Esports',          C.blue,    '🕹️', 'Gaming'),
  cat('lan_party',      'LAN Party',        C.cyan,    '🖥️', 'Gaming'),
  cat('gaming_tourney', 'Gaming Tournament',C.red,     '🏆', 'Gaming'),
  cat('retro_gaming',   'Retro Gaming',     C.stone,   '👾', 'Gaming'),
  cat('tabletop',       'Tabletop RPG',     C.amber,   '🎲', 'Gaming'),
  cat('boardgames',     'Board Games',      C.yellow,  '♟️', 'Gaming'),
  cat('cardgames',      'Card Games',       C.red,     '🃏', 'Gaming'),
  cat('poker',          'Poker',            C.green,   '🃏', 'Gaming'),
  cat('chess_event',    'Chess',            C.slate,   '♟️', 'Gaming'),
  cat('puzzles',        'Puzzles',          C.teal,    '🧩', 'Gaming'),
  cat('vrgaming',       'VR Gaming',        C.violet,  '🥽', 'Gaming'),
  cat('mobile_gaming',  'Mobile Gaming',    C.blue,    '📱', 'Gaming'),
  cat('speedrun',       'Speedrun',         C.lime,    '⚡', 'Gaming'),
  cat('minecraft',      'Minecraft',        C.green,   '⛏️', 'Gaming'),
  cat('cosplay_gaming', 'Gaming Cosplay',   C.fuchsia, '🎭', 'Gaming'),
  cat('streamer',       'Streamer Meet',    C.purple,  '🎥', 'Gaming'),

  // ── SOCIAL & COMMUNITY ──────────────────────────────────────────────────────
  cat('social',         'Social',           C.pink,    '👥', 'Social'),
  cat('meetup',         'Meetup',           C.blue,    '🤝', 'Social'),
  cat('party',          'Party',            C.pink,    '🎉', 'Social'),
  cat('birthday',       'Birthday',         C.yellow,  '🎂', 'Social'),
  cat('anniversary',    'Anniversary',      C.rose,    '🥂', 'Social'),
  cat('wedding',        'Wedding',          C.pink,    '💍', 'Social'),
  cat('engagement',     'Engagement',       C.rose,    '💍', 'Social'),
  cat('babyshower',     'Baby Shower',      C.sky,     '👶', 'Social'),
  cat('graduation_party','Graduation Party',C.amber,   '🎓', 'Social'),
  cat('housewarming',   'Housewarming',     C.amber,   '🏠', 'Social'),
  cat('rooftop',        'Rooftop Party',    C.cyan,    '🏙️', 'Social'),
  cat('pool_party',     'Pool Party',       C.sky,     '🏊', 'Social'),
  cat('beach_party',    'Beach Party',      C.yellow,  '🏖️', 'Social'),
  cat('garden_party',   'Garden Party',     C.green,   '🌸', 'Social'),
  cat('house_party',    'House Party',      C.orange,  '🏠', 'Social'),
  cat('vip_event',      'VIP',              C.amber,   '💎', 'Social'),
  cat('speed_dating',   'Speed Dating',     C.rose,    '💘', 'Social'),
  cat('singles_night',  'Singles Night',    C.pink,    '💖', 'Social'),
  cat('dating',         'Social & Dating',  C.pink,    '💘', 'Social'),
  cat('lgbtq',          'LGBTQ+',           C.orange,  '🏳️‍🌈', 'Social'),
  cat('pride',          'Pride',            C.rainbow, '🌈', 'Social'),
  cat('community',      'Community',        C.green,   '🏘️', 'Social'),
  cat('charity',        'Charity',          C.teal,    '❤️', 'Social'),
  cat('fundraiser',     'Fundraiser',       C.green,   '💰', 'Social'),
  cat('volunteering',   'Volunteering',     C.lime,    '🙌', 'Social'),
  cat('neighbourhood',  'Neighbourhood',    C.green,   '🏘️', 'Social'),
  cat('reunion',        'Reunion',          C.amber,   '🤗', 'Social'),
  cat('memorial',       'Memorial',         C.stone,   '🕯️', 'Social'),

  // ── KIDS & FAMILY ──────────────────────────────────────────────────────────
  cat('kids',           'Kids & Family',    C.yellow,  '👨‍👩‍👧', 'Family'),
  cat('parenting',      'Parenting',        C.amber,   '👶', 'Family'),
  cat('babies',         'Babies',           C.sky,     '🍼', 'Family'),
  cat('toddlers',       'Toddlers',         C.yellow,  '🧸', 'Family'),
  cat('playdate',       'Playdate',         C.lime,    '🛝', 'Family'),
  cat('kidsfitness',    "Kids' Fitness",    C.green,   '🤸', 'Family'),
  cat('storytime',      'Story Time',       C.amber,   '📖', 'Family'),
  cat('kidscooking',    "Kids' Cooking",    C.orange,  '👨‍🍳', 'Family'),
  cat('kidsart',        "Kids' Art",        C.pink,    '🎨', 'Family'),
  cat('kidssports',     "Kids' Sports",     C.green,   '⚽', 'Family'),
  cat('carnival',       'Carnival',         C.yellow,  '🎡', 'Family'),
  cat('funfair',        'Fun Fair',         C.orange,  '🎠', 'Family'),
  cat('familydayout',   'Family Day Out',   C.lime,    '🌳', 'Family'),
  cat('homeschool',     'Homeschool',       C.blue,    '🏠', 'Family'),
  cat('seniors',        '55+',              C.slate,   '👴', 'Family'),
  cat('youth',          'Youth',            C.lime,    '👦', 'Family'),

  // ── FAITH & SPIRITUALITY ────────────────────────────────────────────────────
  cat('religion',       'Faith',            C.violet,  '🙏', 'Faith'),
  cat('christianity',   'Christianity',     C.blue,    '✝️', 'Faith'),
  cat('islam',          'Islam',            C.green,   '☪️', 'Faith'),
  cat('judaism',        'Judaism',          C.blue,    '✡️', 'Faith'),
  cat('hinduism',       'Hinduism',         C.orange,  '🕉️', 'Faith'),
  cat('buddhism',       'Buddhism',         C.amber,   '☸️', 'Faith'),
  cat('traditional',    'Traditional',      C.amber,   '🌿', 'Faith'),
  cat('interfaith',     'Interfaith',       C.teal,    '🌍', 'Faith'),
  cat('prayer',         'Prayer',           C.indigo,  '🙏', 'Faith'),
  cat('bible_study',    'Bible Study',      C.blue,    '📖', 'Faith'),
  cat('retreat',        'Retreat',          C.violet,  '🌿', 'Faith'),
  cat('crusade',        'Crusade',          C.amber,   '✝️', 'Faith'),
  cat('eid',            'Eid',              C.green,   '🌙', 'Faith'),
  cat('diwali',         'Diwali',           C.yellow,  '🪔', 'Faith'),
  cat('hanukkah',       'Hanukkah',         C.blue,    '🕎', 'Faith'),
  cat('christmas',      'Christmas',        C.red,     '🎄', 'Faith'),
  cat('easter',         'Easter',           C.lime,    '🐣', 'Faith'),
  cat('ramadan',        'Ramadan',          C.green,   '🌙', 'Faith'),
  cat('passover',       'Passover',         C.amber,   '🍷', 'Faith'),
  cat('navratri',       'Navratri',         C.pink,    '💃', 'Faith'),

  // ── POLITICS & CIVIC ────────────────────────────────────────────────────────
  cat('politics',       'Civic',            C.indigo,  '🗳️', 'Civic'),
  cat('activist',       'Activism',         C.red,     '✊', 'Civic'),
  cat('protest',        'Protest',          C.red,     '✊', 'Civic'),
  cat('townhall',       'Town Hall',        C.indigo,  '🏛️', 'Civic'),
  cat('election',       'Election',         C.blue,    '🗳️', 'Civic'),
  cat('panel',          'Panel Discussion', C.violet,  '💬', 'Civic'),
  cat('petition',       'Petition',         C.orange,  '📝', 'Civic'),
  cat('human_rights',   'Human Rights',     C.red,     '✊', 'Civic'),
  cat('gender_rights',  'Gender Rights',    C.pink,    '♀️', 'Civic'),
  cat('environment',    'Environment',      C.green,   '🌿', 'Civic'),
  cat('climate',        'Climate Action',   C.teal,    '🌍', 'Civic'),
  cat('clean_up',       'Clean-Up',         C.lime,    '♻️', 'Civic'),
  cat('tree_planting',  'Tree Planting',    C.green,   '🌳', 'Civic'),
  cat('food_drive',     'Food Drive',       C.amber,   '🍱', 'Civic'),
  cat('indigenous',     'Indigenous',       C.amber,   '🌾', 'Civic'),
  cat('social_justice', 'Social Justice',   C.red,     '⚖️', 'Civic'),

  // ── HEALTH ─────────────────────────────────────────────────────────────────
  cat('health',         'Health',           C.teal,    '🏥', 'Health'),
  cat('medicine',       'Medicine',         C.red,     '💊', 'Health'),
  cat('mental_wellness','Mental Wellness',  C.violet,  '🧠', 'Health'),
  cat('therapy',        'Therapy',          C.indigo,  '💬', 'Health'),
  cat('rehab',          'Rehab',            C.teal,    '🏥', 'Health'),
  cat('fundraise_health','Health Fundraiser',C.red,    '❤️', 'Health'),
  cat('blood_drive',    'Blood Drive',      C.red,     '🩸', 'Health'),
  cat('hiv_aids',       'HIV Awareness',    C.red,     '❤️', 'Health'),
  cat('cancer',         'Cancer Awareness', C.pink,    '🎗️', 'Health'),
  cat('diabetes',       'Diabetes',         C.blue,    '💙', 'Health'),
  cat('womens_health',  "Women's Health",   C.pink,    '👩', 'Health'),
  cat('mens_health',    "Men's Health",     C.blue,    '👨', 'Health'),
  cat('reproductive',   'Reproductive Health',C.rose,  '❤️', 'Health'),
  cat('addiction',      'Addiction Recovery',C.teal,   '🤝', 'Health'),
  cat('grief',          'Grief Support',    C.stone,   '🕊️', 'Health'),
  cat('disability',     'Disability',       C.sky,     '♿', 'Health'),
  cat('autism',         'Autism Awareness', C.blue,    '🧩', 'Health'),

  // ── SCIENCE & NATURE ────────────────────────────────────────────────────────
  cat('science_event',  'Science',          C.sky,     '🔬', 'Science'),
  cat('astronomy',      'Astronomy',        C.indigo,  '🌌', 'Science'),
  cat('physics',        'Physics',          C.blue,    '⚛️', 'Science'),
  cat('biology',        'Biology',          C.lime,    '🧬', 'Science'),
  cat('chemistry',      'Chemistry',        C.cyan,    '⚗️', 'Science'),
  cat('geology',        'Geology',          C.stone,   '🪨', 'Science'),
  cat('marine',         'Marine Life',      C.sky,     '🐬', 'Science'),
  cat('wildlife',       'Wildlife',         C.green,   '🦁', 'Science'),
  cat('conservation',   'Conservation',     C.green,   '🌿', 'Science'),
  cat('nature',         'Nature',           C.green,   '🌳', 'Science'),
  cat('gardening',      'Gardening',        C.lime,    '🌱', 'Science'),
  cat('urban_farming',  'Urban Farming',    C.lime,    '🌾', 'Science'),
  cat('composting',     'Composting',       C.green,   '♻️', 'Science'),
  cat('beekeeping',     'Beekeeping',       C.amber,   '🐝', 'Science'),
  cat('animals',        'Animals & Pets',   C.amber,   '🐾', 'Science'),
  cat('pets',           'Pets',             C.lime,    '🐾', 'Science'),
  cat('dogs',           'Dogs',             C.amber,   '🐕', 'Science'),
  cat('cats',           'Cats',             C.yellow,  '🐱', 'Science'),
  cat('horses',         'Horses',           C.stone,   '🐎', 'Science'),

  // ── VIRTUAL & ONLINE ─────────────────────────────────────────────────────────
  cat('virtual',        'Virtual',          C.indigo,  '💻', 'Virtual'),
  cat('webinar',        'Webinar',          C.blue,    '🖥️', 'Virtual'),
  cat('livestream',     'Livestream',       C.red,     '📡', 'Virtual'),
  cat('podcast',        'Podcast',          C.purple,  '🎙️', 'Virtual'),
  cat('online_course',  'Online Course',    C.teal,    '🎓', 'Virtual'),
  cat('virtual_concert','Virtual Concert',  C.violet,  '🎵', 'Virtual'),
  cat('virtual_tour',   'Virtual Tour',     C.sky,     '🌐', 'Virtual'),
  cat('online_party',   'Online Party',     C.pink,    '🎉', 'Virtual'),
  cat('discord',        'Discord',          C.indigo,  '💬', 'Virtual'),
  cat('zoom_event',     'Zoom Event',       C.blue,    '🎥', 'Virtual'),
  cat('clubhouse',      'Clubhouse',        C.orange,  '🎤', 'Virtual'),

  // ── NIGHTLIFE ──────────────────────────────────────────────────────────────
  cat('nightlife',      'Nightlife',        C.violet,  '🌙', 'Nightlife'),
  cat('bar_night',      'Bar Night',        C.amber,   '🍸', 'Nightlife'),
  cat('lounge',         'Lounge',           C.indigo,  '🛋️', 'Nightlife'),
  cat('jazz_bar',       'Jazz Bar',         C.amber,   '🎷', 'Nightlife'),
  cat('comedy_night',   'Comedy Night',     C.yellow,  '😂', 'Nightlife'),
  cat('karaoke_bar',    'Karaoke Bar',      C.pink,    '🎤', 'Nightlife'),
  cat('trivia_night',   'Trivia Night',     C.indigo,  '❓', 'Nightlife'),
  cat('game_night',     'Game Night',       C.lime,    '🎲', 'Nightlife'),
  cat('movie_night',    'Movie Night',      C.slate,   '🎬', 'Nightlife'),
  cat('drag',           'Drag Show',        C.fuchsia, '👑', 'Nightlife'),
  cat('burlesque',      'Burlesque',        C.rose,    '💃', 'Nightlife'),

  // ── MARKETS & SHOPPING ─────────────────────────────────────────────────────
  cat('market',         'Market',           C.orange,  '🛒', 'Markets'),
  cat('crafts_market',  'Crafts Market',    C.amber,   '✂️', 'Markets'),
  cat('artmarket',      'Art Market',       C.fuchsia, '🎨', 'Markets'),
  cat('pop_up',         'Pop-Up',           C.pink,    '🏪', 'Markets'),
  cat('car_boot',       'Car Boot',         C.stone,   '🚗', 'Markets'),
  cat('flea_market',    'Flea Market',      C.amber,   '🛍️', 'Markets'),
  cat('fashion_market', 'Fashion Market',   C.pink,    '👗', 'Markets'),
  cat('tech_market',    'Tech Market',      C.blue,    '💻', 'Markets'),
  cat('bookfair',       'Book Fair',        C.stone,   '📚', 'Markets'),
  cat('plant_sale',     'Plant Sale',       C.lime,    '🌱', 'Markets'),
  cat('food_swap',      'Food Swap',        C.green,   '🥦', 'Markets'),

  // ── CARS & MOTORS ──────────────────────────────────────────────────────────
  cat('cars',           'Cars',             C.slate,   '🚗', 'Cars & Motors'),
  cat('carshow',        'Car Show',         C.red,     '🚗', 'Cars & Motors'),
  cat('carwash',        'Car Wash',         C.sky,     '🚿', 'Cars & Motors'),
  cat('motorsport',     'Motorsport',       C.red,     '🏎️', 'Cars & Motors'),
  cat('karting',        'Karting',          C.orange,  '🏎️', 'Cars & Motors'),
  cat('f1',             'F1 Watch Party',   C.red,     '🏁', 'Cars & Motors'),
  cat('classic_cars',   'Classic Cars',     C.amber,   '🚙', 'Cars & Motors'),
  cat('offroad',        'Off-Road',         C.stone,   '🚙', 'Cars & Motors'),
  cat('motorbikes',     'Motorbikes',       C.slate,   '🏍️', 'Cars & Motors'),
  cat('trucks',         'Trucks',           C.stone,   '🚚', 'Cars & Motors'),

  // ── BOOKS & WRITING ────────────────────────────────────────────────────────
  cat('books',          'Books',            C.stone,   '📖', 'Books & Writing'),
  cat('bookclub',       'Book Club',        C.amber,   '📚', 'Books & Writing'),
  cat('author_talk',    'Author Talk',      C.indigo,  '🎤', 'Books & Writing'),
  cat('creative_writing','Creative Writing',C.violet,  '✍️', 'Books & Writing'),
  cat('journalism',     'Journalism',       C.blue,    '📰', 'Books & Writing'),
  cat('publishing',     'Publishing',       C.stone,   '📚', 'Books & Writing'),
  cat('blogging',       'Blogging',         C.teal,    '💻', 'Books & Writing'),
  cat('zine',           'Zine',             C.pink,    '📰', 'Books & Writing'),
  cat('comics',         'Comics',           C.orange,  '💥', 'Books & Writing'),
  cat('screenwriting',  'Screenwriting',    C.red,     '🎬', 'Books & Writing'),

  // ── HOBBIES & MISC ─────────────────────────────────────────────────────────
  cat('hobbies',        'Hobbies',          C.teal,    '🎯', 'Hobbies'),
  cat('astronomy_hobby','Astronomy',        C.indigo,  '🔭', 'Hobbies'),
  cat('meteorology',    'Meteorology',      C.sky,     '⛅', 'Hobbies'),
  cat('geology_hobby',  'Rock Collecting',  C.stone,   '🪨', 'Hobbies'),
  cat('magic',          'Magic',            C.violet,  '🎩', 'Hobbies'),
  cat('circus',         'Circus Arts',      C.red,     '🎪', 'Hobbies'),
  cat('juggling',       'Juggling',         C.orange,  '🤹', 'Hobbies'),
  cat('kite_flying',    'Kite Flying',      C.sky,     '🪁', 'Hobbies'),
  cat('model_making',   'Model Making',     C.stone,   '✈️', 'Hobbies'),
  cat('drone_racing',   'Drone Racing',     C.cyan,    '🚁', 'Hobbies'),
  cat('rc_cars',        'RC Cars',          C.red,     '🚗', 'Hobbies'),
  cat('board_sports',   'Board Sports',     C.slate,   '🛹', 'Hobbies'),
  cat('rollerblading',  'Rollerblading',    C.orange,  '🛼', 'Hobbies'),
  cat('scooter',        'Scooter',          C.lime,    '🛴', 'Hobbies'),
  cat('foraging',       'Foraging',         C.lime,    '🍄', 'Hobbies'),
  cat('mycology',       'Mycology',         C.stone,   '🍄', 'Hobbies'),
  cat('numismatics',    'Coin Collecting',  C.amber,   '🪙', 'Hobbies'),
  cat('stamps',         'Stamp Collecting', C.indigo,  '📮', 'Hobbies'),
  cat('antiques',       'Antiques',         C.stone,   '🏺', 'Hobbies'),
  cat('escape_room',    'Escape Room',      C.red,     '🔐', 'Hobbies'),
  cat('murder_mystery', 'Murder Mystery',   C.slate,   '🔍', 'Hobbies'),
  cat('wine_beer_hobby','Home Brewing',     C.amber,   '🍺', 'Hobbies'),
  cat('perfumery',      'Perfumery',        C.pink,    '🌸', 'Hobbies'),
  cat('feng_shui',      'Feng Shui',        C.teal,    '🌿', 'Hobbies'),
  cat('tarot',          'Tarot',            C.violet,  '🃏', 'Hobbies'),
  cat('astrology',      'Astrology',        C.indigo,  '⭐', 'Hobbies'),
  cat('zodiac',         'Zodiac',           C.violet,  '♈', 'Hobbies'),
];

// Quick lookup by key
export const ALL_CATEGORIES_MAP = Object.fromEntries(
  ALL_CATEGORIES.map(c => [c.key, c])
);

// Unique group names
export const CATEGORY_GROUPS = [...new Set(ALL_CATEGORIES.map(c => c.group))];

export const searchCategories = (query) => {
  if (!query.trim()) return ALL_CATEGORIES;
  const q = query.toLowerCase();
  return ALL_CATEGORIES.filter(c =>
    c.label.toLowerCase().includes(q) ||
    c.group.toLowerCase().includes(q) ||
    c.key.toLowerCase().includes(q)
  );
};
