/**
 * The Gruvs — Master Category Registry
 * 1000+ curated categories spanning every domain of human interest.
 * Each entry: { key, label, color, icon, group }
 */

const C = {
  purple:  '#8b5cf6', violet: '#7c3aed', indigo: '#6366f1',
  blue:    '#3b82f6', sky:    '#0ea5e9', cyan:   '#06b6d4',
  teal:    '#0d9488', green:  '#10b981', lime:   '#84cc16',
  yellow:  '#f59e0b', amber:  '#d97706', orange: '#f97316',
  red:     '#ef4444', rose:   '#f43f5e', pink:   '#ec4899',
  fuchsia: '#d946ef', slate:  '#64748b', stone:  '#78716c',
};

const cat = (key, label, color, icon, group) => ({ key, label, color, icon, group });

export const ALL_CATEGORIES = [

  // ── MUSIC ──────────────────────────────────────────────────────────────────
  cat('music',          'Music',            C.purple,  'music', 'Music'),
  cat('afrobeats',      'Afrobeats',        C.orange,  'music-note', 'Music'),
  cat('amapiano',       'Amapiano',         C.fuchsia, 'piano', 'Music'),
  cat('afrojuju',       'Afro Juju',        C.amber,   'drum', 'Music'),
  cat('highlife',       'Highlife',         C.yellow,  'trumpet', 'Music'),
  cat('fuji',           'Fuji',             C.orange,  'drum', 'Music'),
  cat('afropop',        'Afropop',          C.pink,    'microphone-variant', 'Music'),
  cat('gospel',         'Gospel',           C.indigo,  'hands-pray', 'Music'),
  cat('choir',          'Choir',            C.blue,    'music-clef-treble', 'Music'),
  cat('hiphop',         'Hip-Hop',          C.purple,  'headphones', 'Music'),
  cat('rap',            'Rap',              C.slate,   'microphone-variant', 'Music'),
  cat('trap',           'Trap',             C.violet,  'volume-high', 'Music'),
  cat('drill',          'Drill',            C.slate,   'music', 'Music'),
  cat('rnb',            'R&B',              C.rose,    'heart', 'Music'),
  cat('soul',           'Soul',             C.fuchsia, 'music-note', 'Music'),
  cat('neosoul',        'Neo-Soul',         C.purple,  'guitar-electric', 'Music'),
  cat('jazz',           'Jazz',             C.amber,   'saxophone', 'Music'),
  cat('blues',          'Blues',            C.blue,    'guitar-electric', 'Music'),
  cat('classical',      'Classical',        C.indigo,  'violin', 'Music'),
  cat('opera',          'Opera',            C.red,     'drama-masks', 'Music'),
  cat('orchestral',     'Orchestral',       C.indigo,  'music-clef-treble', 'Music'),
  cat('electronic',     'Electronic',       C.cyan,    'tune', 'Music'),
  cat('edm',            'EDM',              C.blue,    'flash', 'Music'),
  cat('house',          'House',            C.sky,     'music-note', 'Music'),
  cat('deephouse',      'Deep House',       C.teal,    'music-note', 'Music'),
  cat('techhouse',      'Tech House',       C.cyan,    'music-note', 'Music'),
  cat('afrohouse',      'Afro House',       C.orange,  'music-note', 'Music'),
  cat('techno',         'Techno',           C.slate,   'volume-high', 'Music'),
  cat('trance',         'Trance',           C.violet,  'sync', 'Music'),
  cat('psytrance',      'Psytrance',        C.purple,  'sync', 'Music'),
  cat('dubstep',        'Dubstep',          C.blue,    'volume-high', 'Music'),
  cat('dnb',            'Drum & Bass',      C.indigo,  'drum', 'Music'),
  cat('jungle',         'Jungle',           C.green,   'music-note', 'Music'),
  cat('grime',          'Grime',            C.slate,   'microphone-variant', 'Music'),
  cat('ukgarage',       'UK Garage',        C.sky,     'music-note', 'Music'),
  cat('ambient',        'Ambient',          C.teal,    'waves', 'Music'),
  cat('lofi',           'Lo-Fi',            C.stone,   'coffee', 'Music'),
  cat('chillout',       'Chillout',         C.sky,     'weather-night', 'Music'),
  cat('downtempo',      'Downtempo',        C.teal,    'music-note', 'Music'),
  cat('triphop',        'Trip-Hop',         C.purple,  'music-note', 'Music'),
  cat('reggae',         'Reggae',           C.green,   'leaf', 'Music'),
  cat('dancehall',      'Dancehall',        C.yellow,  'dance-ballroom', 'Music'),
  cat('soca',           'Soca',             C.orange,  'party-popper', 'Music'),
  cat('calypso',        'Calypso',          C.yellow,  'music-note', 'Music'),
  cat('latin',          'Latin',            C.red,     'chili-hot', 'Music'),
  cat('salsa',          'Salsa',            C.red,     'dance-ballroom', 'Music'),
  cat('merengue',       'Merengue',         C.orange,  'music-note', 'Music'),
  cat('bachata',        'Bachata',          C.rose,    'dance-ballroom', 'Music'),
  cat('cumbia',         'Cumbia',           C.yellow,  'music-note', 'Music'),
  cat('reggaeton',      'Reggaeton',        C.orange,  'microphone-variant', 'Music'),
  cat('country',        'Country',          C.amber,   'hat-fedora', 'Music'),
  cat('folk',           'Folk',             C.stone,   'guitar-acoustic', 'Music'),
  cat('bluegrass',      'Bluegrass',        C.green,   'guitar-acoustic', 'Music'),
  cat('americana',      'Americana',        C.amber,   'guitar-electric', 'Music'),
  cat('indie',          'Indie',            C.purple,  'guitar-electric', 'Music'),
  cat('alternative',    'Alternative',      C.violet,  'guitar-electric', 'Music'),
  cat('punk',           'Punk',             C.red,     'hand-back-right', 'Music'),
  cat('metal',          'Metal',            C.slate,   'hand-back-right', 'Music'),
  cat('deathmetal',     'Death Metal',      C.red,     'hand-back-right', 'Music'),
  cat('blackmetal',     'Black Metal',      C.slate,   'hand-back-right', 'Music'),
  cat('progmetal',      'Prog Metal',       C.violet,  'guitar-electric', 'Music'),
  cat('nymetal',        'Nu-Metal',         C.orange,  'guitar-electric', 'Music'),
  cat('emo',            'Emo',              C.violet,  'heart', 'Music'),
  cat('postrock',       'Post-Rock',        C.teal,    'guitar-electric', 'Music'),
  cat('shoegaze',       'Shoegaze',         C.sky,     'guitar-electric', 'Music'),
  cat('dreampop',       'Dream Pop',        C.pink,    'weather-night', 'Music'),
  cat('synthpop',       'Synth-Pop',        C.cyan,    'piano', 'Music'),
  cat('newwave',        'New Wave',         C.indigo,  'piano', 'Music'),
  cat('disco',          'Disco',            C.pink,    'mirror', 'Music'),
  cat('funk',           'Funk',             C.orange,  'guitar-electric', 'Music'),
  cat('groove',         'Groove',           C.amber,   'music-note', 'Music'),
  cat('kpop',           'K-Pop',            C.pink,    'flag', 'Music'),
  cat('jpop',           'J-Pop',            C.sky,     'flag', 'Music'),
  cat('cpop',           'C-Pop',            C.red,     'flag', 'Music'),
  cat('bollywood',      'Bollywood',        C.yellow,  'movie-open', 'Music'),
  cat('qawwali',        'Qawwali',          C.amber,   'music-note', 'Music'),
  cat('bhangra',        'Bhangra',          C.orange,  'drum', 'Music'),
  cat('carnatic',       'Carnatic',         C.amber,   'music', 'Music'),
  cat('hindustani',     'Hindustani',       C.yellow,  'music', 'Music'),
  cat('celtic',         'Celtic',           C.green,   'clover', 'Music'),
  cat('worldmusic',     'World Music',      C.teal,    'earth', 'Music'),
  cat('afrofusion',     'Afro-Fusion',      C.orange,  'earth', 'Music'),
  cat('gospel_praise',  'Praise & Worship', C.indigo,  'cross', 'Music'),
  cat('acapella',       'A Cappella',       C.blue,    'microphone-variant', 'Music'),
  cat('karaoke',        'Karaoke',          C.pink,    'microphone-variant', 'Music'),
  cat('open_mic',       'Open Mic',         C.amber,   'microphone', 'Music'),
  cat('battle',         'Battle',           C.red,     'sword-cross', 'Music'),
  cat('djset',          'DJ Set',           C.cyan,    'headphones', 'Music'),
  cat('liveband',       'Live Band',        C.purple,  'guitar-electric', 'Music'),
  cat('concert',        'Concert',          C.violet,  'ticket', 'Music'),
  cat('festival_music', 'Music Festival',   C.yellow,  'tent', 'Music'),
  cat('rave',           'Rave',             C.cyan,    'sync', 'Music'),
  cat('club_night',     'Club Night',       C.fuchsia, 'weather-night', 'Music'),

  // ── DANCE ──────────────────────────────────────────────────────────────────
  cat('dance',          'Dance',            C.pink,    'dance-ballroom', 'Dance'),
  cat('ballet',         'Ballet',           C.rose,    'shoe-ballet', 'Dance'),
  cat('contemporary',   'Contemporary',     C.violet,  'dance-ballroom', 'Dance'),
  cat('hiphop_dance',   'Hip-Hop Dance',    C.purple,  'dance-ballroom', 'Dance'),
  cat('breakdance',     'Breakdancing',     C.orange,  'dance-ballroom', 'Dance'),
  cat('streetdance',    'Street Dance',     C.slate,   'dance-ballroom', 'Dance'),
  cat('afrobeats_dance','Afrobeats Dance',  C.orange,  'dance-ballroom', 'Dance'),
  cat('amapiano_dance', 'Amapiano Dance',   C.fuchsia, 'dance-ballroom', 'Dance'),
  cat('gqom_dance',     'Gqom Dance',       C.cyan,    'dance-ballroom', 'Dance'),
  cat('kizomba',        'Kizomba',          C.rose,    'dance-ballroom', 'Dance'),
  cat('zouk',           'Zouk',             C.pink,    'dance-ballroom', 'Dance'),
  cat('twerking',       'Twerk',            C.orange,  'dance-ballroom', 'Dance'),
  cat('linedance',      'Line Dance',       C.amber,   'hat-fedora', 'Dance'),
  cat('swing',          'Swing',            C.yellow,  'dance-ballroom', 'Dance'),
  cat('waltz',          'Waltz',            C.indigo,  'dance-ballroom', 'Dance'),
  cat('tango',          'Tango',            C.red,     'dance-ballroom', 'Dance'),
  cat('tap_dance',      'Tap Dance',        C.amber,   'hat-fedora', 'Dance'),
  cat('bollywood_dance','Bollywood Dance',  C.yellow,  'dance-ballroom', 'Dance'),
  cat('kathak',         'Kathak',           C.orange,  'dance-ballroom', 'Dance'),
  cat('flamenco',       'Flamenco',         C.red,     'dance-ballroom', 'Dance'),
  cat('irish_dance',    'Irish Dance',      C.green,   'clover', 'Dance'),
  cat('danceworkshop',  'Dance Workshop',   C.teal,    'school', 'Dance'),
  cat('dancebattle',    'Dance Battle',     C.red,     'sword-cross', 'Dance'),
  cat('dancesocial',    'Social Dancing',   C.pink,    'party-popper', 'Dance'),

  // ── SPORT ──────────────────────────────────────────────────────────────────
  cat('sport',          'Sport',            C.green,   'trophy', 'Sport'),
  cat('football',       'Football',         C.green,   'soccer', 'Sport'),
  cat('basketball',     'Basketball',       C.orange,  'basketball', 'Sport'),
  cat('tennis',         'Tennis',           C.lime,    'tennis', 'Sport'),
  cat('cricket',        'Cricket',          C.green,   'cricket', 'Sport'),
  cat('rugby',          'Rugby',            C.amber,   'rugby', 'Sport'),
  cat('boxing',         'Boxing',           C.red,     'boxing-glove', 'Sport'),
  cat('mma',            'MMA',              C.red,     'karate', 'Sport'),
  cat('wrestling',      'Wrestling',        C.orange,  'wrestling', 'Sport'),
  cat('athletics',      'Athletics',        C.yellow,  'run', 'Sport'),
  cat('swimming',       'Swimming',         C.sky,     'swim', 'Sport'),
  cat('cycling',        'Cycling',          C.lime,    'bike', 'Sport'),
  cat('triathlon',      'Triathlon',        C.teal,    'swim', 'Sport'),
  cat('marathon',       'Marathon',         C.orange,  'run', 'Sport'),
  cat('crossfit',       'CrossFit',         C.red,     'arm-flex', 'Sport'),
  cat('weightlifting',  'Weightlifting',    C.slate,   'weight-lifter', 'Sport'),
  cat('powerlifting',   'Powerlifting',     C.stone,   'weight-lifter', 'Sport'),
  cat('bodybuilding',   'Bodybuilding',     C.amber,   'arm-flex', 'Sport'),
  cat('calisthenics',   'Calisthenics',     C.green,   'arm-flex', 'Sport'),
  cat('gymnastics',     'Gymnastics',       C.pink,    'gymnastics', 'Sport'),
  cat('parkour',        'Parkour',          C.slate,   'run', 'Sport'),
  cat('rockclimbing',   'Rock Climbing',    C.stone,   'climbing', 'Sport'),
  cat('bouldering',     'Bouldering',       C.orange,  'climbing', 'Sport'),
  cat('hiking',         'Hiking',           C.green,   'hiking', 'Sport'),
  cat('trailrunning',   'Trail Running',    C.lime,    'run', 'Sport'),
  cat('mountainbike',   'Mountain Biking',  C.green,   'bike', 'Sport'),
  cat('bmx',            'BMX',              C.orange,  'bicycle', 'Sport'),
  cat('skateboarding',  'Skateboarding',    C.slate,   'skateboard', 'Sport'),
  cat('surfing',        'Surfing',          C.sky,     'surfing', 'Sport'),
  cat('snowboarding',   'Snowboarding',     C.sky,     'snowboard', 'Sport'),
  cat('skiing',         'Skiing',           C.blue,    'ski', 'Sport'),
  cat('iceskating',     'Ice Skating',      C.sky,     'skate', 'Sport'),
  cat('icehockey',      'Ice Hockey',       C.blue,    'hockey-sticks', 'Sport'),
  cat('fieldhockey',    'Field Hockey',     C.green,   'hockey-puck', 'Sport'),
  cat('baseball',       'Baseball',         C.red,     'baseball', 'Sport'),
  cat('softball',       'Softball',         C.yellow,  'baseball-bat', 'Sport'),
  cat('americanfootball','American Football',C.orange, 'football', 'Sport'),
  cat('volleyball',     'Volleyball',       C.orange,  'volleyball', 'Sport'),
  cat('beachvolleyball','Beach Volleyball',  C.yellow,  'volleyball', 'Sport'),
  cat('tabletennis',    'Table Tennis',     C.blue,    'table-tennis', 'Sport'),
  cat('badminton',      'Badminton',        C.lime,    'badminton', 'Sport'),
  cat('squash',         'Squash',           C.green,   'tennis', 'Sport'),
  cat('handball',       'Handball',         C.orange,  'handball', 'Sport'),
  cat('netball',        'Netball',          C.teal,    'basketball', 'Sport'),
  cat('polo',           'Polo',             C.green,   'horse', 'Sport'),
  cat('equestrian',     'Equestrian',       C.amber,   'horse', 'Sport'),
  cat('archery',        'Archery',          C.green,   'bow-arrow', 'Sport'),
  cat('judo',           'Judo',             C.blue,    'karate', 'Sport'),
  cat('karate',         'Karate',           C.red,     'karate', 'Sport'),
  cat('taekwondo',      'Taekwondo',        C.blue,    'karate', 'Sport'),
  cat('kungfu',         'Kung Fu',          C.red,     'karate', 'Sport'),
  cat('muaythai',       'Muay Thai',        C.orange,  'boxing-glove', 'Sport'),
  cat('bjj',            'Brazilian Jiu-Jitsu',C.blue,  'karate', 'Sport'),
  cat('capoeira',       'Capoeira',         C.yellow,  'karate', 'Sport'),
  cat('kickboxing',     'Kickboxing',       C.red,     'boxing-glove', 'Sport'),
  cat('fencing',        'Fencing',          C.blue,    'fencing', 'Sport'),
  cat('rowing',         'Rowing',           C.sky,     'rowing', 'Sport'),
  cat('kayaking',       'Kayaking',         C.cyan,    'rowing', 'Sport'),
  cat('canoeing',       'Canoeing',         C.teal,    'rowing', 'Sport'),
  cat('scuba',          'Scuba Diving',     C.blue,    'diving-snorkel', 'Sport'),
  cat('snorkeling',     'Snorkelling',      C.sky,     'diving-snorkel', 'Sport'),
  cat('kitesurf',       'Kitesurfing',      C.cyan,    'kite', 'Sport'),
  cat('windsurfing',    'Windsurfing',      C.sky,     'surfing', 'Sport'),
  cat('golf',           'Golf',             C.lime,    'golf', 'Sport'),
  cat('darts',          'Darts',            C.red,     'target', 'Sport'),
  cat('billiards',      'Billiards',        C.green,   'billiards', 'Sport'),
  cat('bowls',          'Lawn Bowls',       C.lime,    'bowling', 'Sport'),
  cat('bowling',        'Bowling',          C.orange,  'bowling', 'Sport'),
  cat('fishing',        'Fishing',          C.teal,    'fish', 'Sport'),
  cat('hunting',        'Hunting',          C.stone,   'deer', 'Sport'),
  cat('paintball',      'Paintball',        C.green,   'target', 'Sport'),
  cat('lasertagsport',  'Laser Tag',        C.cyan,    'pistol', 'Sport'),
  cat('esports_sport',  'Esports',          C.blue,    'gamepad-variant', 'Sport'),
  cat('chess',          'Chess',            C.slate,   'chess-pawn', 'Sport'),
  cat('sportsday',      'Sports Day',       C.green,   'run', 'Sport'),
  cat('charity_run',    'Charity Run',      C.rose,    'run', 'Sport'),
  cat('fun_run',        'Fun Run',          C.orange,  'run', 'Sport'),

  // ── FITNESS & WELLNESS ──────────────────────────────────────────────────────
  cat('fitness',        'Fitness',          C.green,   'arm-flex', 'Fitness & Wellness'),
  cat('yoga',           'Yoga',             C.violet,  'meditation', 'Fitness & Wellness'),
  cat('hotfyoga',       'Hot Yoga',         C.red,     'meditation', 'Fitness & Wellness'),
  cat('hatha',          'Hatha Yoga',       C.teal,    'meditation', 'Fitness & Wellness'),
  cat('vinyasa',        'Vinyasa',          C.sky,     'meditation', 'Fitness & Wellness'),
  cat('kundalini',      'Kundalini',        C.violet,  'meditation', 'Fitness & Wellness'),
  cat('ashtanga',       'Ashtanga',         C.indigo,  'meditation', 'Fitness & Wellness'),
  cat('pilates',        'Pilates',          C.pink,    'gymnastics', 'Fitness & Wellness'),
  cat('taichi',         'Tai Chi',          C.teal,    'leaf', 'Fitness & Wellness'),
  cat('qigong',         'Qi Gong',          C.green,   'leaf', 'Fitness & Wellness'),
  cat('meditation',     'Meditation',       C.violet,  'brain', 'Fitness & Wellness'),
  cat('mindfulness',    'Mindfulness',      C.teal,    'leaf', 'Fitness & Wellness'),
  cat('breathwork',     'Breathwork',       C.sky,     'weather-windy', 'Fitness & Wellness'),
  cat('stretching',     'Stretching',       C.lime,    'gymnastics', 'Fitness & Wellness'),
  cat('hiit',           'HIIT',             C.red,     'fire', 'Fitness & Wellness'),
  cat('zumba',          'Zumba',            C.orange,  'dance-ballroom', 'Fitness & Wellness'),
  cat('aerobics',       'Aerobics',         C.pink,    'gymnastics', 'Fitness & Wellness'),
  cat('spin',           'Spin Class',       C.red,     'bike', 'Fitness & Wellness'),
  cat('barre',          'Barre',            C.rose,    'shoe-ballet', 'Fitness & Wellness'),
  cat('wellness',       'Wellness',         C.teal,    'heart', 'Fitness & Wellness'),
  cat('spa',            'Spa & Relaxation', C.violet,  'spa', 'Fitness & Wellness'),
  cat('nutrition',      'Nutrition',        C.green,   'bowl-mix', 'Fitness & Wellness'),
  cat('mentalhealth',   'Mental Health',    C.violet,  'brain', 'Fitness & Wellness'),
  cat('therapy_group',  'Group Therapy',    C.indigo,  'chat', 'Fitness & Wellness'),
  cat('detox',          'Detox',            C.teal,    'leaf', 'Fitness & Wellness'),
  cat('fasting',        'Fasting',          C.green,   'leaf', 'Fitness & Wellness'),
  cat('naturopathy',    'Naturopathy',      C.lime,    'leaf', 'Fitness & Wellness'),
  cat('reiki',          'Reiki',            C.violet,  'star-four-points', 'Fitness & Wellness'),
  cat('acupuncture',    'Acupuncture',      C.teal,    'leaf', 'Fitness & Wellness'),
  cat('massage',        'Massage',          C.stone,   'spa', 'Fitness & Wellness'),
  cat('cold_therapy',   'Cold Therapy',     C.sky,     'cube-outline', 'Fitness & Wellness'),
  cat('sauna',          'Sauna',            C.orange,  'fire', 'Fitness & Wellness'),

  // ── FOOD & DRINK ───────────────────────────────────────────────────────────
  cat('food',           'Food',             C.orange,  'noodles', 'Food & Drink'),
  cat('restaurant',     'Restaurant Night', C.amber,   'silverware-fork-knife', 'Food & Drink'),
  cat('brunch',         'Brunch',           C.yellow,  'stack-overflow', 'Food & Drink'),
  cat('breakfast',      'Breakfast',        C.amber,   'egg-fried', 'Food & Drink'),
  cat('lunch',          'Lunch',            C.orange,  'bowl-mix', 'Food & Drink'),
  cat('dinner',         'Dinner',           C.amber,   'pasta', 'Food & Drink'),
  cat('supper',         'Supper Club',      C.red,     'candle', 'Food & Drink'),
  cat('braai',          'Braai / BBQ',      C.red,     'fire', 'Food & Drink'),
  cat('picnic',         'Picnic',           C.lime,    'basket', 'Food & Drink'),
  cat('streetfood',     'Street Food',      C.orange,  'taco', 'Food & Drink'),
  cat('foodmarket',     'Food Market',      C.yellow,  'cart', 'Food & Drink'),
  cat('foodfestival',   'Food Festival',    C.orange,  'tent', 'Food & Drink'),
  cat('wine_tasting',   'Wine Tasting',     C.rose,    'glass-wine', 'Food & Drink'),
  cat('beer',           'Beer & Brewing',   C.amber,   'beer', 'Food & Drink'),
  cat('cocktails',      'Cocktail Night',   C.pink,    'glass-cocktail', 'Food & Drink'),
  cat('whiskey',        'Whiskey Tasting',  C.amber,   'glass-tulip', 'Food & Drink'),
  cat('gin',            'Gin Tasting',      C.teal,    'martini', 'Food & Drink'),
  cat('coffee',         'Coffee',           C.stone,   'coffee', 'Food & Drink'),
  cat('coffee_cupping', 'Coffee Cupping',   C.amber,   'coffee', 'Food & Drink'),
  cat('tea',            'Tea Ceremony',     C.green,   'tea', 'Food & Drink'),
  cat('cooking',        'Cooking',          C.orange,  'chef-hat', 'Food & Drink'),
  cat('baking',         'Baking',           C.yellow,  'food-croissant', 'Food & Drink'),
  cat('pastry',         'Pastry',           C.pink,    'food-croissant', 'Food & Drink'),
  cat('vegan',          'Vegan',            C.green,   'sprout', 'Food & Drink'),
  cat('vegetarian',     'Vegetarian',       C.lime,    'bowl-mix', 'Food & Drink'),
  cat('sushi',          'Sushi',            C.red,     'food', 'Food & Drink'),
  cat('halaal',         'Halaal',           C.green,   'weather-night', 'Food & Drink'),
  cat('kosher',         'Kosher',           C.blue,    'star-david', 'Food & Drink'),
  cat('african_food',   'African Cuisine',  C.orange,  'earth', 'Food & Drink'),
  cat('asian_food',     'Asian Cuisine',    C.red,     'noodles', 'Food & Drink'),
  cat('mediterranean',  'Mediterranean',    C.sky,     'fruit-cherries', 'Food & Drink'),
  cat('mexican_food',   'Mexican Cuisine',  C.green,   'taco', 'Food & Drink'),
  cat('indian_food',    'Indian Cuisine',   C.yellow,  'rice', 'Food & Drink'),
  cat('masterchef',     'Cook-Off',         C.orange,  'trophy', 'Food & Drink'),
  cat('cheesetasting',  'Cheese Tasting',   C.yellow,  'cheese', 'Food & Drink'),
  cat('chocolate',      'Chocolate',        C.stone,   'candy', 'Food & Drink'),
  cat('nonalcoholic',   'Mocktails',        C.cyan,    'cup', 'Food & Drink'),
  cat('bubbletea',      'Bubble Tea',       C.pink,    'cup', 'Food & Drink'),

  // ── ARTS & CULTURE ─────────────────────────────────────────────────────────
  cat('art',            'Arts & Theatre',   C.fuchsia, 'palette', 'Arts & Culture'),
  cat('painting',       'Painting',         C.pink,    'brush', 'Arts & Culture'),
  cat('drawing',        'Drawing',          C.violet,  'pencil', 'Arts & Culture'),
  cat('sculpture',      'Sculpture',        C.stone,   'image-filter-hdr', 'Arts & Culture'),
  cat('photography',    'Photography',      C.purple,  'camera', 'Arts & Culture'),
  cat('streetphotog',   'Street Photography',C.slate,  'camera', 'Arts & Culture'),
  cat('portraitphotog', 'Portrait Photography',C.indigo,'camera', 'Arts & Culture'),
  cat('film_photog',    'Film Photography', C.stone,   'filmstrip', 'Arts & Culture'),
  cat('videography',    'Videography',      C.red,     'movie-open', 'Arts & Culture'),
  cat('film',           'Film',             C.red,     'movie-open', 'Arts & Culture'),
  cat('cinema',         'Cinema Night',     C.slate,   'popcorn', 'Arts & Culture'),
  cat('documentary',    'Documentary',      C.stone,   'video', 'Arts & Culture'),
  cat('shortfilm',      'Short Film',       C.red,     'video', 'Arts & Culture'),
  cat('theatre',        'Theatre',          C.violet,  'drama-masks', 'Arts & Culture'),
  cat('musicaltheatre', 'Musical Theatre',  C.pink,    'drama-masks', 'Arts & Culture'),
  cat('improv',         'Improv',           C.yellow,  'drama-masks', 'Arts & Culture'),
  cat('standup',        'Stand-Up Comedy',  C.amber,   'microphone', 'Arts & Culture'),
  cat('comedy',         'Comedy',           C.yellow,  'emoticon-lol', 'Arts & Culture'),
  cat('poetry',         'Poetry',           C.violet,  'note-edit', 'Arts & Culture'),
  cat('spoken_word',    'Spoken Word',      C.indigo,  'microphone-variant', 'Arts & Culture'),
  cat('storytelling',   'Storytelling',     C.amber,   'book-open-variant', 'Arts & Culture'),
  cat('gallery',        'Art Gallery',      C.fuchsia, 'image-frame', 'Arts & Culture'),
  cat('exhibition',     'Exhibition',       C.pink,    'bank', 'Arts & Culture'),
  cat('artwalk',        'Art Walk',         C.rose,    'walk', 'Arts & Culture'),
  cat('mural',          'Mural Art',        C.orange,  'palette', 'Arts & Culture'),
  cat('graffiti',       'Graffiti',         C.lime,    'palette', 'Arts & Culture'),
  cat('digitalart',     'Digital Art',      C.cyan,    'laptop', 'Arts & Culture'),
  cat('nft_art',        'NFT Art',          C.violet,  'image-frame', 'Arts & Culture'),
  cat('animation',      'Animation',        C.blue,    'movie-open', 'Arts & Culture'),
  cat('manga',          'Manga & Comics',   C.orange,  'bookshelf', 'Arts & Culture'),
  cat('anime',          'Anime',            C.purple,  'torii', 'Arts & Culture'),
  cat('cosplay',        'Cosplay',          C.fuchsia, 'drama-masks', 'Arts & Culture'),
  cat('craft',          'Crafts',           C.amber,   'content-cut', 'Arts & Culture'),
  cat('pottery',        'Pottery',          C.stone,   'amphora', 'Arts & Culture'),
  cat('ceramics',       'Ceramics',         C.stone,   'amphora', 'Arts & Culture'),
  cat('glassblowing',   'Glass Blowing',    C.sky,     'chart-bubble', 'Arts & Culture'),
  cat('jewellery',      'Jewellery Making', C.yellow,  'diamond-stone', 'Arts & Culture'),
  cat('candle_making',  'Candle Making',    C.amber,   'candle', 'Arts & Culture'),
  cat('origami',        'Origami',          C.green,   'bird', 'Arts & Culture'),
  cat('knitting',       'Knitting',         C.pink,    'yarn', 'Arts & Culture'),
  cat('crochet',        'Crochet',          C.rose,    'yarn', 'Arts & Culture'),
  cat('sewing',         'Sewing',           C.indigo,  'needle', 'Arts & Culture'),
  cat('embroidery',     'Embroidery',       C.pink,    'needle', 'Arts & Culture'),
  cat('woodwork',       'Woodwork',         C.stone,   'tree', 'Arts & Culture'),
  cat('leatherwork',    'Leatherwork',      C.amber,   'hiking', 'Arts & Culture'),
  cat('printmaking',    'Printmaking',      C.teal,    'printer', 'Arts & Culture'),
  cat('calligraphy',    'Calligraphy',      C.indigo,  'pen', 'Arts & Culture'),
  cat('culture',        'Culture & Heritage',C.orange, 'earth', 'Arts & Culture'),
  cat('heritage',       'Heritage',         C.amber,   'bank', 'Arts & Culture'),
  cat('museum',         'Museum',           C.stone,   'bank', 'Arts & Culture'),
  cat('history',        'History',          C.amber,   'script-text', 'Arts & Culture'),
  cat('archaeology',    'Archaeology',      C.stone,   'amphora', 'Arts & Culture'),

  // ── FASHION & BEAUTY ───────────────────────────────────────────────────────
  cat('fashion',        'Fashion',          C.fuchsia, 'hanger', 'Fashion & Beauty'),
  cat('fashionshow',    'Fashion Show',     C.pink,    'hanger', 'Fashion & Beauty'),
  cat('runway',         'Runway',           C.rose,    'shoe-heel', 'Fashion & Beauty'),
  cat('streetstyle',    'Street Style',     C.slate,   'hat-fedora', 'Fashion & Beauty'),
  cat('vintage',        'Vintage Fashion',  C.amber,   'hat-fedora', 'Fashion & Beauty'),
  cat('thriftstore',    'Thrift & Swap',    C.stone,   'recycle', 'Fashion & Beauty'),
  cat('sustainable_fashion','Sustainable Fashion',C.green,'leaf','Fashion & Beauty'),
  cat('sneakers',       'Sneaker Culture',  C.blue,    'shoe-sneaker', 'Fashion & Beauty'),
  cat('luxury_fashion', 'Luxury Fashion',   C.amber,   'diamond-stone', 'Fashion & Beauty'),
  cat('menswear',       'Menswear',         C.slate,   'coat-rack', 'Fashion & Beauty'),
  cat('womenswear',     "Women's Fashion",  C.pink,    'hanger', 'Fashion & Beauty'),
  cat('kidswear',       "Kids' Fashion",    C.yellow,  'baby-face', 'Fashion & Beauty'),
  cat('jewellery_fashion','Jewellery',      C.yellow,  'ring', 'Fashion & Beauty'),
  cat('beauty',         'Beauty',           C.pink,    'lipstick', 'Fashion & Beauty'),
  cat('makeup',         'Makeup',           C.rose,    'lipstick', 'Fashion & Beauty'),
  cat('skincare',       'Skincare',         C.pink,    'star-four-points', 'Fashion & Beauty'),
  cat('haircare',       'Haircare',         C.purple,  'content-cut', 'Fashion & Beauty'),
  cat('nailart',        'Nail Art',         C.fuchsia, 'hand-back-right', 'Fashion & Beauty'),
  cat('locs',           'Locs & Braids',    C.amber,   'rope', 'Fashion & Beauty'),
  cat('naturalhai',     'Natural Hair',     C.orange,  'content-cut', 'Fashion & Beauty'),
  cat('barbershop',     'Barbershop',       C.slate,   'content-cut', 'Fashion & Beauty'),
  cat('tattoo',         'Tattoo',           C.red,     'palette', 'Fashion & Beauty'),
  cat('piercing',       'Piercing',         C.stone,   'diamond-stone', 'Fashion & Beauty'),
  cat('wellness_beauty','Beauty & Wellness',C.violet,  'flower', 'Fashion & Beauty'),

  // ── TECHNOLOGY ─────────────────────────────────────────────────────────────
  cat('tech',           'Technology',       C.blue,    'laptop', 'Technology'),
  cat('startup',        'Startups',         C.violet,  'rocket-launch', 'Technology'),
  cat('hackathon',      'Hackathon',        C.blue,    'flash', 'Technology'),
  cat('coding',         'Coding',           C.cyan,    'keyboard', 'Technology'),
  cat('webdev',         'Web Dev',          C.blue,    'web', 'Technology'),
  cat('mobiledev',      'Mobile Dev',       C.indigo,  'cellphone', 'Technology'),
  cat('ai',             'AI & Machine Learning',C.cyan, 'robot', 'Technology'),
  cat('blockchain',     'Blockchain',       C.blue,    'link-variant', 'Technology'),
  cat('crypto',         'Crypto',           C.amber,   'bitcoin', 'Technology'),
  cat('web3',           'Web3',             C.violet,  'web', 'Technology'),
  cat('cybersecurity',  'Cybersecurity',    C.red,     'lock', 'Technology'),
  cat('data_science',   'Data Science',     C.sky,     'chart-bar', 'Technology'),
  cat('cloud',          'Cloud Computing',  C.sky,     'cloud', 'Technology'),
  cat('devops',         'DevOps',           C.teal,    'cog', 'Technology'),
  cat('ux_design',      'UX Design',        C.pink,    'palette', 'Technology'),
  cat('product',        'Product',          C.indigo,  'package-variant', 'Technology'),
  cat('robotics',       'Robotics',         C.slate,   'robot', 'Technology'),
  cat('iot',            'IoT',              C.teal,    'power-plug', 'Technology'),
  cat('ar_vr',          'AR / VR',          C.violet,  'safety-goggles', 'Technology'),
  cat('gaming_dev',     'Game Dev',         C.purple,  'gamepad-variant', 'Technology'),
  cat('open_source',    'Open Source',      C.green,   'laptop', 'Technology'),
  cat('techworkshop',   'Tech Workshop',    C.blue,    'tools', 'Technology'),
  cat('techtalks',      'Tech Talks',       C.indigo,  'microphone-variant', 'Technology'),
  cat('pitch',          'Pitch Night',      C.green,   'lightbulb', 'Technology'),
  cat('accelerator',    'Accelerator',      C.orange,  'rocket-launch', 'Technology'),
  cat('fintech',        'FinTech',          C.green,   'credit-card', 'Technology'),
  cat('healthtech',     'HealthTech',       C.teal,    'hospital-building', 'Technology'),
  cat('edtech',         'EdTech',           C.blue,    'bookshelf', 'Technology'),
  cat('cleantech',      'CleanTech',        C.green,   'recycle', 'Technology'),
  cat('spacetech',      'Space & Astronomy',C.indigo,  'rocket-launch', 'Technology'),

  // ── BUSINESS & NETWORKING ───────────────────────────────────────────────────
  cat('business',       'Business',         C.indigo,  'briefcase', 'Business'),
  cat('networking',     'Networking',       C.blue,    'handshake', 'Business'),
  cat('conference',     'Conference',       C.indigo,  'microphone-variant', 'Business'),
  cat('summit',         'Summit',           C.violet,  'image-filter-hdr', 'Business'),
  cat('workshop',       'Workshop',         C.teal,    'tools', 'Business'),
  cat('seminar',        'Seminar',          C.blue,    'clipboard-text', 'Business'),
  cat('masterclass',    'Masterclass',      C.purple,  'school', 'Business'),
  cat('mentoring',      'Mentoring',        C.amber,   'handshake', 'Business'),
  cat('coaching',       'Coaching',         C.green,   'trophy', 'Business'),
  cat('leadership',     'Leadership',       C.indigo,  'crown', 'Business'),
  cat('entrepreneurship','Entrepreneurship',C.orange,  'lightbulb', 'Business'),
  cat('investment',     'Investment',       C.green,   'trending-up', 'Business'),
  cat('realestate',     'Real Estate',      C.stone,   'home', 'Business'),
  cat('finance',        'Finance',          C.green,   'cash', 'Business'),
  cat('marketing',      'Marketing',        C.orange,  'bullhorn', 'Business'),
  cat('branding',       'Branding',         C.red,     'target', 'Business'),
  cat('socialmedia',    'Social Media',     C.pink,    'cellphone', 'Business'),
  cat('pr',             'PR & Media',       C.violet,  'newspaper', 'Business'),
  cat('sales',          'Sales',            C.green,   'cash-multiple', 'Business'),
  cat('ecommerce',      'E-Commerce',       C.blue,    'cart', 'Business'),
  cat('logistics',      'Logistics',        C.slate,   'package-variant', 'Business'),
  cat('legal',          'Legal',            C.indigo,  'scale-balance', 'Business'),
  cat('hr',             'HR & Recruiting',  C.blue,    'account-group', 'Business'),
  cat('management',     'Management',       C.slate,   'chart-bar', 'Business'),
  cat('womeninbiz',     'Women in Business',C.pink,    'account-tie', 'Business'),
  cat('youthbiz',       'Youth Entrepreneurship',C.lime,'star-circle','Business'),
  cat('sme',            'SME',              C.amber,   'store', 'Business'),
  cat('franchise',      'Franchise',        C.orange,  'store', 'Business'),
  cat('agribiz',        'Agri-Business',    C.lime,    'sprout', 'Business'),
  cat('creative_biz',   'Creative Business',C.fuchsia, 'palette', 'Business'),

  // ── EDUCATION ──────────────────────────────────────────────────────────────
  cat('edu',            'Education',        C.sky,     'bookshelf', 'Education'),
  cat('school',         'School',           C.blue,    'school', 'Education'),
  cat('university',     'University',       C.indigo,  'school', 'Education'),
  cat('graduation',     'Graduation',       C.amber,   'school', 'Education'),
  cat('lecture',        'Lecture',          C.blue,    'clipboard-text', 'Education'),
  cat('tutorial',       'Tutorial',         C.teal,    'book-open-variant', 'Education'),
  cat('study_group',    'Study Group',      C.indigo,  'bookshelf', 'Education'),
  cat('debate',         'Debate',           C.red,     'chat', 'Education'),
  cat('quiz',           'Quiz Night',       C.yellow,  'help-circle', 'Education'),
  cat('science',        'Science',          C.sky,     'microscope', 'Education'),
  cat('mathematics',    'Mathematics',      C.blue,    'numeric', 'Education'),
  cat('languages',      'Languages',        C.teal,    'web', 'Education'),
  cat('english',        'English',          C.blue,    'flag', 'Education'),
  cat('afrikaans',      'Afrikaans',        C.orange,  'flag', 'Education'),
  cat('zulu',           'Zulu',             C.green,   'earth', 'Education'),
  cat('xhosa',          'Xhosa',            C.amber,   'earth', 'Education'),
  cat('french',         'French',           C.blue,    'flag', 'Education'),
  cat('arabic',         'Arabic',           C.green,   'flag', 'Education'),
  cat('mandarin',       'Mandarin',         C.red,     'flag', 'Education'),
  cat('spanish',        'Spanish',          C.red,     'flag', 'Education'),
  cat('portuguese',     'Portuguese',       C.green,   'flag', 'Education'),
  cat('swahili',        'Swahili',          C.teal,    'earth', 'Education'),
  cat('sign_language',  'Sign Language',    C.teal,    'hand-peace', 'Education'),
  cat('literacy',       'Literacy',         C.sky,     'book-open-variant', 'Education'),
  cat('tutoring',       'Tutoring',         C.blue,    'ruler', 'Education'),
  cat('eduwomen',       'Girls in Education',C.pink,   'school', 'Education'),
  cat('stem',           'STEM',             C.blue,    'flask', 'Education'),
  cat('coding_kids',    'Coding for Kids',  C.lime,    'space-invaders', 'Education'),

  // ── TRAVEL & ADVENTURE ─────────────────────────────────────────────────────
  cat('travel',         'Travel',           C.sky,     'airplane', 'Travel'),
  cat('adventure',      'Adventure',        C.green,   'leaf', 'Travel'),
  cat('camping',        'Camping',          C.lime,    'tent', 'Travel'),
  cat('glamping',       'Glamping',         C.amber,   'tent', 'Travel'),
  cat('roadtrip',       'Road Trip',        C.orange,  'car', 'Travel'),
  cat('backpacking',    'Backpacking',      C.stone,   'bag-personal', 'Travel'),
  cat('safaari',        'Safari',           C.amber,   'cat', 'Travel'),
  cat('beachtrip',      'Beach Trip',       C.sky,     'beach', 'Travel'),
  cat('island_hopping', 'Island Hopping',   C.cyan,    'island', 'Travel'),
  cat('cruise',         'Cruise',           C.blue,    'ferry', 'Travel'),
  cat('citybreak',      'City Break',       C.indigo,  'city', 'Travel'),
  cat('voluntourism',   'Voluntourism',     C.green,   'earth', 'Travel'),
  cat('cultural_tour',  'Cultural Tour',    C.orange,  'map', 'Travel'),
  cat('food_tour',      'Food Tour',        C.amber,   'noodles', 'Travel'),
  cat('wine_tour',      'Wine Tour',        C.rose,    'glass-wine', 'Travel'),
  cat('motorcycle',     'Motorcycle Ride',  C.red,     'motorbike', 'Travel'),
  cat('trekkings',      'Trekking',         C.green,   'hiking', 'Travel'),
  cat('skydiving',      'Skydiving',        C.sky,     'parachute', 'Travel'),
  cat('bungee',         'Bungee Jumping',   C.red,     'parachute', 'Travel'),
  cat('paragliding',    'Paragliding',      C.sky,     'parachute', 'Travel'),
  cat('whitewater',     'White-Water Rafting',C.sky,   'waves', 'Travel'),
  cat('spelunking',     'Cave Exploration', C.stone,   'circle-outline', 'Travel'),
  cat('stargazing',     'Stargazing',       C.indigo,  'star', 'Travel'),
  cat('birdwatching',   'Birdwatching',     C.lime,    'bird', 'Travel'),
  cat('wildflowers',    'Nature Walk',      C.green,   'flower', 'Travel'),
  cat('sunrise_hike',   'Sunrise Hike',     C.amber,   'image-filter-hdr', 'Travel'),
  cat('night_hike',     'Night Hike',       C.indigo,  'weather-night', 'Travel'),

  // ── GAMING ─────────────────────────────────────────────────────────────────
  cat('gaming',         'Gaming',           C.purple,  'gamepad-variant', 'Gaming'),
  cat('esports',        'Esports',          C.blue,    'gamepad', 'Gaming'),
  cat('lan_party',      'LAN Party',        C.cyan,    'monitor', 'Gaming'),
  cat('gaming_tourney', 'Gaming Tournament',C.red,     'trophy', 'Gaming'),
  cat('retro_gaming',   'Retro Gaming',     C.stone,   'space-invaders', 'Gaming'),
  cat('tabletop',       'Tabletop RPG',     C.amber,   'dice-multiple', 'Gaming'),
  cat('boardgames',     'Board Games',      C.yellow,  'chess-pawn', 'Gaming'),
  cat('cardgames',      'Card Games',       C.red,     'cards-playing', 'Gaming'),
  cat('poker',          'Poker',            C.green,   'cards-playing', 'Gaming'),
  cat('chess_event',    'Chess',            C.slate,   'chess-pawn', 'Gaming'),
  cat('puzzles',        'Puzzles',          C.teal,    'puzzle', 'Gaming'),
  cat('vrgaming',       'VR Gaming',        C.violet,  'safety-goggles', 'Gaming'),
  cat('mobile_gaming',  'Mobile Gaming',    C.blue,    'cellphone', 'Gaming'),
  cat('speedrun',       'Speedrun',         C.lime,    'flash', 'Gaming'),
  cat('minecraft',      'Minecraft',        C.green,   'pickaxe', 'Gaming'),
  cat('cosplay_gaming', 'Gaming Cosplay',   C.fuchsia, 'drama-masks', 'Gaming'),
  cat('streamer',       'Streamer Meet',    C.purple,  'video', 'Gaming'),
  // ── Game genres ──
  cat('fps',            'FPS / Shooter',    C.red,     'pistol', 'Gaming'),
  cat('moba',           'MOBA',             C.blue,    'sword-cross', 'Gaming'),
  cat('battle_royale',  'Battle Royale',    C.orange,  'parachute', 'Gaming'),
  cat('fighting_games', 'Fighting Games',   C.red,     'boxing-glove', 'Gaming'),
  cat('racing_games',   'Racing / Sim',     C.cyan,    'car-sports', 'Gaming'),
  cat('rpg_games',      'RPG',              C.violet,  'sword', 'Gaming'),
  cat('mmo',            'MMO',              C.indigo,  'earth', 'Gaming'),
  cat('sports_games',   'Sports Games',     C.green,   'soccer', 'Gaming'),
  cat('strategy_games', 'Strategy / RTS',   C.amber,   'chess-king', 'Gaming'),
  cat('auto_battler',   'Auto-Battler',     C.teal,    'robot', 'Gaming'),
  cat('survival_games', 'Survival',         C.stone,   'campfire', 'Gaming'),
  cat('sandbox_games',  'Sandbox',          C.lime,    'cube-outline', 'Gaming'),
  cat('platformer',     'Platformer',       C.pink,    'run-fast', 'Gaming'),
  // ── Popular titles ──
  cat('ea_fc',          'EA FC / FIFA',     C.green,   'soccer', 'Gaming'),
  cat('call_of_duty',   'Call of Duty',     C.slate,   'pistol', 'Gaming'),
  cat('fortnite',       'Fortnite',         C.purple,  'parachute', 'Gaming'),
  cat('valorant',       'Valorant',         C.red,     'pistol', 'Gaming'),
  cat('apex',           'Apex Legends',     C.red,     'pistol', 'Gaming'),
  cat('pubg',           'PUBG',             C.amber,   'parachute', 'Gaming'),
  cat('dota2',          'Dota 2',           C.red,     'sword-cross', 'Gaming'),
  cat('lol',            'League of Legends',C.blue,    'sword-cross', 'Gaming'),
  cat('cs2',            'CS2',              C.orange,  'pistol', 'Gaming'),
  cat('overwatch',      'Overwatch',        C.orange,  'pistol', 'Gaming'),
  cat('rocket_league',  'Rocket League',    C.sky,     'car-sports', 'Gaming'),
  cat('tekken',         'Tekken',           C.violet,  'boxing-glove', 'Gaming'),
  cat('street_fighter', 'Street Fighter',   C.red,     'boxing-glove', 'Gaming'),
  cat('mortal_kombat',  'Mortal Kombat',    C.amber,   'boxing-glove', 'Gaming'),
  cat('gta_online',     'GTA Online',       C.green,   'car', 'Gaming'),
  cat('mobile_legends', 'Mobile Legends',   C.blue,    'cellphone', 'Gaming'),
  cat('free_fire',      'Free Fire',        C.orange,  'parachute', 'Gaming'),

  // ── SOCIAL & COMMUNITY ──────────────────────────────────────────────────────
  cat('social',         'Social',           C.pink,    'account-group', 'Social'),
  cat('meetup',         'Meetup',           C.blue,    'handshake', 'Social'),
  cat('party',          'Party',            C.pink,    'party-popper', 'Social'),
  cat('birthday',       'Birthday',         C.yellow,  'cake-variant', 'Social'),
  cat('anniversary',    'Anniversary',      C.rose,    'glass-flute', 'Social'),
  cat('wedding',        'Wedding',          C.pink,    'ring', 'Social'),
  cat('engagement',     'Engagement',       C.rose,    'ring', 'Social'),
  cat('babyshower',     'Baby Shower',      C.sky,     'baby-face-outline', 'Social'),
  cat('graduation_party','Graduation Party',C.amber,   'school', 'Social'),
  cat('housewarming',   'Housewarming',     C.amber,   'home', 'Social'),
  cat('rooftop',        'Rooftop Party',    C.cyan,    'city', 'Social'),
  cat('pool_party',     'Pool Party',       C.sky,     'swim', 'Social'),
  cat('beach_party',    'Beach Party',      C.yellow,  'beach', 'Social'),
  cat('garden_party',   'Garden Party',     C.green,   'flower', 'Social'),
  cat('house_party',    'House Party',      C.orange,  'home', 'Social'),
  cat('vip_event',      'VIP',              C.amber,   'diamond-stone', 'Social'),
  cat('speed_dating',   'Speed Dating',     C.rose,    'heart', 'Social'),
  cat('singles_night',  'Singles Night',    C.pink,    'heart-multiple', 'Social'),
  cat('dating',         'Social & Dating',  C.pink,    'heart', 'Social'),
  cat('lgbtq',          'LGBTQ+',           C.orange,  'looks', 'Social'),
  cat('pride',          'Pride',            C.rainbow, 'looks', 'Social'),
  cat('community',      'Community',        C.green,   'home-group', 'Social'),
  cat('charity',        'Charity',          C.teal,    'heart', 'Social'),
  cat('fundraiser',     'Fundraiser',       C.green,   'cash', 'Social'),
  cat('volunteering',   'Volunteering',     C.lime,    'hands-pray', 'Social'),
  cat('neighbourhood',  'Neighbourhood',    C.green,   'home-group', 'Social'),
  cat('reunion',        'Reunion',          C.amber,   'emoticon-happy', 'Social'),
  cat('memorial',       'Memorial',         C.stone,   'candle', 'Social'),

  // ── KIDS & FAMILY ──────────────────────────────────────────────────────────
  cat('kids',           'Kids & Family',    C.yellow,  'account-group', 'Family'),
  cat('parenting',      'Parenting',        C.amber,   'baby-face-outline', 'Family'),
  cat('babies',         'Babies',           C.sky,     'baby-bottle', 'Family'),
  cat('toddlers',       'Toddlers',         C.yellow,  'teddy-bear', 'Family'),
  cat('playdate',       'Playdate',         C.lime,    'slide', 'Family'),
  cat('kidsfitness',    "Kids' Fitness",    C.green,   'gymnastics', 'Family'),
  cat('storytime',      'Story Time',       C.amber,   'book-open-variant', 'Family'),
  cat('kidscooking',    "Kids' Cooking",    C.orange,  'chef-hat', 'Family'),
  cat('kidsart',        "Kids' Art",        C.pink,    'palette', 'Family'),
  cat('kidssports',     "Kids' Sports",     C.green,   'soccer', 'Family'),
  cat('carnival',       'Carnival',         C.yellow,  'ferris-wheel', 'Family'),
  cat('funfair',        'Fun Fair',         C.orange,  'horse-variant', 'Family'),
  cat('familydayout',   'Family Day Out',   C.lime,    'tree', 'Family'),
  cat('homeschool',     'Homeschool',       C.blue,    'home', 'Family'),
  cat('seniors',        '55+',              C.slate,   'account', 'Family'),
  cat('youth',          'Youth',            C.lime,    'account', 'Family'),

  // ── FAITH & SPIRITUALITY ────────────────────────────────────────────────────
  cat('religion',       'Faith',            C.violet,  'hands-pray', 'Faith'),
  cat('christianity',   'Christianity',     C.blue,    'cross', 'Faith'),
  cat('islam',          'Islam',            C.green,   'star-crescent', 'Faith'),
  cat('judaism',        'Judaism',          C.blue,    'star-david', 'Faith'),
  cat('hinduism',       'Hinduism',         C.orange,  'om', 'Faith'),
  cat('buddhism',       'Buddhism',         C.amber,   'dharmachakra', 'Faith'),
  cat('traditional',    'Traditional',      C.amber,   'leaf', 'Faith'),
  cat('interfaith',     'Interfaith',       C.teal,    'earth', 'Faith'),
  cat('prayer',         'Prayer',           C.indigo,  'hands-pray', 'Faith'),
  cat('bible_study',    'Bible Study',      C.blue,    'book-open-variant', 'Faith'),
  cat('retreat',        'Retreat',          C.violet,  'leaf', 'Faith'),
  cat('crusade',        'Crusade',          C.amber,   'cross', 'Faith'),
  cat('eid',            'Eid',              C.green,   'weather-night', 'Faith'),
  cat('diwali',         'Diwali',           C.yellow,  'lamp', 'Faith'),
  cat('hanukkah',       'Hanukkah',         C.blue,    'candelabra', 'Faith'),
  cat('christmas',      'Christmas',        C.red,     'pine-tree', 'Faith'),
  cat('easter',         'Easter',           C.lime,    'egg', 'Faith'),
  cat('ramadan',        'Ramadan',          C.green,   'weather-night', 'Faith'),
  cat('passover',       'Passover',         C.amber,   'glass-wine', 'Faith'),
  cat('navratri',       'Navratri',         C.pink,    'dance-ballroom', 'Faith'),

  // ── POLITICS & CIVIC ────────────────────────────────────────────────────────
  cat('politics',       'Civic',            C.indigo,  'vote', 'Civic'),
  cat('activist',       'Activism',         C.red,     'hand-back-left', 'Civic'),
  cat('protest',        'Protest',          C.red,     'hand-back-left', 'Civic'),
  cat('townhall',       'Town Hall',        C.indigo,  'bank', 'Civic'),
  cat('election',       'Election',         C.blue,    'vote', 'Civic'),
  cat('panel',          'Panel Discussion', C.violet,  'chat', 'Civic'),
  cat('petition',       'Petition',         C.orange,  'note-edit', 'Civic'),
  cat('human_rights',   'Human Rights',     C.red,     'hand-back-left', 'Civic'),
  cat('gender_rights',  'Gender Rights',    C.pink,    'gender-female', 'Civic'),
  cat('environment',    'Environment',      C.green,   'leaf', 'Civic'),
  cat('climate',        'Climate Action',   C.teal,    'earth', 'Civic'),
  cat('clean_up',       'Clean-Up',         C.lime,    'recycle', 'Civic'),
  cat('tree_planting',  'Tree Planting',    C.green,   'tree', 'Civic'),
  cat('food_drive',     'Food Drive',       C.amber,   'food', 'Civic'),
  cat('indigenous',     'Indigenous',       C.amber,   'sprout', 'Civic'),
  cat('social_justice', 'Social Justice',   C.red,     'scale-balance', 'Civic'),

  // ── HEALTH ─────────────────────────────────────────────────────────────────
  cat('health',         'Health',           C.teal,    'hospital-building', 'Health'),
  cat('medicine',       'Medicine',         C.red,     'pill', 'Health'),
  cat('mental_wellness','Mental Wellness',  C.violet,  'brain', 'Health'),
  cat('therapy',        'Therapy',          C.indigo,  'chat', 'Health'),
  cat('rehab',          'Rehab',            C.teal,    'hospital-building', 'Health'),
  cat('fundraise_health','Health Fundraiser',C.red,    'heart', 'Health'),
  cat('blood_drive',    'Blood Drive',      C.red,     'water', 'Health'),
  cat('hiv_aids',       'HIV Awareness',    C.red,     'heart', 'Health'),
  cat('cancer',         'Cancer Awareness', C.pink,    'ribbon', 'Health'),
  cat('diabetes',       'Diabetes',         C.blue,    'heart', 'Health'),
  cat('womens_health',  "Women's Health",   C.pink,    'human-female', 'Health'),
  cat('mens_health',    "Men's Health",     C.blue,    'human-male', 'Health'),
  cat('reproductive',   'Reproductive Health',C.rose,  'heart', 'Health'),
  cat('addiction',      'Addiction Recovery',C.teal,   'handshake', 'Health'),
  cat('grief',          'Grief Support',    C.stone,   'bird', 'Health'),
  cat('disability',     'Disability',       C.sky,     'wheelchair-accessibility', 'Health'),
  cat('autism',         'Autism Awareness', C.blue,    'puzzle', 'Health'),

  // ── SCIENCE & NATURE ────────────────────────────────────────────────────────
  cat('science_event',  'Science',          C.sky,     'microscope', 'Science'),
  cat('astronomy',      'Astronomy',        C.indigo,  'star-shooting', 'Science'),
  cat('physics',        'Physics',          C.blue,    'atom', 'Science'),
  cat('biology',        'Biology',          C.lime,    'dna', 'Science'),
  cat('chemistry',      'Chemistry',        C.cyan,    'flask', 'Science'),
  cat('geology',        'Geology',          C.stone,   'rock', 'Science'),
  cat('marine',         'Marine Life',      C.sky,     'dolphin', 'Science'),
  cat('wildlife',       'Wildlife',         C.green,   'cat', 'Science'),
  cat('conservation',   'Conservation',     C.green,   'leaf', 'Science'),
  cat('nature',         'Nature',           C.green,   'tree', 'Science'),
  cat('gardening',      'Gardening',        C.lime,    'sprout', 'Science'),
  cat('urban_farming',  'Urban Farming',    C.lime,    'sprout', 'Science'),
  cat('composting',     'Composting',       C.green,   'recycle', 'Science'),
  cat('beekeeping',     'Beekeeping',       C.amber,   'bee', 'Science'),
  cat('animals',        'Animals & Pets',   C.amber,   'paw', 'Science'),
  cat('pets',           'Pets',             C.lime,    'paw', 'Science'),
  cat('dogs',           'Dogs',             C.amber,   'dog', 'Science'),
  cat('cats',           'Cats',             C.yellow,  'cat', 'Science'),
  cat('horses',         'Horses',           C.stone,   'horse', 'Science'),

  // ── VIRTUAL & ONLINE ─────────────────────────────────────────────────────────
  cat('virtual',        'Virtual',          C.indigo,  'laptop', 'Virtual'),
  cat('webinar',        'Webinar',          C.blue,    'monitor', 'Virtual'),
  cat('livestream',     'Livestream',       C.red,     'satellite-variant', 'Virtual'),
  cat('podcast',        'Podcast',          C.purple,  'microphone', 'Virtual'),
  cat('online_course',  'Online Course',    C.teal,    'school', 'Virtual'),
  cat('virtual_concert','Virtual Concert',  C.violet,  'music', 'Virtual'),
  cat('virtual_tour',   'Virtual Tour',     C.sky,     'web', 'Virtual'),
  cat('online_party',   'Online Party',     C.pink,    'party-popper', 'Virtual'),
  cat('discord',        'Discord',          C.indigo,  'chat', 'Virtual'),
  cat('zoom_event',     'Zoom Event',       C.blue,    'video', 'Virtual'),
  cat('clubhouse',      'Clubhouse',        C.orange,  'microphone-variant', 'Virtual'),

  // ── NIGHTLIFE ──────────────────────────────────────────────────────────────
  cat('nightlife',      'Nightlife',        C.violet,  'weather-night', 'Nightlife'),
  cat('bar_night',      'Bar Night',        C.amber,   'martini', 'Nightlife'),
  cat('lounge',         'Lounge',           C.indigo,  'sofa', 'Nightlife'),
  cat('jazz_bar',       'Jazz Bar',         C.amber,   'saxophone', 'Nightlife'),
  cat('comedy_night',   'Comedy Night',     C.yellow,  'emoticon-lol', 'Nightlife'),
  cat('karaoke_bar',    'Karaoke Bar',      C.pink,    'microphone-variant', 'Nightlife'),
  cat('trivia_night',   'Trivia Night',     C.indigo,  'help-circle', 'Nightlife'),
  cat('game_night',     'Game Night',       C.lime,    'dice-multiple', 'Nightlife'),
  cat('movie_night',    'Movie Night',      C.slate,   'movie-open', 'Nightlife'),
  cat('drag',           'Drag Show',        C.fuchsia, 'crown', 'Nightlife'),
  cat('burlesque',      'Burlesque',        C.rose,    'dance-ballroom', 'Nightlife'),

  // ── MARKETS & SHOPPING ─────────────────────────────────────────────────────
  cat('market',         'Market',           C.orange,  'cart', 'Markets'),
  cat('crafts_market',  'Crafts Market',    C.amber,   'content-cut', 'Markets'),
  cat('artmarket',      'Art Market',       C.fuchsia, 'palette', 'Markets'),
  cat('pop_up',         'Pop-Up',           C.pink,    'store', 'Markets'),
  cat('car_boot',       'Car Boot',         C.stone,   'car', 'Markets'),
  cat('flea_market',    'Flea Market',      C.amber,   'shopping', 'Markets'),
  cat('fashion_market', 'Fashion Market',   C.pink,    'hanger', 'Markets'),
  cat('tech_market',    'Tech Market',      C.blue,    'laptop', 'Markets'),
  cat('bookfair',       'Book Fair',        C.stone,   'bookshelf', 'Markets'),
  cat('plant_sale',     'Plant Sale',       C.lime,    'sprout', 'Markets'),
  cat('food_swap',      'Food Swap',        C.green,   'food-apple', 'Markets'),

  // ── CARS & MOTORS ──────────────────────────────────────────────────────────
  cat('cars',           'Cars',             C.slate,   'car', 'Cars & Motors'),
  cat('carshow',        'Car Show',         C.red,     'car', 'Cars & Motors'),
  cat('carwash',        'Car Wash',         C.sky,     'shower', 'Cars & Motors'),
  cat('motorsport',     'Motorsport',       C.red,     'car-sports', 'Cars & Motors'),
  cat('karting',        'Karting',          C.orange,  'car-sports', 'Cars & Motors'),
  cat('f1',             'F1 Watch Party',   C.red,     'flag-checkered', 'Cars & Motors'),
  cat('classic_cars',   'Classic Cars',     C.amber,   'car-estate', 'Cars & Motors'),
  cat('offroad',        'Off-Road',         C.stone,   'car-estate', 'Cars & Motors'),
  cat('motorbikes',     'Motorbikes',       C.slate,   'motorbike', 'Cars & Motors'),
  cat('trucks',         'Trucks',           C.stone,   'truck', 'Cars & Motors'),

  // ── BOOKS & WRITING ────────────────────────────────────────────────────────
  cat('books',          'Books',            C.stone,   'book-open-variant', 'Books & Writing'),
  cat('bookclub',       'Book Club',        C.amber,   'bookshelf', 'Books & Writing'),
  cat('author_talk',    'Author Talk',      C.indigo,  'microphone-variant', 'Books & Writing'),
  cat('creative_writing','Creative Writing',C.violet,  'pencil', 'Books & Writing'),
  cat('journalism',     'Journalism',       C.blue,    'newspaper', 'Books & Writing'),
  cat('publishing',     'Publishing',       C.stone,   'bookshelf', 'Books & Writing'),
  cat('blogging',       'Blogging',         C.teal,    'laptop', 'Books & Writing'),
  cat('zine',           'Zine',             C.pink,    'newspaper', 'Books & Writing'),
  cat('comics',         'Comics',           C.orange,  'star-shooting', 'Books & Writing'),
  cat('screenwriting',  'Screenwriting',    C.red,     'movie-open', 'Books & Writing'),

  // ── HOBBIES & MISC ─────────────────────────────────────────────────────────
  cat('hobbies',        'Hobbies',          C.teal,    'target', 'Hobbies'),
  cat('astronomy_hobby','Astronomy',        C.indigo,  'telescope', 'Hobbies'),
  cat('meteorology',    'Meteorology',      C.sky,     'weather-partly-cloudy', 'Hobbies'),
  cat('geology_hobby',  'Rock Collecting',  C.stone,   'rock', 'Hobbies'),
  cat('magic',          'Magic',            C.violet,  'hat-fedora', 'Hobbies'),
  cat('circus',         'Circus Arts',      C.red,     'tent', 'Hobbies'),
  cat('juggling',       'Juggling',         C.orange,  'juggle', 'Hobbies'),
  cat('kite_flying',    'Kite Flying',      C.sky,     'kite', 'Hobbies'),
  cat('model_making',   'Model Making',     C.stone,   'airplane', 'Hobbies'),
  cat('drone_racing',   'Drone Racing',     C.cyan,    'helicopter', 'Hobbies'),
  cat('rc_cars',        'RC Cars',          C.red,     'car', 'Hobbies'),
  cat('board_sports',   'Board Sports',     C.slate,   'skateboard', 'Hobbies'),
  cat('rollerblading',  'Rollerblading',    C.orange,  'roller-skate', 'Hobbies'),
  cat('scooter',        'Scooter',          C.lime,    'scooter', 'Hobbies'),
  cat('foraging',       'Foraging',         C.lime,    'mushroom', 'Hobbies'),
  cat('mycology',       'Mycology',         C.stone,   'mushroom', 'Hobbies'),
  cat('numismatics',    'Coin Collecting',  C.amber,   'currency-usd-circle', 'Hobbies'),
  cat('stamps',         'Stamp Collecting', C.indigo,  'mailbox', 'Hobbies'),
  cat('antiques',       'Antiques',         C.stone,   'amphora', 'Hobbies'),
  cat('escape_room',    'Escape Room',      C.red,     'lock', 'Hobbies'),
  cat('murder_mystery', 'Murder Mystery',   C.slate,   'magnify', 'Hobbies'),
  cat('wine_beer_hobby','Home Brewing',     C.amber,   'beer', 'Hobbies'),
  cat('perfumery',      'Perfumery',        C.pink,    'flower', 'Hobbies'),
  cat('feng_shui',      'Feng Shui',        C.teal,    'leaf', 'Hobbies'),
  cat('tarot',          'Tarot',            C.violet,  'cards-playing', 'Hobbies'),
  cat('astrology',      'Astrology',        C.indigo,  'star', 'Hobbies'),
  cat('zodiac',         'Zodiac',           C.violet,  'zodiac-aries', 'Hobbies'),
];

// Quick lookup by key
export const ALL_CATEGORIES_MAP = Object.fromEntries(
  ALL_CATEGORIES.map(c => [c.key, c])
);

// Unique group names
export const CATEGORY_GROUPS = [...new Set(ALL_CATEGORIES.map(c => c.group))];

// Every category key in the Gaming group — the single source of truth for
// "is this a game?" so scoreboard gating (EventDetailScreen._isSportCat) and the
// esports sport_type default can't drift from the registry as titles are added.
export const GAMING_KEYS = new Set(
  ALL_CATEGORIES.filter(c => c.group === 'Gaming').map(c => c.key)
);

export const searchCategories = (query) => {
  if (!query.trim()) return ALL_CATEGORIES;
  const q = query.toLowerCase();
  return ALL_CATEGORIES.filter(c =>
    c.label.toLowerCase().includes(q) ||
    c.group.toLowerCase().includes(q) ||
    c.key.toLowerCase().includes(q)
  );
};
