export const CATEGORY_CONFIG = {
  all:         { label: 'All',              color: '#00f2ff', icon: 'globe'  },
  music:       { label: 'Music',            color: '#8b5cf6', icon: 'music' },
  party:       { label: 'Party',            color: '#ec4899', icon: 'activity' },
  food:        { label: 'Food & Markets',   color: '#f97316', icon: 'coffee' },
  sport:       { label: 'Sport & Fitness',  color: '#10b981', icon: 'award' },
  gaming:      { label: 'Gaming & Tech',    color: '#3b82f6', icon: 'tv' },
  art:         { label: 'Arts & Theatre',   color: '#f472b6', icon: 'image' },
  edu:         { label: 'Education',        color: '#0891b2', icon: 'book' },
  biz:         { label: 'Business',         color: '#6366f1', icon: 'briefcase' },
  comedy:      { label: 'Comedy',           color: '#f59e0b', icon: 'smile' },
  wellness:    { label: 'Wellness',         color: '#10b981', icon: 'heart' },
  fashion:     { label: 'Fashion',          color: '#d946ef', icon: 'tag' },
  travel:      { label: 'Travel',           color: '#0ea5e9', icon: 'compass' },
  networking:  { label: 'Networking',       color: '#6366f1', icon: 'users' },
  film:        { label: 'Film',             color: '#dc2626', icon: 'video' },
  photography: { label: 'Photography',      color: '#7c3aed', icon: 'camera' },
  dance:       { label: 'Dance',            color: '#ec4899', icon: 'zap' },
  culture:     { label: 'Culture & Heritage',color: '#f97316', icon: 'map' },
  charity:     { label: 'Charity',          color: '#10b981', icon: 'gift' },
  kids:        { label: 'Kids & Family',    color: '#f59e0b', icon: 'smile' },
  pets:        { label: 'Pets',             color: '#84cc16', icon: 'heart' },
  cars:        { label: 'Cars',             color: '#64748b', icon: 'tool' },
  crafts:      { label: 'Crafts',           color: '#d97706', icon: 'feather' },
  wine:        { label: 'Wine & Spirits',   color: '#be185d', icon: 'shopping-bag' },
  science:     { label: 'Science',          color: '#0891b2', icon: 'settings' },
  religion:    { label: 'Faith',            color: '#a78bfa', icon: 'sun' },
  politics:    { label: 'Civic',            color: '#1d4ed8', icon: 'edit-3' },
  environment: { label: 'Environment',      color: '#16a34a', icon: 'wind' },
  books:       { label: 'Books',            color: '#92400e', icon: 'book-open' },
  startup:     { label: 'Startups',         color: '#7c3aed', icon: 'trending-up' },
  beauty:      { label: 'Beauty',           color: '#f472b6', icon: 'scissors' },
  esports:     { label: 'Esports',          color: '#3b82f6', icon: 'play-circle' },
  virtual:     { label: 'Virtual',          color: '#6366f1', icon: 'monitor' },
  health:      { label: 'Health',           color: '#10b981', icon: 'activity' },
  property:    { label: 'Property',         color: '#78716c', icon: 'home' },
  nightlife:   { label: 'Nightlife',        color: '#7c3aed', icon: 'moon' },
  workshop:    { label: 'Workshop',         color: '#0891b2', icon: 'sliders' },
  conference:  { label: 'Conference',       color: '#4f46e5', icon: 'mic' },
  festival:    { label: 'Festival',         color: '#f59e0b', icon: 'gift' },
  market:      { label: 'Market',           color: '#f97316', icon: 'shopping-cart' },
  hackathon:   { label: 'Hackathon',        color: '#3b82f6', icon: 'cpu' },
  dating:      { label: 'Social & Dating',  color: '#ec4899', icon: 'heart' },
  mental:      { label: 'Mental Health',    color: '#a78bfa', icon: 'shield' },
  parenting:   { label: 'Parenting',        color: '#f59e0b', icon: 'users' },
  seniors:     { label: '55+',             color: '#64748b', icon: 'heart' },
  lgbtq:       { label: 'LGBTQ+',          color: '#f97316', icon: 'flag' },
  indigenous:  { label: 'Indigenous',       color: '#d97706', icon: 'feather' },
  cooking:     { label: 'Cooking',          color: '#f97316', icon: 'coffee' },
  fitness:     { label: 'Fitness',          color: '#10b981', icon: 'activity' },
  yoga:        { label: 'Yoga',             color: '#a78bfa', icon: 'heart' },
  motorsport:  { label: 'Motorsport',       color: '#ef4444', icon: 'fast-forward' },
  anime:       { label: 'Anime',            color: '#8b5cf6', icon: 'tv' },
  poetry:      { label: 'Poetry',           color: '#7c3aed', icon: 'edit' },
  standup:     { label: 'Stand-Up',         color: '#f59e0b', icon: 'mic' },
};

export const CATEGORY_KEYS = Object.keys(CATEGORY_CONFIG);

export const getCategoryColor = (key) =>
  CATEGORY_CONFIG[key]?.color || '#00f2ff';

export const getCategoryLabel = (key) =>
  CATEGORY_CONFIG[key]?.label || key;

export const REACTION_LIST = [
  { key: 'fire',     emoji: '🔥', label: 'Fire'     },
  { key: 'heart',    emoji: '❤️',  label: 'Love'     },
  { key: 'hype',     emoji: '🙌', label: 'Hype'     },
  { key: 'wow',      emoji: '😮', label: 'Wow'      },
  { key: 'laugh',    emoji: '😂', label: 'Laugh'    },
  { key: 'crown',    emoji: '👑', label: 'Crown'    },
  { key: 'gem',      emoji: '💎', label: 'Gem'      },
  { key: 'rocket',   emoji: '🚀', label: 'Rocket'   },
  { key: '100',      emoji: '💯', label: '100'      },
  { key: 'wave',     emoji: '🌊', label: 'Wave'     },
  { key: 'star',     emoji: '⭐', label: 'Star'     },
  { key: 'magic',    emoji: '✨', label: 'Magic'    },
  { key: 'electric', emoji: '⚡', label: 'Electric' },
  { key: 'goat',     emoji: '🐐', label: 'GOAT'     },
  { key: 'clap',     emoji: '👏', label: 'Clap'     },
  { key: 'muscle',   emoji: '💪', label: 'Strength' },
  { key: 'vibe',     emoji: '🎵', label: 'Vibe'     },
  { key: 'legend',   emoji: '🏆', label: 'Legend'   },
  { key: 'drip',     emoji: '💧', label: 'Drip'     },
  { key: 'gang',     emoji: '🤙', label: 'Gang'     },
  { key: 'real',     emoji: '💬', label: 'Real'     },
  { key: 'growth',   emoji: '📈', label: 'Growth'   },
  { key: 'peace',    emoji: '✌️',  label: 'Peace'    },
  { key: 'mind',     emoji: '🤯', label: 'Blown'    },
  { key: 'sad',      emoji: '😢', label: 'Sad'      },
  { key: 'pulse',    emoji: '🫀', label: 'Pulse'    },
  { key: 'drop',     emoji: '🎤', label: 'Drop'     },
  { key: 'heat',     emoji: '🌡️', label: 'Heat'     },
  { key: 'eyes',     emoji: '👀', label: 'Eyes'     },
  { key: 'confetti', emoji: '🎉', label: 'Lit'      },
  { key: 'skull',    emoji: '💀', label: 'Dead'     },
  { key: 'frost',    emoji: '❄️',  label: 'Frost'    },
  { key: 'alien',    emoji: '👽', label: 'Alien'    },
  { key: 'unicorn',  emoji: '🦄', label: 'Unicorn'  },
  { key: 'comet',    emoji: '☄️',  label: 'Comet'    },
  { key: 'cosmic',   emoji: '🌌', label: 'Cosmic'   },
  { key: 'mystic',   emoji: '🔮', label: 'Mystic'   },
  { key: 'erupt',    emoji: '🌋', label: 'Erupt'    },
  { key: 'storm',    emoji: '🌪️',  label: 'Storm'    },
  { key: 'rainbow',  emoji: '🌈', label: 'Rainbow'  },
  { key: 'boom',     emoji: '🎆', label: 'Boom'     },
  { key: 'gold',     emoji: '🥇', label: 'Gold'     },
  { key: 'respect',  emoji: '🤝', label: 'Respect'  },
  { key: 'genius',   emoji: '🧠', label: 'Genius'   },
  { key: 'bag',      emoji: '💰', label: 'Bag'      },
  { key: 'rock',     emoji: '🎸', label: 'Rock'     },
  { key: 'angel',    emoji: '😇', label: 'Angel'    },
  { key: 'devilish', emoji: '😈', label: 'Devilish' },
  { key: 'spooky',   emoji: '👻', label: 'Spooky'   },
  { key: 'dragon',   emoji: '🐉', label: 'Dragon'   },
  { key: 'love_eyes', emoji: '😍', label: 'Adore' },
  { key: 'kiss',      emoji: '😘', label: 'Kiss' },
  { key: 'cool',      emoji: '😎', label: 'Cool' },
  { key: 'party',     emoji: '🥳', label: 'Party' },
  { key: 'sparkleheart', emoji: '💖', label: 'Sparkle' },
  { key: 'starstruck', emoji: '🤩', label: 'Starstruck' },
  { key: 'pray',      emoji: '🙏', label: 'Bless' },
  { key: 'perfect',   emoji: '👌', label: 'Perfect' },
  { key: 'up',        emoji: '👍', label: 'Up' },
  { key: 'salute',    emoji: '🫡', label: 'Salute' },
  { key: 'wink',      emoji: '😉', label: 'Wink' },
  { key: 'cheeky',    emoji: '😜', label: 'Cheeky' },
  { key: 'hush',      emoji: '🤫', label: 'Secret' },
  { key: 'hmm',       emoji: '🤔', label: 'Hmm' },
  { key: 'smirk',     emoji: '😏', label: 'Smirk' },
  { key: 'melt',      emoji: '🫠', label: 'Melt' },
  { key: 'butterfly', emoji: '🦋', label: 'Flutter' },
  { key: 'lion',      emoji: '🦁', label: 'King' },
  { key: 'wolf',      emoji: '🐺', label: 'Wolf' },
  { key: 'bloom',     emoji: '🌸', label: 'Bloom' },
  { key: 'moon',      emoji: '🌙', label: 'Moon' },
  { key: 'sun',       emoji: '☀️', label: 'Sunny' },
  { key: 'cash',      emoji: '💸', label: 'Cash' },
  { key: 'bullseye',  emoji: '🎯', label: 'Bullseye' },
];
