export const CATEGORY_CONFIG = {
  all:         { label: 'All',              color: '#00f2ff', icon: '✦'  },
  music:       { label: 'Music',            color: '#8b5cf6', icon: '🎵' },
  party:       { label: 'Party',            color: '#ec4899', icon: '🎉' },
  food:        { label: 'Food & Markets',   color: '#f97316', icon: '🍜' },
  sport:       { label: 'Sport & Fitness',  color: '#10b981', icon: '🏀' },
  gaming:      { label: 'Gaming & Tech',    color: '#3b82f6', icon: '🎮' },
  art:         { label: 'Arts & Theatre',   color: '#f472b6', icon: '🎨' },
  edu:         { label: 'Education',        color: '#0891b2', icon: '📚' },
  biz:         { label: 'Business',         color: '#6366f1', icon: '💼' },
  comedy:      { label: 'Comedy',           color: '#f59e0b', icon: '😂' },
  wellness:    { label: 'Wellness',         color: '#10b981', icon: '🧘' },
  fashion:     { label: 'Fashion',          color: '#d946ef', icon: '👗' },
  travel:      { label: 'Travel',           color: '#0ea5e9', icon: '✈️' },
  networking:  { label: 'Networking',       color: '#6366f1', icon: '🤝' },
  film:        { label: 'Film',             color: '#dc2626', icon: '🎬' },
  photography: { label: 'Photography',      color: '#7c3aed', icon: '📸' },
  dance:       { label: 'Dance',            color: '#ec4899', icon: '💃' },
  culture:     { label: 'Culture & Heritage',color: '#f97316', icon: '🌍' },
  charity:     { label: 'Charity',          color: '#10b981', icon: '❤️' },
  kids:        { label: 'Kids & Family',    color: '#f59e0b', icon: '👨‍👩‍👧' },
  pets:        { label: 'Pets',             color: '#84cc16', icon: '🐾' },
  cars:        { label: 'Cars',             color: '#64748b', icon: '🚗' },
  crafts:      { label: 'Crafts',           color: '#d97706', icon: '🎭' },
  wine:        { label: 'Wine & Spirits',   color: '#be185d', icon: '🍷' },
  science:     { label: 'Science',          color: '#0891b2', icon: '🔬' },
  religion:    { label: 'Faith',            color: '#a78bfa', icon: '🙏' },
  politics:    { label: 'Civic',            color: '#1d4ed8', icon: '🗳️' },
  environment: { label: 'Environment',      color: '#16a34a', icon: '🌿' },
  books:       { label: 'Books',            color: '#92400e', icon: '📖' },
  startup:     { label: 'Startups',         color: '#7c3aed', icon: '🚀' },
  beauty:      { label: 'Beauty',           color: '#f472b6', icon: '💄' },
  esports:     { label: 'Esports',          color: '#3b82f6', icon: '🕹️' },
  virtual:     { label: 'Virtual',          color: '#6366f1', icon: '💻' },
  health:      { label: 'Health',           color: '#10b981', icon: '🏥' },
  property:    { label: 'Property',         color: '#78716c', icon: '🏠' },
  nightlife:   { label: 'Nightlife',        color: '#7c3aed', icon: '🌙' },
  workshop:    { label: 'Workshop',         color: '#0891b2', icon: '🛠️' },
  conference:  { label: 'Conference',       color: '#4f46e5', icon: '🎤' },
  festival:    { label: 'Festival',         color: '#f59e0b', icon: '🎪' },
  market:      { label: 'Market',           color: '#f97316', icon: '🛒' },
  hackathon:   { label: 'Hackathon',        color: '#3b82f6', icon: '⚡' },
  dating:      { label: 'Social & Dating',  color: '#ec4899', icon: '💘' },
  mental:      { label: 'Mental Health',    color: '#a78bfa', icon: '🧠' },
  parenting:   { label: 'Parenting',        color: '#f59e0b', icon: '👶' },
  seniors:     { label: '55+',             color: '#64748b', icon: '👴' },
  lgbtq:       { label: 'LGBTQ+',          color: '#f97316', icon: '🏳️‍🌈' },
  indigenous:  { label: 'Indigenous',       color: '#d97706', icon: '🌾' },
  cooking:     { label: 'Cooking',          color: '#f97316', icon: '👨‍🍳' },
  fitness:     { label: 'Fitness',          color: '#10b981', icon: '💪' },
  yoga:        { label: 'Yoga',             color: '#a78bfa', icon: '🧘‍♀️' },
  motorsport:  { label: 'Motorsport',       color: '#ef4444', icon: '🏎️' },
  anime:       { label: 'Anime',            color: '#8b5cf6', icon: '⛩️' },
  poetry:      { label: 'Poetry',           color: '#7c3aed', icon: '📝' },
  standup:     { label: 'Stand-Up',         color: '#f59e0b', icon: '🎙️' },
};

export const CATEGORY_KEYS = Object.keys(CATEGORY_CONFIG);

export const getCategoryColor = (key) =>
  CATEGORY_CONFIG[key]?.color || '#00f2ff';

export const getCategoryLabel = (key) =>
  CATEGORY_CONFIG[key]?.label || key;

export const REACTION_LIST = [
  { key: 'fire',     emoji: '🔥', label: 'Fire'     },
  { key: 'heart',    emoji: '❤️',  label: 'Love'     },
  { key: 'hype',     emoji: '🙌', label: 'Hype'     },
  { key: 'wow',      emoji: '😮', label: 'Wow'      },
  { key: 'laugh',    emoji: '😂', label: 'Laugh'    },
  { key: 'crown',    emoji: '👑', label: 'Crown'    },
  { key: 'gem',      emoji: '💎', label: 'Gem'      },
  { key: 'rocket',   emoji: '🚀', label: 'Rocket'   },
  { key: '100',      emoji: '💯', label: '100'      },
  { key: 'wave',     emoji: '🌊', label: 'Wave'     },
  { key: 'star',     emoji: '⭐', label: 'Star'     },
  { key: 'magic',    emoji: '✨', label: 'Magic'    },
  { key: 'electric', emoji: '⚡', label: 'Electric' },
  { key: 'goat',     emoji: '🐐', label: 'GOAT'     },
  { key: 'clap',     emoji: '👏', label: 'Clap'     },
  { key: 'muscle',   emoji: '💪', label: 'Strength' },
  { key: 'vibe',     emoji: '🎵', label: 'Vibe'     },
  { key: 'legend',   emoji: '🏆', label: 'Legend'   },
  { key: 'drip',     emoji: '💧', label: 'Drip'     },
  { key: 'gang',     emoji: '🤙', label: 'Gang'     },
  { key: 'real',     emoji: '💬', label: 'Real'     },
  { key: 'growth',   emoji: '📈', label: 'Growth'   },
  { key: 'peace',    emoji: '✌️',  label: 'Peace'    },
  { key: 'mind',     emoji: '🤯', label: 'Blown'    },
  { key: 'sad',      emoji: '😢', label: 'Sad'      },
  { key: 'pulse',    emoji: '🫀', label: 'Pulse'    },
  { key: 'drop',     emoji: '🎤', label: 'Drop'     },
  { key: 'heat',     emoji: '🌡️', label: 'Heat'     },
  { key: 'eyes',     emoji: '👀', label: 'Eyes'     },
  { key: 'confetti', emoji: '🎉', label: 'Lit'      },
  { key: 'skull',    emoji: '💀', label: 'Dead'     },
  { key: 'frost',    emoji: '❄️',  label: 'Frost'    },
  { key: 'alien',    emoji: '👽', label: 'Alien'    },
  { key: 'unicorn',  emoji: '🦄', label: 'Unicorn'  },
  { key: 'comet',    emoji: '☄️',  label: 'Comet'    },
  { key: 'cosmic',   emoji: '🌌', label: 'Cosmic'   },
  { key: 'mystic',   emoji: '🔮', label: 'Mystic'   },
  { key: 'erupt',    emoji: '🌋', label: 'Erupt'    },
  { key: 'storm',    emoji: '🌪️',  label: 'Storm'    },
  { key: 'rainbow',  emoji: '🌈', label: 'Rainbow'  },
  { key: 'boom',     emoji: '🎆', label: 'Boom'     },
  { key: 'gold',     emoji: '🥇', label: 'Gold'     },
  { key: 'respect',  emoji: '🤝', label: 'Respect'  },
  { key: 'genius',   emoji: '🧠', label: 'Genius'   },
  { key: 'bag',      emoji: '💰', label: 'Bag'      },
  { key: 'rock',     emoji: '🎸', label: 'Rock'     },
  { key: 'angel',    emoji: '😇', label: 'Angel'    },
  { key: 'devilish', emoji: '😈', label: 'Devilish' },
  { key: 'spooky',   emoji: '👻', label: 'Spooky'   },
  { key: 'dragon',   emoji: '🐉', label: 'Dragon'   },
];
