export const CATEGORY_CONFIG = {
  all:         { label: 'All',              color: '#00f2ff', icon: 'globe'  },
  music:       { label: 'Music',            color: '#8b5cf6', icon: 'music' },
  party:       { label: 'Party',            color: '#ec4899', icon: 'activity' },
  food:        { label: 'Food & Markets',   color: '#f97316', icon: 'coffee' },
  sport:       { label: 'Sport & Fitness',  color: '#10b981', icon: 'award' },
  gaming:      { label: 'Gaming & Tech',    color: '#3b82f6', icon: 'tv' },
  art:         { label: 'Arts & Theatre',   color: '#f472b6', icon: 'image' },
  edu:         { label: 'Education',        color: '#0891b2', icon: 'book' },
  biz:         { label: 'Business',         color: '#6366f1', icon: 'briefcase' },
  comedy:      { label: 'Comedy',           color: '#f59e0b', icon: 'smile' },
  wellness:    { label: 'Wellness',         color: '#10b981', icon: 'heart' },
  fashion:     { label: 'Fashion',          color: '#d946ef', icon: 'tag' },
  travel:      { label: 'Travel',           color: '#0ea5e9', icon: 'compass' },
  networking:  { label: 'Networking',       color: '#6366f1', icon: 'users' },
  film:        { label: 'Film',             color: '#dc2626', icon: 'video' },
  photography: { label: 'Photography',      color: '#7c3aed', icon: 'camera' },
  dance:       { label: 'Dance',            color: '#ec4899', icon: 'zap' },
  culture:     { label: 'Culture & Heritage',color: '#f97316', icon: 'map' },
  charity:     { label: 'Charity',          color: '#10b981', icon: 'gift' },
  kids:        { label: 'Kids & Family',    color: '#f59e0b', icon: 'smile' },
  pets:        { label: 'Pets',             color: '#84cc16', icon: 'heart' },
  cars:        { label: 'Cars',             color: '#64748b', icon: 'tool' },
  crafts:      { label: 'Crafts',           color: '#d97706', icon: 'feather' },
  wine:        { label: 'Wine & Spirits',   color: '#be185d', icon: 'shopping-bag' },
  science:     { label: 'Science',          color: '#0891b2', icon: 'settings' },
  religion:    { label: 'Faith',            color: '#a78bfa', icon: 'sun' },
  politics:    { label: 'Civic',            color: '#1d4ed8', icon: 'edit-3' },
  environment: { label: 'Environment',      color: '#16a34a', icon: 'wind' },
  books:       { label: 'Books',            color: '#92400e', icon: 'book-open' },
  startup:     { label: 'Startups',         color: '#7c3aed', icon: 'trending-up' },
  beauty:      { label: 'Beauty',           color: '#f472b6', icon: 'scissors' },
  esports:     { label: 'Esports',          color: '#3b82f6', icon: 'play-circle' },
  virtual:     { label: 'Virtual',          color: '#6366f1', icon: 'monitor' },
  health:      { label: 'Health',           color: '#10b981', icon: 'activity' },
  property:    { label: 'Property',         color: '#78716c', icon: 'home' },
  nightlife:   { label: 'Nightlife',        color: '#7c3aed', icon: 'moon' },
  workshop:    { label: 'Workshop',         color: '#0891b2', icon: 'sliders' },
  conference:  { label: 'Conference',       color: '#4f46e5', icon: 'mic' },
  festival:    { label: 'Festival',         color: '#f59e0b', icon: 'gift' },
  market:      { label: 'Market',           color: '#f97316', icon: 'shopping-cart' },
  hackathon:   { label: 'Hackathon',        color: '#3b82f6', icon: 'cpu' },
  dating:      { label: 'Social & Dating',  color: '#ec4899', icon: 'heart' },
  mental:      { label: 'Mental Health',    color: '#a78bfa', icon: 'shield' },
  parenting:   { label: 'Parenting',        color: '#f59e0b', icon: 'users' },
  seniors:     { label: '55+',             color: '#64748b', icon: 'heart' },
  lgbtq:       { label: 'LGBTQ+',          color: '#f97316', icon: 'flag' },
  indigenous:  { label: 'Indigenous',       color: '#d97706', icon: 'feather' },
  cooking:     { label: 'Cooking',          color: '#f97316', icon: 'coffee' },
  fitness:     { label: 'Fitness',          color: '#10b981', icon: 'activity' },
  yoga:        { label: 'Yoga',             color: '#a78bfa', icon: 'heart' },
  motorsport:  { label: 'Motorsport',       color: '#ef4444', icon: 'fast-forward' },
  anime:       { label: 'Anime',            color: '#8b5cf6', icon: 'tv' },
  poetry:      { label: 'Poetry',           color: '#7c3aed', icon: 'edit' },
  standup:     { label: 'Stand-Up',         color: '#f59e0b', icon: 'mic' },
};

export const CATEGORY_KEYS = Object.keys(CATEGORY_CONFIG);

export const getCategoryColor = (key) =>
  CATEGORY_CONFIG[key]?.color || '#00f2ff';

export const getCategoryLabel = (key) =>
  CATEGORY_CONFIG[key]?.label || key;

export const REACTION_LIST = [
  { key: 'fire', emoji: '🔥', icon: 'fire', label: 'Fire' },
  { key: 'heart', emoji: '❤️', icon: 'heart', label: 'Love' },
  { key: 'hype', emoji: '🙌', icon: 'hands-pray', label: 'Hype' },
  { key: 'wow', emoji: '😮', icon: 'emoticon-outline', label: 'Wow' },
  { key: 'laugh', emoji: '😂', icon: 'emoticon-lol', label: 'Laugh' },
  { key: 'crown', emoji: '👑', icon: 'crown', label: 'Crown' },
  { key: 'gem', emoji: '💎', icon: 'diamond-stone', label: 'Gem' },
  { key: 'rocket', emoji: '🚀', icon: 'rocket-launch', label: 'Rocket' },
  { key: '100', emoji: '💯', icon: 'numeric', label: '100' },
  { key: 'wave', emoji: '🌊', icon: 'waves', label: 'Wave' },
  { key: 'star', emoji: '⭐', icon: 'star', label: 'Star' },
  { key: 'magic', emoji: '✨', icon: 'star-four-points', label: 'Magic' },
  { key: 'electric', emoji: '⚡', icon: 'flash', label: 'Electric' },
  { key: 'goat', emoji: '🐐', icon: 'trophy-variant', label: 'GOAT' },
  { key: 'clap', emoji: '👏', icon: 'hand-back-right', label: 'Clap' },
  { key: 'muscle', emoji: '💪', icon: 'arm-flex', label: 'Strength' },
  { key: 'vibe', emoji: '🎵', icon: 'music', label: 'Vibe' },
  { key: 'legend', emoji: '🏆', icon: 'trophy', label: 'Legend' },
  { key: 'drip', emoji: '💧', icon: 'water', label: 'Drip' },
  { key: 'gang', emoji: '🤙', icon: 'hand-wave', label: 'Gang' },
  { key: 'real', emoji: '💬', icon: 'comment', label: 'Real' },
  { key: 'growth', emoji: '📈', icon: 'trending-up', label: 'Growth' },
  { key: 'peace', emoji: '✌️', icon: 'hand-peace', label: 'Peace' },
  { key: 'mind', emoji: '🤯', icon: 'brain', label: 'Blown' },
  { key: 'sad', emoji: '😢', icon: 'emoticon-sad', label: 'Sad' },
  { key: 'pulse', emoji: '🫀', icon: 'heart-pulse', label: 'Pulse' },
  { key: 'drop', emoji: '🎤', icon: 'microphone', label: 'Drop' },
  { key: 'heat', emoji: '🌡️', icon: 'thermometer', label: 'Heat' },
  { key: 'eyes', emoji: '👀', icon: 'eye', label: 'Eyes' },
  { key: 'confetti', emoji: '🎉', icon: 'party-popper', label: 'Lit' },
  { key: 'skull', emoji: '💀', icon: 'skull', label: 'Dead' },
  { key: 'frost', emoji: '❄️', icon: 'snowflake', label: 'Frost' },
  { key: 'alien', emoji: '👽', icon: 'alien', label: 'Alien' },
  { key: 'unicorn', emoji: '🦄', icon: 'unicorn-variant', label: 'Unicorn' },
  { key: 'comet', emoji: '☄️', icon: 'star-shooting', label: 'Comet' },
  { key: 'cosmic', emoji: '🌌', icon: 'shimmer', label: 'Cosmic' },
  { key: 'mystic', emoji: '🔮', icon: 'crystal-ball', label: 'Mystic' },
  { key: 'erupt', emoji: '🌋', icon: 'volcano', label: 'Erupt' },
  { key: 'storm', emoji: '🌪️', icon: 'weather-tornado', label: 'Storm' },
  { key: 'rainbow', emoji: '🌈', icon: 'looks', label: 'Rainbow' },
  { key: 'boom', emoji: '🎆', icon: 'firework', label: 'Boom' },
  { key: 'gold', emoji: '🥇', icon: 'medal', label: 'Gold' },
  { key: 'respect', emoji: '🤝', icon: 'handshake', label: 'Respect' },
  { key: 'genius', emoji: '🧠', icon: 'brain', label: 'Genius' },
  { key: 'bag', emoji: '💰', icon: 'cash', label: 'Bag' },
  { key: 'rock', emoji: '🎸', icon: 'guitar-electric', label: 'Rock' },
  { key: 'angel', emoji: '😇', icon: 'emoticon-happy', label: 'Angel' },
  { key: 'devilish', emoji: '😈', icon: 'emoticon-devil', label: 'Devilish' },
  { key: 'spooky', emoji: '👻', icon: 'ghost', label: 'Spooky' },
  { key: 'dragon', emoji: '🐉', icon: 'shield-star', label: 'Dragon' },
  { key: 'love_eyes', emoji: '😍', icon: 'heart-circle', label: 'Adore' },
  { key: 'kiss', emoji: '😘', icon: 'emoticon-kiss', label: 'Kiss' },
  { key: 'cool', emoji: '😎', icon: 'emoticon-cool', label: 'Cool' },
  { key: 'party', emoji: '🥳', icon: 'party-popper', label: 'Party' },
  { key: 'sparkleheart', emoji: '💖', icon: 'heart-multiple', label: 'Sparkle' },
  { key: 'starstruck', emoji: '🤩', icon: 'emoticon-excited', label: 'Starstruck' },
  { key: 'pray', emoji: '🙏', icon: 'hands-pray', label: 'Bless' },
  { key: 'perfect', emoji: '👌', icon: 'hand-okay', label: 'Perfect' },
  { key: 'up', emoji: '👍', icon: 'thumb-up', label: 'Up' },
  { key: 'salute', emoji: '🫡', icon: 'emoticon-happy', label: 'Salute' },
  { key: 'wink', emoji: '😉', icon: 'emoticon-wink', label: 'Wink' },
  { key: 'cheeky', emoji: '😜', icon: 'emoticon-tongue', label: 'Cheeky' },
  { key: 'hush', emoji: '🤫', icon: 'emoticon-neutral', label: 'Secret' },
  { key: 'hmm', emoji: '🤔', icon: 'emoticon-neutral', label: 'Hmm' },
  { key: 'smirk', emoji: '😏', icon: 'emoticon-cool', label: 'Smirk' },
  { key: 'melt', emoji: '🫠', icon: 'emoticon', label: 'Melt' },
  { key: 'butterfly', emoji: '🦋', icon: 'butterfly', label: 'Flutter' },
  { key: 'lion', emoji: '🦁', icon: 'cat', label: 'King' },
  { key: 'wolf', emoji: '🐺', icon: 'dog', label: 'Wolf' },
  { key: 'bloom', emoji: '🌸', icon: 'flower', label: 'Bloom' },
  { key: 'moon', emoji: '🌙', icon: 'weather-night', label: 'Moon' },
  { key: 'sun', emoji: '☀️', icon: 'white-balance-sunny', label: 'Sunny' },
  { key: 'cash', emoji: '💸', icon: 'cash-multiple', label: 'Cash' },
  { key: 'bullseye', emoji: '🎯', icon: 'target', label: 'Bullseye' },
];
