/**
 * extract-schema.js — Reverse-engineers the expected Supabase schema from the
 * codebase. Parses every .from('table') chain and every .rpc('fn', {...}) call
 * to infer which tables, columns, and RPC functions the app depends on.
 *
 * Output: a SCHEMA.md contract you can diff against your live Supabase project
 * to catch drift (a missing column or RPC = a silently broken feature).
 *
 * Run: node scripts/extract-schema.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC_DIRS = ['src/screens', 'src/components', 'src/services', 'src/hooks', 'src/context'];

const files = [];
SRC_DIRS.forEach((dir) => {
  const full = path.join(ROOT, dir);
  if (!fs.existsSync(full)) return;
  fs.readdirSync(full)
    .filter((f) => f.endsWith('.js'))
    .forEach((f) => files.push(path.join(full, f)));
});

const tables = {}; // name -> { cols:Set, ops:Set, files:Set }
const rpcs = {}; // name -> { params:Set, files:Set }

const ensureTable = (t) => {
  if (!tables[t]) tables[t] = { cols: new Set(), ops: new Set(), files: new Set() };
  return tables[t];
};
const ensureRpc = (r) => {
  if (!rpcs[r]) rpcs[r] = { params: new Set(), files: new Set() };
  return rpcs[r];
};

const COL = /^[a-z][a-z0-9_]*$/;

for (const fp of files) {
  const code = fs.readFileSync(fp, 'utf8');
  const rel = path.relative(ROOT, fp).replace(/\\/g, '/');

  // ── Tables: split on .from('x') and inspect the following chain segment ──
  const fromRe = /\.from\(\s*['"`]([a-z_][a-z0-9_]*)['"`]\s*\)/g;
  let fm;
  const froms = [];
  while ((fm = fromRe.exec(code)) !== null) froms.push({ name: fm[1], start: fm.index + fm[0].length });
  froms.forEach((f, i) => {
    const end = i + 1 < froms.length ? froms[i + 1].start : Math.min(f.start + 500, code.length);
    const seg = code.slice(f.start, end);
    const t = ensureTable(f.name);
    t.files.add(rel);

    ['select', 'insert', 'update', 'upsert', 'delete'].forEach((op) => {
      if (new RegExp('\\.' + op + '\\(').test(seg)) t.ops.add(op);
    });

    // select('a, b, nested:fk(...)')
    const sel = seg.match(/\.select\(\s*[`'"]([^`'"]*)[`'"]/);
    if (sel) {
      sel[1].split(',').forEach((raw) => {
        const name = raw.trim().split(':')[0].split('(')[0].trim();
        if (COL.test(name)) t.cols.add(name);
      });
    }

    // filters: .eq('col', ...) etc.
    const filt = seg.matchAll(/\.(eq|neq|gt|gte|lt|lte|is|in|like|ilike|contains|order)\(\s*[`'"]([a-z_][a-z0-9_]*)[`'"]/g);
    for (const m of filt) t.cols.add(m[2]);

    // insert/update/upsert object literal keys
    const obj = seg.match(/\.(insert|update|upsert)\(\s*\[?\s*\{([^}]*)\}/);
    if (obj) {
      const keys = obj[2].matchAll(/([a-z_][a-z0-9_]*)\s*:/g);
      for (const k of keys) if (COL.test(k[1])) t.cols.add(k[1]);
    }
  });

  // ── RPCs: .rpc('fn', { p_x: ..., p_y: ... }) ──
  const rpcRe = /\.rpc\(\s*['"`]([a-z_][a-z0-9_]*)['"`]\s*(?:,\s*\{([^}]*)\})?/g;
  let rm;
  while ((rm = rpcRe.exec(code)) !== null) {
    const r = ensureRpc(rm[1]);
    r.files.add(rel);
    if (rm[2]) {
      const keys = rm[2].matchAll(/([a-z_][a-z0-9_]*)\s*:/g);
      for (const k of keys) r.params.add(k[1]);
    }
  }
}

// ── Emit SCHEMA.md ──
const lines = [];
lines.push('# The Gruvs — Inferred Database Schema Contract');
lines.push('');
lines.push('> Auto-generated by `scripts/extract-schema.js` from every Supabase query in the app.');
lines.push('> This is what the **code expects**. Diff it against your live Supabase project to catch drift —');
lines.push('> a table/column/RPC here that is missing in the database = a silently broken feature.');
lines.push('');
lines.push(`**${Object.keys(tables).length} tables** · **${Object.keys(rpcs).length} RPC functions** referenced.`);
lines.push('');
lines.push('## Tables');
lines.push('');
Object.keys(tables).sort().forEach((name) => {
  const t = tables[name];
  const cols = [...t.cols].sort();
  lines.push(`### \`${name}\``);
  lines.push(`Operations: ${[...t.ops].sort().join(', ') || '—'}`);
  lines.push('');
  if (cols.length) {
    lines.push(`Columns referenced (${cols.length}): ${cols.map((c) => `\`${c}\``).join(', ')}`);
  } else {
    lines.push('Columns referenced: _(none captured — likely select(\'*\') or count-only)_');
  }
  lines.push('');
});
lines.push('## RPC Functions');
lines.push('');
Object.keys(rpcs).sort().forEach((name) => {
  const r = rpcs[name];
  const params = [...r.params].sort();
  lines.push(`- \`${name}(${params.join(', ')})\``);
});
lines.push('');

fs.writeFileSync(path.join(ROOT, 'SCHEMA.md'), lines.join('\n'));
console.log(`SCHEMA.md written: ${Object.keys(tables).length} tables, ${Object.keys(rpcs).length} RPCs`);
