// ─── Themes ───────────────────────────────────────────────────────────────────
export const THEMES = {
    day:        { bg: '#f9fafb', card: '#fff', text: '#111', sub: '#666', border: '#e2e8f0', nav: '#fff', acc: '#ff4da6', inp: '#e8ecf0', it: '#111', glow: 'rgba(255,77,166,0.3)' },
    male:       { bg: '#f9fafb', card: '#fff', text: '#111', sub: '#666', border: '#e2e8f0', nav: '#fff', acc: '#3b82f6', inp: '#e8ecf0', it: '#111', glow: 'rgba(59,130,246,0.3)' },
    female:     { bg: '#f9fafb', card: '#fff', text: '#111', sub: '#666', border: '#e2e8f0', nav: '#fff', acc: '#ff4da6', inp: '#e8ecf0', it: '#111', glow: 'rgba(255,77,166,0.3)' },
    other:      { bg: '#f9fafb', card: '#fff', text: '#111', sub: '#666', border: '#e2e8f0', nav: '#fff', acc: '#8b5cf6', inp: '#e8ecf0', it: '#111', glow: 'rgba(139,92,246,0.3)' },
    prefer_not: { bg: '#f9fafb', card: '#fff', text: '#111', sub: '#666', border: '#e2e8f0', nav: '#fff', acc: '#888',    inp: '#e8ecf0', it: '#111', glow: 'rgba(150,150,150,0.2)' },
};
export const getTheme = (g) => THEMES[g] || THEMES.day;

// ─── Genders ──────────────────────────────────────────────────────────────────
export const GENDERS = [
    { value: 'male',       label: 'Male',       icon: '♂', accent: '#3b82f6' },
    { value: 'female',     label: 'Female',     icon: '♀', accent: '#ff4da6' },
    { value: 'other',      label: 'Other',      icon: '⚧', accent: '#8b5cf6' },
    { value: 'prefer_not', label: 'Prefer Not', icon: '◎', accent: '#888' },
];

// ─── Network Types ────────────────────────────────────────────────────────────
export const NETWORKS = [
    { id: 'public',       label: 'Public',       icon: '◉', desc: 'Everyone can see' },
    { id: 'friends',      label: 'Friends',      icon: '◈', desc: 'Invite only' },
    { id: 'local',        label: 'Local',        icon: '◎', desc: 'Near me (<20km)' },
    { id: 'professional', label: 'Professional', icon: '⬡', desc: 'Career network' },
    { id: 'anonymous',    label: 'Anonymous',    icon: '⎔', desc: 'Identity hidden' },
];

// ─── Event Category Groups (comprehensive list) ───────────────────────────────
export const CATEGORY_GROUPS = {
  '⛪ Faith': [
    'Church','Mosque','Temple','Synagogue','Bible Study','Youth Ministry','Prayer Group',
    'Revival','Baptism','Confirmation','Choir Practice','Sunday School','Cell Group',
    'Interfaith Dialogue','Islamic Lecture','Hindu Puja','Buddhist Retreat','Quaker Meeting',
    'Gospel Concert','Praise & Worship','Prophetic Service','Deliverance Service',
    'Marriage Enrichment','Faith Camp','Pilgrimage','Midnight Prayer','Zion Service',
    'Water Baptism','Faith Conference','Spiritual Retreat','Healing Service',
  ],
  '⚽ Sports': [
    'Football','Basketball','Soccer','Running','Cycling','Yoga','Gym','Swimming',
    'Tennis','Martial Arts','Golf','Cricket','Rugby','Volleyball','Boxing',
    'Athletics','Triathlon','Crossfit','Pilates','Archery','Badminton','Squash',
    'Table Tennis','Skateboarding','Surfing','Hiking','Climbing','Horse Riding',
    'Polo','Rowing','Canoe','Kite Surfing','Paragliding','Mountain Biking',
    'Parkour','Fencing','Wrestling','Judo','Karate','Taekwondo','BJJ',
    'Kickboxing','MMA','Bowling','Darts','Snooker','E-Sports','Frisbee','Netball',
    'Water Polo','Handball','Lacrosse','Baseball','Softball','American Football',
    'Ice Skating','Roller Skating','Cheerleading','Dance Fitness','Zumba',
    'Body Combat','Spin Class','Boot Camp','Obstacle Course','Fun Run','5K',
    'Half Marathon','Full Marathon','Trail Run','Ultra Marathon','Colour Run',
    'Night Run','Charity Run','Swim Meet','Swim Gala','Boxing Match',
  ],
  '💼 Career': [
    'Job Fair','Networking','Workshop','Hackathon','Startup Pitch','Mentorship',
    'Conference','Panel Talk','Interview Prep','Coding Bootcamp','Career Expo',
    'Internship Fair','Graduate Fair','Recruitment Drive','Talent Show',
    'Leadership Summit','Entrepreneur Meetup','Angel Investor Talk','VC Pitch Night',
    'Product Demo Day','Design Sprint','Strategy Offsite','Team Building',
    'Corporate Training','Sales Training','Marketing Conference','PR Workshop',
    'Finance Seminar','Law Symposium','Medical Conference','Nursing CPD',
    'Teacher Training','HR Summit','Diversity & Inclusion Forum','Women in Tech',
    'Black in Tech','Youth in Business','Freelancer Meetup','Creator Economy Talk',
    'Social Media Workshop','SEO Masterclass','Brand Strategy Session',
    'Agile Scrum Training','Data Science Bootcamp','Cloud Computing Workshop',
    'Cybersecurity Summit','Digital Transformation Conference','PropTech Expo',
    'FinTech Forum','EdTech Summit','HealthTech Conference','Logistics Forum',
    'Manufacturing Expo','Mining Summit','Agriculture Expo','Energy Conference',
  ],
  '🎉 Social': [
    'Party','Mixer','Happy Hour','Game Night','Movie Night','Dinner','Karaoke',
    'Speed Dating','Singles Event','Reunion','Braai','Shisanyama','Block Party',
    'House Party','Loft Party','Rooftop Party','Pool Party','Beach Party',
    'Garden Party','Costume Party','Masquerade','Gala','Awards Night',
    'Birthday Bash','Anniversary','Baby Shower','Bridal Shower','Hen Party',
    'Bachelor Party','After Party','Day Party','Sunday Funday','Sundowner',
    'Yacht Party','Boat Cruise','Game Drive Social','Picnic','Camping Trip',
    'Road Trip','Weekend Getaway','Girls Trip','Boys Trip','Friend Group Trip',
    'Festival','Carnival','Street Party','Cultural Celebration',
    'New Year Party','Christmas Party','Heritage Day','Freedom Day Celebration',
    'Valentine\'s Event','Halloween Event','Easter Egg Hunt','Diwali Celebration',
    'Eid Gathering','Hanukkah Party','Chinese New Year','Kwanzaa',
    'Mzansi Night','Afro Vibes Night','Whine & Cheese',
  ],
  '🎓 Education': [
    'Lecture','Study Group','Tutoring','Language Exchange','Science Fair',
    'Book Club','Debate','Research Talk','Coding Class','Math Olympiad',
    'Spelling Bee','School Open Day','University Open Day','TVET Info Day',
    'Scholarship Workshop','Bursary Application Help','Adult Literacy Class',
    'GED Prep','Matric Rewrite Prep','University Application Workshop',
    'Learnerships Info Day','NSFAS Briefing','Student Orientation',
    'Academic Symposium','Research Colloquium','PhD Defense','Postgrad Networking',
    'STEM Workshop','Girls in STEM','Robotics Competition','Coding for Kids',
    'Creative Writing Workshop','Essay Writing Workshop','Public Speaking Course',
    'Storytelling Workshop','Sign Language Class','Financial Literacy Workshop',
    'Investment Club','Crypto Education','Forex Training','Life Skills Workshop',
    'Driving Lessons','First Aid Course','CPR Training','Safety Training',
    'Photography Class','Cooking Class','Sewing Class','Art Class for Kids',
  ],
  '🎭 Arts & Culture': [
    'Music Concert','Art Show','Dance','Theater','Film Screening','Poetry',
    'Open Mic','Photography Walk','Gallery Opening','Jazz Night','Amapiano Night',
    'Afrobeats Night','Hip-Hop Show','R&B Night','Reggae Night','Kwaito Night',
    'Gqom Night','Maskandi Show','Gospel Show','Choir Festival','Opera',
    'Ballet','Contemporary Dance','Ballroom Dance','Salsa Night','Kizomba Night',
    'Bachata Night','Lindy Hop','Street Dance Battle','Krumping Battle',
    'Comedy Night','Stand-Up Comedy','Improv Show','Spoken Word','Slam Poetry',
    'Beat Battle','DJ Competition','Producer Meetup','Music Video Shoot',
    'Album Launch','EP Launch','Book Launch','Magazine Launch',
    'Fashion Show','Runway Show','Pop-Up Exhibition','Street Art Festival',
    'Mural Painting','Graffiti Jam','Sculpture Exhibition','Ceramics Class',
    'Pottery Workshop','Painting Class','Watercolour Workshop','Life Drawing',
    'Illustration Masterclass','Graphic Design Workshop','Motion Graphics',
    'Animation Workshop','Film Festival','Short Film Showcase','Documentary Screening',
    'Drive-In Movie','Outdoor Cinema','Market','Craft Market','Flea Market',
    'Night Market','Vintage Fair','Antique Fair','Cultural Festival',
  ],
  '🌿 Wellness & Health': [
    'Meditation','Mental Health','Support Group','Nutrition Talk','Therapy Session',
    'Breathwork','Journaling Circle','Yoga Retreat','Sound Bath','Reiki Healing',
    'Acupuncture Workshop','Crystal Healing','Aromatherapy','Massage Workshop',
    'Detox Programme','Juice Cleanse','Health & Wellness Expo','Fitness Challenge',
    'Weight Loss Programme','Body Transformation Challenge','Mindfulness Workshop',
    'Stress Management','Burnout Recovery Workshop','Grief Support Group',
    'Addiction Recovery Meeting','AA Meeting','NA Meeting','Anger Management',
    'Relationship Counselling','Couples Retreat','Parenting Workshop',
    'Fertility Support','Prenatal Yoga','Postnatal Support','Breastfeeding Circle',
    'Women\'s Circle','Men\'s Group','Teen Support Group','LGBTQ+ Support Group',
    'HIV/AIDS Awareness','Cancer Awareness','Diabetes Workshop','Blood Pressure Check',
    'Blood Drive','Organ Donation Drive','Eye Test Day','Dental Check-Up',
    'Health Screening','Vaccination Drive','Mental Health Awareness Walk',
    'World AIDS Day','Breast Cancer Walk','Movember Event',
  ],
  '🌍 Community & Activism': [
    'Volunteer','Charity Drive','Clean-Up','Fundraiser','Town Hall',
    'Awareness Walk','Food Drive','Protest March','Petition Campaign',
    'Community Meeting','Ward Councillor Meeting','Street Committee Meeting',
    'Neighborhood Watch','Crime Prevention Workshop','Safety Forum',
    'Voter Registration Drive','Election Campaign','Political Rally',
    'Human Rights Event','Gender-Based Violence Awareness','Gender Equality Forum',
    'Climate Change Rally','Environmental Clean-Up','Tree Planting','Park Revamp',
    'Housing Rights Workshop','Tenant Rights Meeting','Social Grant Application Help',
    'SASSA Help Desk','Home Affairs Drive','Legal Aid Clinic','Free Legal Advice',
    'Know Your Rights Workshop','Consumer Rights Workshop','Land Rights Forum',
    'Youth Parliament','Student Representative Council','Community Radio Show',
    'Newspaper Launch','Zine Making','Podcast Recording','Community Theatre',
    'Archive Project','Oral History Collection','Heritage Walk','Cultural Tour',
    'Museum Day','Library Reading Day','Community Library Launch',
  ],
  '🎮 Tech & Gaming': [
    'Hackathon','AI Meetup','Dev Talk','Product Launch','Tech Demo',
    'Robotics','Gaming Tournament','Esports Competition','LAN Party',
    'Game Jam','Indie Game Showcase','Console Gaming Night','PC Gaming Night',
    'Mobile Gaming Tournament','Card Game Tournament','Chess Tournament',
    'Puzzle Competition','VR Experience','AR Workshop','Drone Racing',
    '3D Printing Workshop','Electronics Workshop','Arduino Class','Raspberry Pi',
    'Open Source Meetup','Linux Users Group','Blockchain Meetup','NFT Discussion',
    'Metaverse Event','Web3 Summit','DeFi Discussion','Crypto Trading Class',
    'App Development Marathon','No-Code Workshop','Low-Code Demo Day',
    'UX Design Sprint','UI Design Workshop','Figma Masterclass','Webflow Class',
    'WordPress Workshop','Shopify Setup','E-commerce Strategy','SEO Workshop',
    'Digital Marketing Course','Social Media Strategy','Content Creation Workshop',
    'Podcast Production Class','YouTube Growth Workshop','TikTok Strategy',
    'Streaming Setup Guide','Photography & Editing Workshop','Video Production',
  ],
  '🍽️ Food & Drink': [
    'Food Festival','Wine Tasting','Cook-Off','Pop-Up Restaurant','Bake Sale',
    'Street Food Tour','Beer Festival','Gin Festival','Whisky Tasting',
    'Craft Beer Night','Cocktail Masterclass','Mocktail Workshop','Braai Competition',
    'Potjie Competition','Chilli Cook-Off','Pizza Baking Class','Pasta Workshop',
    'Sushi Making Class','Bread Baking','Cake Decorating','Cupcake Workshop',
    'Vegan Cooking Class','Plant-Based Workshop','Gluten-Free Baking',
    'Diabetic-Friendly Cooking','Budget Meals Workshop','Meal Prep Workshop',
    'Coffee Tasting','Tea Ceremony','Barista Training','Mixology Class',
    'Cheese & Wine Pairing','Charcuterie Workshop','Chocolate Tasting',
    'Ice Cream Social','Dessert Pop-Up','Supper Club','Fine Dining Experience',
    'Farmers Market','Organic Market','Health Food Market','Night Food Market',
    'Restaurant Week','Food Truck Festival','Braai & Jazz','Sundowner Braai',
    'Picnic in the Park','Champagne Breakfast','Bottomless Brunch','High Tea',
    'Traditional Food Experience','Heritage Cuisine Night','African Food Festival',
    'Indian Food Night','Cape Malay Cooking','Zulu Cuisine','Xhosa Cuisine',
  ],
  '🏠 Lifestyle': [
    'Home Décor Workshop','Interior Design Talk','DIY Home Improvement',
    'Garden Design','Plant Sale','Succulent Workshop','Flower Arranging',
    'Knitting Circle','Crochet Workshop','Embroidery Class','Quilting Bee',
    'Upcycling Workshop','Sustainable Living Talk','Zero Waste Workshop',
    'Minimalism Masterclass','Decluttering Workshop','Feng Shui Talk',
    'Property Investing Seminar','First-Time Buyer Workshop','Bond Application Help',
    'Rental Rights Workshop','Body Corporate Meeting','HOA Meeting',
    'Car Enthusiast Meetup','Classic Car Show','Motorbike Rally','Off-Road Meetup',
    'Pet Adoption Day','Dog Training Class','Cat Café','Pet Photography',
    'Parenting Talk','Toddler Playdate','Kids Birthday Party','Educational Toy Fair',
    'Baby Expo','Children\'s Book Fair','Family Fun Day','Kids Art Workshop',
    'Family Movie Night','Board Game Night','Escape Room','Quiz Night',
    'Pub Quiz','Trivia Night','Bingo Night','Casino Night','Poker Night',
    'Mahjong Group','Bridge Club','Scrabble Club','Crossword Club',
  ],
  '✈️ Travel & Adventure': [
    'Hiking','Trail Walking','Mountain Biking','Rock Climbing','Abseiling',
    'Skydiving','Bungee Jumping','Zipline','Quad Biking','4x4 Off-Road',
    'Camping','Star Gazing','Wildlife Safari','Game Drive','Bird Watching',
    'Whale Watching','Shark Cage Diving','Scuba Diving','Snorkelling','Kayaking',
    'White Water Rafting','Stand-Up Paddleboarding','Windsurfing','Kitesurfing',
    'Deep Sea Fishing','Fly Fishing','Weekend Getaway','Backpacking',
    'Travel Meetup','Digital Nomad Meetup','Solo Travel Forum','Group Tour',
    'Heritage Tour','Township Tour','Wine Route Tour','Garden Route Trip',
    'Drakensberg Trip','Kruger Trip','Cape Town Trip','Durban Beach Trip',
    'International Travel Planning','Visa Application Workshop','Travel Hacking',
    'Budget Travel Tips','Luxury Travel Showcase','Glamping',
  ],
  '🎵 Music genres': [
    'Amapiano Night','Afrobeats Show','Kwaito Night','Gqom Night','Afro House',
    'Deep House','Tech House','Progressive House','Techno Night','Drum & Bass',
    'Jungle Night','UK Garage','Afro Soul','Neo Soul','Jazz Brunch',
    'Nu Jazz','Smooth Jazz','Bebop Jazz','Free Jazz','Blues Night',
    'Rock Night','Indie Night','Pop Concert','K-Pop Night','J-Pop Gathering',
    'Hip-Hop Night','Trap Night','Drill Show','Boom Bap Night','Old School Hip-Hop',
    'Gospel Fest','Praise Night','Worship Concert','Hymns Evening',
    'Classical Concert','Chamber Music','Opera Evening','String Quartet',
    'Reggae Night','Dancehall Night','Soca Night','Calypso Night',
    'Latin Night','Salsa Concert','Cumbia Night','Merengue Party',
    'Maskandi Night','Isicathamiya','Mbaqanga Show','Marabi Evening',
    'Country Night','Folk Music Session','Bluegrass Evening','Americana Night',
    'Metal Night','Heavy Metal Concert','Punk Night','Alternative Rock',
    'Rave','Underground Party','Warehouse Party','Techno Rave','Psytrance',
    'Trance Night','EDM Festival','Electronic Music Festival',
  ],
  '📸 Content & Creator': [
    'Content Creator Meetup','Influencer Brunch','Blogger Meetup',
    'YouTuber Gathering','Podcaster Networking','Photographer Meetup',
    'Videographer Workshop','Social Media Panel','Brand Deal Masterclass',
    'Monetisation Workshop','UGC Creator Workshop','OnlyFans Strategy (Safe)',
    'Substack Writers Circle','Newsletter Growth','Community Building Workshop',
    'Personal Branding Workshop','LinkedIn Masterclass','Twitter/X Strategy',
    'Instagram Growth','TikTok Creator Camp','Reel Shooting Day',
    'YouTube Thumbnail Workshop','Editing Masterclass','Colour Grading Class',
    'Audio Engineering Basics','Podcast Editing','Live Streaming Workshop',
    'Drone Filming Class','Timelapse Workshop','Street Photography Walk',
    'Fashion Photography','Portrait Photography','Product Photography',
    'Food Photography','Event Photography','Wedding Photography Tips',
    'Studio Day','Behind-the-Scenes Set Visit','Script Writing Workshop',
    'Short Film Making','Music Video Production','Documentary Workshop',
  ],
  '💰 Finance & Business': [
    'Stock Market Workshop','JSE Investment Talk','ETF Explained','Unit Trust',
    'TFSA Planning','Retirement Planning','Estate Planning','Will Writing',
    'Business Registration Workshop','CIPC Registration Help','Tax Workshop',
    'SARS E-Filing Help','VAT Registration','Company Compliance','Accounting Basics',
    'Bookkeeping Course','Financial Modelling','Business Valuation','Due Diligence',
    'Mergers & Acquisitions','Private Equity Talk','Venture Capital Night',
    'Angel Investing','Crowdfunding Workshop','Grant Writing','SEDA Workshop',
    'NEF Funding Talk','IDC Funding Seminar','NYDA Briefing','SEFA Loans',
    'SMMEs Forum','Township Economy Summit','Informal Trader Support',
    'Spaza Shop Development','Cooperative Formation','Social Enterprise',
    'Franchise Expo','Retail Strategy','Import & Export Workshop',
    'Supply Chain Talk','Logistics Expo','E-Commerce Launch',
    'Dropshipping Workshop','Amazon FBA','Takealot Seller Talk',
    'Print on Demand','Etsy for Crafters','Fiverr Freelancing',
  ],
  '🎪 Festivals & Expos': [
    'Art Festival','Music Festival','Food Festival','Cultural Festival',
    'Literary Festival','Science Festival','Technology Expo','Motor Show',
    'Property Expo','Wedding Expo','Baby Expo','Travel Expo','Franchise Expo',
    'Wellness Expo','Beauty Expo','Fashion Week','Design Week','Architecture Tour',
    'Heritage Festival','Jazz Festival','Blues Festival','Comedy Festival',
    'Film Festival','Theatre Festival','Dance Festival','Spoken Word Festival',
    'Street Culture Festival','Urban Arts Festival','Skateboarding Festival',
    'BMX Festival','Surfing Competition','Running Festival','Cycling Festival',
    'Outdoor Festival','Nature Festival','Environment Expo','Green Building',
    'Solar Energy Expo','Agriculture Show','Rand Show','Cape Town Cycle Tour',
    'Cape Town Jazz Festival','Oppikoppi','Ultra SA','Music Is Life',
    'Africa Rising Festival','Pan-African Festival','Durban July',
    'Comic Con Africa','Fan Expo','Anime Expo','Gaming Expo',
  ],
};

export const ALL_CATEGORIES = ['All', ...Object.values(CATEGORY_GROUPS).flat()];
export const GROUP_KEYS = Object.keys(CATEGORY_GROUPS);

// ─── Interest Tags (for feed personalization) ─────────────────────────────────
export const INTERESTS = [
    { id: 'church',    label: 'Faith',      icon: '⛪', color: '#8b5cf6' },
    { id: 'sports',    label: 'Sports',     icon: '⚽', color: '#10b981' },
    { id: 'career',    label: 'Career',     icon: '💼', color: '#3b82f6' },
    { id: 'social',    label: 'Social',     icon: '🎉', color: '#f59e0b' },
    { id: 'education', label: 'Education',  icon: '🎓', color: '#06b6d4' },
    { id: 'arts',      label: 'Arts',       icon: '🎭', color: '#ec4899' },
    { id: 'wellness',  label: 'Wellness',   icon: '🌿', color: '#34d399' },
    { id: 'community', label: 'Community',  icon: '🌍', color: '#64748b' },
    { id: 'tech',      label: 'Tech',       icon: '🎮', color: '#a855f7' },
    { id: 'food',      label: 'Food',       icon: '🍽️', color: '#ef4444' },
    { id: 'music',     label: 'Music',      icon: '🎵', color: '#f97316' },
    { id: 'travel',    label: 'Travel',     icon: '✈️', color: '#14b8a6' },
    { id: 'finance',   label: 'Finance',    icon: '💰', color: '#84cc16' },
    { id: 'creator',   label: 'Creator',    icon: '📸', color: '#fb923c' },
    { id: 'lifestyle', label: 'Lifestyle',  icon: '🏠', color: '#e879f9' },
    { id: 'festival',  label: 'Festivals',  icon: '🎪', color: '#fbbf24' },
];

// ─── Report Reasons ────────────────────────────────────────────────────────────
export const REPORT_REASONS = [
    'Spam', 'Offensive language', 'Harassment', 'False information',
    'Adult content', 'Copyright violation', 'Misinformation', 'Other',
];

// ─── Search Tags / Autocomplete hints ────────────────────────────────────────
export const SEARCH_TAGS = [
    'church','networking','party','yoga','hackathon','concert','volunteering',
    'dating','bootcamp','marathon','art show','game night','job fair','open mic',
    'meditation','food festival','clean-up','mentorship','cinema','study group',
    'amapiano','shisanyama','braai','kwaito','gqom','afrobeats','jazz','wine',
    'startup','coding','wellness','retreat','comedy','forex','crypto','esports',
];
