// ─── MASSIVE DESCRIPTOR DATABASE (2,100 Words) ───────────────────────────────

export const PERSONALITY_VIRTUOUS = ['Altruistic', 'Benevolent', 'Chivalrous', 'Conscientious', 'Diligent', 'Empathetic', 'Fortuitous', 'Generous', 'Honorable', 'Industrious', 'Jovial', 'Kindhearted', 'Loyal', 'Magnanimous', 'Noble', 'Philanthropic', 'Reliable', 'Sincere', 'Trustworthy', 'Valiant'];
export const PERSONALITY_INTELLECTUAL = ['Analytical', 'Astute', 'Cerebral', 'Discerning', 'Erudite', 'Ingenious', 'Insightful', 'Judicious', 'Knowledgeable', 'Logical', 'Meticulous', 'Observant', 'Perceptive', 'Pragmatic', 'Rational', 'Sagacious', 'Scholarly', 'Theoretical', 'Visionary', 'Wise'];
export const PERSONALITY_SOCIAL = ['Affable', 'Articulate', 'Charismatic', 'Congenial', 'Diplomatic', 'Eloquent', 'Engaging', 'Extroverted', 'Forthright', 'Gregarious', 'Harmonious', 'Outgoing', 'Personable', 'Polite', 'Sociable', 'Suave', 'Talkative', 'Unflappable', 'Urbane', 'Vivacious'];
export const PERSONALITY_CHALLENGING = ['Aloof', 'Arrogant', 'Belligerent', 'Callous', 'Cantankerous', 'Capricious', 'Cynical', 'Deceitful', 'Dogmatic', 'Egotistical', 'Fickle', 'Hostile', 'Malevolent', 'Narcissistic', 'Obstinate', 'Pompous', 'Pugnacious', 'Supercilious', 'Treacherous', 'Vindictive'];
export const PERSONALITY_TEMPERAMENT = ['Amiable', 'Buoyant', 'Carefree', 'Composed', 'Demure', 'Enigmatic', 'Exuberant', 'Guarded', 'Impulsive', 'Level-headed', 'Melancholy', 'Pensive', 'Placid', 'Resilient', 'Stoic', 'Tenacious', 'Unyielding', 'Whimsical', 'Zealous', 'Serene'];

export const PHYSICAL_BODY = ['Athletic', 'Brawny', 'Burly', 'Chiseled', 'Compact', 'Dainty', 'Delicate', 'Elegant', 'Gaunt', 'Graceful', 'Lanky', 'Lithe', 'Muscular', 'Petite', 'Portly', 'Robust', 'Rugged', 'Sinewy', 'Statuesque', 'Wiry'];
export const PHYSICAL_FACE_EYES = ['Angular', 'Beaming', 'Bright-eyed', 'Dimpled', 'Distinguished', 'Expressive', 'Fair', 'Freckled', 'Glistening', 'Glowing', 'Handsome', 'Impeccable', 'Luminous', 'Pale', 'Piercing', 'Radiant', 'Sallow', 'Symmetrical', 'Weathered', 'Wrinkled'];
export const PHYSICAL_HAIR = ['Auburn', 'Bobbed', 'Braided', 'Bushy', 'Coiffed', 'Disheveled', 'Grizzled', 'Lustrous', 'Platinum', 'Shaggy', 'Sleek', 'Thinning', 'Tousled', 'Unkempt', 'Voluminous', 'Wavy', 'Wispy', 'Cropped', 'Manicured', 'Silver-haired'];
export const PHYSICAL_AESTHETIC = ['Aesthetic', 'Breathtaking', 'Chic', 'Dapper', 'Exquisite', 'Fashionable', 'Glamorous', 'Homely', 'Immaculate', 'Jauntily-dressed', 'Modish', 'Ornate', 'Polished', 'Quaint', 'Radiant', 'Scruffy', 'Sophisticated', 'Striking', 'Trendy', 'Unassuming'];
export const PHYSICAL_AGE = ['Adolescent', 'Ancient', 'Bedridden', 'Bloom', 'Decrepit', 'Elderly', 'Fragile', 'Healthy', 'Infantile', 'Juvenile', 'Mature', 'Middle-aged', 'Prime', 'Senile', 'Sprightly', 'Sturdy', 'Venerable', 'Vigorous', 'Withered', 'Youthful'];

export const MANNERISMS_SOCIAL = ['Abrupt', 'Accommodating', 'Assertive', 'Boisterous', 'Businesslike', 'Chatty', 'Collaborative', 'Condescending', 'Direct', 'Formal', 'Garrulous', 'Inquisitive', 'Introverted', 'Mannerly', 'Nonchalant', 'Outspoken', 'Reserved', 'Reticent', 'Straightforward', 'Taciturn'];
export const MANNERISMS_EMOTIONAL = ['Agitated', 'Apprehensive', 'Bewildered', 'Bold', 'Calm', 'Courageous', 'Defiant', 'Despondent', 'Eager', 'Fearful', 'Flustered', 'Hysterical', 'Indifferent', 'Irritable', 'Jittery', 'Nervous', 'Overwhelmed', 'Panic-stricken', 'Resolute', 'Startled'];
export const MANNERISMS_WORK = ['Ambitious', 'Careless', 'Competent', 'Decisive', 'Disorganized', 'Efficient', 'Focused', 'Hesitant', 'Lazy', 'Methodical', 'Motivated', 'Persistent', 'Proactive', 'Punctual', 'Scrupulous', 'Shoddy', 'Systematic', 'Thorough', 'Unproductive', 'Workaholic'];
export const MANNERISMS_MORAL = ['Corrupt', 'Devious', 'Ethical', 'Fraudulent', 'Honest', 'Hypocritical', 'Innocent', 'Just', 'Principled', 'Pure', 'Radical', 'Righteous', 'Saintly', 'Shady', 'Sinister', 'Transparent', 'Unscrupulous', 'Upright', 'Wicked', 'Worthy'];
export const MANNERISMS_QUIRKY = ['Absent-minded', 'Eccentric', 'Flamboyant', 'Idiosyncratic', 'Irreverent', 'Kooky', 'Mischievous', 'Peculiar', 'Playful', 'Quizzical', 'Spontaneous', 'Strange', 'Unconventional', 'Unpredictable', 'Wacky', 'Wayward', 'Wild', 'Witty', 'Zany', 'Zealous'];

export const ROLE_LEADERSHIP = ['Authoritative', 'commanding', 'decisive', 'influential', 'strategic', 'visionary', 'charismatic', 'stern', 'imposing', 'bureaucratic', 'autocratic', 'democratic', 'visionary', 'egalitarian', 'resolute', 'formidable', 'diplomatic', 'inspiring', 'unyielding', 'paternalistic', 'pioneering', 'seasoned', 'veteran', 'grassroots', 'figurehead', 'sovereign', 'magisterial', 'imperious', 'tyrannical', 'managerial', 'principled', 'vigilant', 'stalwart', 'unifying', 'trailblazing', 'innovative', 'progressive', 'traditionalist', 'vanguard', 'veteran'];
export const ROLE_CREATIVE = ['Bohemian', 'avant-garde', 'expressive', 'imaginative', 'abstract', 'poetic', 'eccentric', 'stylistic', 'artisanal', 'inspired', 'melodious', 'rhythmic', 'visual', 'nonconformist', 'visionary', 'eclectic', 'fluid', 'aesthetic', 'colorful', 'dramatic', 'lyrical', 'inventive', 'original', 'whimsical', 'profound', 'sensitive', 'moody', 'spirited', 'avant-garde', 'unconventional', 'radical', 'profound', 'nuanced', 'intricate', 'vivid', 'soulful', 'surreal', 'minimalist', 'maximalist', 'evocative'];
export const ROLE_SCIENTIFIC = ['Methodical', 'analytical', 'clinical', 'systematic', 'precise', 'objective', 'empirical', 'logical', 'technical', 'specialized', 'rigorous', 'meticulous', 'calculated', 'data-driven', 'skeptical', 'observant', 'rational', 'diagnostic', 'experimental', 'factual', 'scrupulous', 'detailed', 'accurate', 'proficient', 'efficient', 'advanced', 'theoretical', 'practical', 'applied', 'pragmatic', 'complex', 'streamlined', 'high-tech', 'mechanical', 'digital', 'sterile', 'focused', 'sharp', 'keen', 'investigative'];
export const ROLE_TRADE = ['Industrious', 'hardworking', 'manual', 'skilled', 'dexterous', 'nimble', 'sturdy', 'reliable', 'resilient', 'practical', 'rugged', 'helpful', 'attentive', 'courteous', 'hospitable', 'diligent', 'efficient', 'thorough', 'versatile', 'seasoned', 'apprentice', 'journeyman', 'master', 'expert', 'dedicated', 'prompt', 'compliant', 'organized', 'methodical', 'tireless', 'energetic', 'friendly', 'obliging', 'supportive', 'selfless', 'patient', 'approachable', 'professional', 'task-oriented', 'grounded'];
export const ROLE_LAW = ['Disciplined', 'vigilant', 'tactical', 'brave', 'heroic', 'stoic', 'alert', 'observant', 'assertive', 'formal', 'rigid', 'honorable', 'just', 'protective', 'defensive', 'offensive', 'strategic', 'calm', 'controlled', 'trained', 'combat-ready', 'lethal', 'non-lethal', 'investigative', 'forensic', 'legalistic', 'moral', 'ethical', 'sworn', 'undercover', 'overt', 'covert', 'official', 'bureaucratic', 'judicial', 'penalty-focused', 'rehabilitative', 'strict', 'severe', 'impartial'];

export const SENSORY_VOICE = ['Melodious', 'gravelly', 'raspy', 'shrill', 'booming', 'whispering', 'guttural', 'nasal', 'breathy', 'honeyed', 'velvety', 'harsh', 'staccato', 'rhythmic', 'monotone', 'expressive', 'articulate', 'slurred', 'stammering', 'eloquent', 'silver-tongued', 'gruff', 'hoarse', 'lyrical', 'piercing', 'resonant', 'sonorous', 'thin', 'reedy', 'squeaky', 'husky', 'throaty', 'clear', 'muffled', 'loud', 'soft', 'gentle', 'abrasive', 'biting', 'sarcastic', 'deadpan', 'drawling', 'clipped', 'rapid', 'slow', 'measured', 'cautious', 'booming', 'thunderous', 'hushed'];
export const SENSORY_SCENT = ['Fragrant', 'musky', 'floral', 'earthy', 'woodsy', 'clean', 'sterile', 'medicinal', 'pungent', 'acrid', 'stale', 'smokey', 'spicy', 'citrusy', 'sweet', 'cloying', 'faint', 'overpowering', 'subtle', 'fresh', 'salty', 'metallic', 'chemical', 'natural', 'wild', 'feral', 'perfumed', 'cologne-scented', 'soapy', 'dusty', 'musty', 'damp', 'dry', 'crisp', 'heavy', 'light', 'airy', 'ethereal', 'grounded', 'intoxicating'];
export const SENSORY_GAIT = ['Lumbering', 'graceful', 'agile', 'nimble', 'sluggish', 'deliberate', 'frantic', 'rhythmic', 'unsteady', 'plodding', 'skipping', 'strutting', 'sauntering', 'swaggering', 'creeping', 'gliding', 'marching', 'pacing', 'darting', 'scurrying', 'wandering', 'drifting', 'lunging', 'staggering', 'limping', 'heavy-footed', 'light-footed', 'fluid', 'stiff', 'robotic', 'jerky', 'smooth', 'effortless', 'laborious', 'energetic', 'lethargic', 'purposeful', 'aimless', 'quick', 'slow'];
export const SENSORY_PRESENCE = ['Menacing', 'inviting', 'warm', 'cold', 'electric', 'magnetic', 'repulsive', 'intimidating', 'comforting', 'eerie', 'ghostly', 'solid', 'shadow-like', 'radiant', 'dull', 'vibrant', 'statuesque', 'fragile', 'hulking', 'towering', 'diminutive', 'imposing', 'inconspicuous', 'flashy', 'gaudy', 'humble', 'regal', 'peasant-like', 'angelic', 'demonic', 'feral', 'civilized', 'rustic', 'urban', 'sophisticated', 'primitive', 'ancient', 'youthful', 'weary', 'restless'];

export const ABSTRACT_MORAL = ['Saintly', 'wicked', 'virtuous', 'corrupt', 'pure', 'tainted', 'angelic', 'devilish', 'righteous', 'sinful', 'noble', 'ignoble', 'honorable', 'treacherous', 'loyal', 'disloyal', 'selfless', 'selfish', 'altruistic', 'greedy', 'humble', 'proud', 'modest', 'vain', 'innocent', 'guilty', 'naive', 'worldly', 'spiritual', 'profane', 'holy', 'sacrilegious', 'kind', 'cruel', 'merciful', 'ruthless', 'forgiving', 'vindictive', 'patient', 'wrathful'];
export const ABSTRACT_MYTHICAL = ['Heroic', 'villainous', 'sage', 'fool', 'trickster', 'mentor', 'ward', 'guardian', 'hunter', 'prey', 'wanderer', 'hermit', 'kingly', 'queenly', 'knightly', 'servant', 'master', 'slave', 'rebel', 'conformist', 'martyr', 'survivor', 'savior', 'destroyer', 'creator', 'preserver', 'prophet', 'skeptic', 'believer', 'dreamer', 'realist', 'optimist', 'pessimist', 'nihilist', 'zealot', 'heretic', 'outlaw', 'citizen', 'nomad', 'ghost'];
export const ABSTRACT_EMOTIONAL = ['Ecstatic', 'despondent', 'furious', 'serene', 'anxious', 'confident', 'terrified', 'brave', 'ashamed', 'proud', 'lonely', 'loved', 'hated', 'bitter', 'sweet', 'sour', 'numb', 'sensitive', 'volatile', 'stable', 'fragile', 'tough', 'resilient', 'broken', 'healed', 'yearning', 'content', 'restless', 'peaceful', 'turbulent', 'mourning', 'celebrating', 'bored', 'fascinated', 'indifferent', 'passionate', 'cold', 'fiery', 'icy', 'lukewarm'];
export const ABSTRACT_INTELLECTUAL = ['Genius', 'simpleton', 'ignorant', 'enlightened', 'confused', 'certain', 'doubtful', 'curious', 'incurious', 'analytical', 'creative', 'logical', 'erratic', 'focused', 'distracted', 'alert', 'asleep', 'aware', 'oblivious', 'sharp', 'dull', 'deep', 'shallow', 'complex', 'simple', 'multifaceted', 'narrow-minded', 'open-minded', 'flexible', 'rigid', 'progressive', 'regressive', 'modern', 'archaic', 'timeless'];

export const EMOTIONS_JOY = ['Radiant', 'ecstatic', 'jubilant', 'blissful', 'buoyant', 'chirpy', 'contented', 'delighted', 'elated', 'exhilarated', 'frolicsome', 'gleeful', 'lighthearted', 'mirthful', 'playful', 'rakish', 'sanguine', 'sparkling', 'sunny', 'thrilled', 'upbeat', 'whimsical', 'zestful', 'beaming', 'carefree', 'convivial', 'festive', 'genial', 'heartened', 'invigorated', 'jaunty', 'lolling', 'mellow', 'perky', 'refreshed', 'spirited', 'tranquil', 'unburdened', 'vivacious', 'winsome'];
export const EMOTIONS_SORROW = ['Bereft', 'dejected', 'desolate', 'despondent', 'disconsolate', 'doleful', 'forlorn', 'gloomy', 'heartbroken', 'inconsolable', 'lugubrious', 'melancholy', 'miserable', 'morose', 'mournful', 'pensive', 'plaintive', 'rueful', 'somber', 'sorrowful', 'tearful', 'woebegone', 'wretched', 'abysmal', 'bleak', 'blue', 'crestfallen', 'dismal', 'dreary', 'funereal', 'grieving', 'heavy-hearted', 'joyless', 'lachrymose', 'lonely', 'oppressed', 'pathetic', 'pessimistic', 'somber', 'tragic'];
export const EMOTIONS_ANGER = ['Abrasive', 'acrimonious', 'belligerent', 'bitter', 'choleric', 'contentious', 'dyspeptic', 'exasperated', 'fiery', 'fractious', 'furious', 'heated', 'huffy', 'ill-tempered', 'indignant', 'inflamed', 'irascible', 'irate', 'ireful', 'irritable', 'malevolent', 'moody', 'nettled', 'obsessive', 'offended', 'petulant', 'prickly', 'pugnacious', 'resentful', 'scorched', 'seething', 'sharp', 'spiteful', 'surly', 'testy', 'truculent', 'vengeful', 'vexed', 'viperous', 'wrathful'];
export const EMOTIONS_FEAR = ['Anxious', 'apprehensive', 'cornered', 'daunted', 'diffident', 'disconcerted', 'distrustful', 'edgy', 'faint-hearted', 'fearful', 'fidgety', 'flustered', 'hesitant', 'hysterical', 'inhibited', 'insecure', 'jittery', 'mousy', 'nervous', 'neurotic', 'panicky', 'paralyzed', 'paranoid', 'perturbed', 'petrified', 'precarious', 'quaking', 'rattled', 'recoiling', 'shaken', 'sheepish', 'skittish', 'startled', 'suspicious', 'terrified', 'timid', 'timorous', 'trembling', 'uneasy', 'wary'];
export const EMOTIONS_CALM = ['Abiding', 'absorbed', 'attentive', 'balanced', 'centered', 'collected', 'composed', 'concentrated', 'detached', 'disciplined', 'equable', 'even-keeled', 'impassive', 'imperturbable', 'intent', 'meditative', 'mild', 'neutralized', 'nonreactive', 'patient', 'peaceable', 'placid', 'poised', 'preoccupied', 'quiescent', 'reflective', 'relaxed', 'resolute', 'sedate', 'self-possessed', 'serene', 'sober', 'steady', 'still', 'stoic', 'thought-filled', 'unagitated', 'unbothered', 'undisturbed', 'unflappable'];

export const CULTURAL_CLASS = ['Aristocratic', 'blue-collar', 'bourgeois', 'bureaucratic', 'celebrated', 'common', 'cosmopolitan', 'debased', 'destitute', 'distinguished', 'elite', 'eminent', 'enslaved', 'exiled', 'high-born', 'impoverished', 'indigent', 'influential', 'lowly', 'marginalized', 'middle-class', 'noble', 'opulent', 'outcast', 'pariah', 'patrician', 'pauper', 'peasant', 'plebeian', 'privileged', 'proletarian', 'prosperous', 'reclusive', 'refined', 'royal', 'squalid', 'titular', 'under-privileged', 'up-and-coming', 'wealthy'];
export const CULTURAL_WORLDVIEW = ['Agnostic', 'altruistic', 'cynical', 'dogmatic', 'egalitarian', 'existential', 'fatalistic', 'hedonistic', 'idealistic', 'individualistic', 'liberal', 'materialistic', 'misanthropic', 'modernistic', 'narcissistic', 'nihilistic', 'objective', 'optimistic', 'orthodox', 'pacifistic', 'partisan', 'pessimistic', 'philanthropic', 'pious', 'pragmatic', 'progressive', 'radical', 'reactionary', 'secular', 'skeptical', 'spiritual', 'stoical', 'subjective', 'superstitious', 'traditional', 'transcendental', 'universal', 'utilitarian', 'utopian', 'zealous'];
export const CULTURAL_EDUCATION = ['Academic', 'autodidactic', 'bookish', 'brainy', 'cultured', 'didactic', 'educated', 'enlightened', 'erudite', 'highbrow', 'ignorant', 'illiterate', 'informed', 'intellectual', 'intuitive', 'learned', 'lettered', 'literate', 'lowbrow', 'pedantic', 'philistine', 'polymathic', 'precocious', 'provincial', 'sage', 'scholarly', 'self-taught', 'sophisticated', 'studious', 'uneducated', 'uninformed', 'unlettered', 'unpolished', 'unrefined', 'urbane', 'vacant', 'versant', 'versatile', 'well-read', 'wise'];
export const CULTURAL_LIFESTYLE = ['Ascetic', 'bohemian', 'decadent', 'dissolute', 'domestic', 'eccentric', 'extravagant', 'frugal', 'gluttonous', 'homely', 'itinerant', 'lavish', 'minimalist', 'nomadic', 'nocturnal', 'orderly', 'ostentatious', 'parsimonious', 'prodigal', 'prudish', 'reclusive', 'rustic', 'sedentary', 'self-indulgent', 'slovenly', 'sober', 'solitary', 'Spartan', 'spendthrift', 'sybaritic', 'temperate', 'thrifty', 'transient', 'unpretentious', 'urban', 'vagrant', 'vegetarian', 'voluptuous', 'wasteful', 'worldly'];
export const CULTURAL_REPUTATION = ['Admired', 'blacklisted', 'championed', 'condemned', 'discredited', 'disgraced', 'disreputable', 'esteemed', 'exalted', 'famed', 'glorified', 'honored', 'iconic', 'illustrious', 'infamous', 'lauded', 'legendary', 'loathed', 'maligned', 'mocked', 'notorious', 'obscure', 'praised', 'renowned', 'respected', 'reviled', 'ridiculed', 'slandered', 'stigmatized', 'touted', 'uncelebrated', 'underrated', 'unheralded', 'unknown', 'unrecognized', 'unsung', 'venerated', 'vilified', 'well-known', 'worshipped'];

export const ANATOMY_EYES = ['Almond-eyed', 'amber', 'amethyst', 'aquamarine', 'asymmetrical', 'beryl', 'beady', 'bloodshot', 'bulging', 'clouded', 'cold', 'deep-set', 'doe-eyed', 'drooping', 'emerald', 'expressionless', 'glassy', 'gold-flecked', 'hazel', 'heavy-lidded', 'hooded', 'icy', 'indigo', 'jaundiced', 'keen', 'lash-fringed', 'liquid', 'misty', 'narrow', 'obsidian', 'piercing', 'rheumy', 'sapphire', 'slanted', 'sunken', 'teardrop-shaped', 'twinkling', 'vacant', 'violet', 'wide-eyed'];
export const ANATOMY_MOUTH = ['Bow-shaped', 'buck-toothed', 'chapped', 'crooked', 'Cupid’s-bow', 'downturned', 'firm', 'fleshy', 'gap-toothed', 'grim', 'lopsided', 'lush', 'narrow', 'ornate', 'painted', 'pale', 'parched', 'pearly', 'pouting', 'pursed', 'rosebud', 'ruby', 'scarred', 'sculpted', 'sensuous', 'slack', 'small', 'smiling', 'sneering', 'soft', 'square', 'stained', 'thin', 'toothless', 'trembling', 'upturned', 'vanished', 'velvet', 'wide', 'wry'];
export const ANATOMY_HANDS = ['Adroit', 'brawny', 'calloused', 'clumsy', 'coarse', 'dainty', 'deft', 'delicate', 'dexterous', 'elegant', 'expressive', 'feathered', 'feeble', 'firm', 'flaccid', 'gnarled', 'graceful', 'greasy', 'hairy', 'heavy-handed', 'ink-stained', 'knobby', 'limber', 'nimble', 'oversized', 'pale', 'palsied', 'papery', 'powerful', 'rough', 'slender', 'soft', 'spindly', 'steady', 'strong', 'supple', 'tapering', 'trembling', 'veiny', 'withered'];
export const ANATOMY_SKIN = ['Alabaster', 'ashen', 'blemished', 'bronzed', 'bruised', 'buttery', 'ceramic', 'chocolate', 'cinnamon', 'copper', 'dewy', 'dusky', 'ebony', 'erythritic', 'flushed', 'freckled', 'honeyed', 'ivory', 'leathery', 'mahogany', 'matte', 'milky', 'mottled', 'olive', 'onyx', 'pale', 'parchment-like', 'peaches-and-cream', 'pitted', 'porcelain', 'ruddy', 'sallow', 'satiny', 'scarred', 'sun-bleached', 'tanned', 'tawny', 'velvet', 'waxy', 'weathered'];
export const ANATOMY_POSTURE = ['Bent', 'bowed', 'brittle', 'collapsed', 'crumpled', 'dignified', 'drooping', 'erect', 'feline', 'flexible', 'fluid', 'halting', 'haughty', 'hunchbacked', 'jaunty', 'languid', 'limp', 'lithe', 'lopsided', 'majestic', 'military', 'nimble', 'plodding', 'poised', 'proud', 'ramrod', 'relaxed', 'rigid', 'slouching', 'slumping', 'sprightly', 'square-shouldered', 'stately', 'stiff', 'stooped', 'supple', 'swaying', 'unbending', 'upright', 'weary'];

export const STYLE_SILHOUETTE = ['Dapper', 'dishevelled', 'flamboyant', 'frumpy', 'haute-couture', 'immaculate', 'jaunty', 'modish', 'ostentatious', 'rakish', 'scruffy', 'slovenly', 'sophisticated', 'swanky', 'tattered', 'trendy', 'unpretentious', 'bohemian', 'chic', 'dowdy', 'elegant', 'fashionable', 'garish', 'grandiose', 'minimalist', 'ornate', 'polished', 'prim', 'rustic', 'sleek', 'spruce', 'stylish', 'tailored', 'unkempt', 'urbane', 'voguish', 'well-groomed', 'avant-garde', 'conservative', 'eccentric'];
export const STYLE_FABRIC = ['Abrasive', 'billowing', 'bristly', 'brocaded', 'coarse', 'diaphanous', 'distressed', 'embroidered', 'filmy', 'fleecy', 'frayed', 'gauzy', 'gossamer', 'grainy', 'inhibits', 'lacy', 'leathery', 'linen-crisp', 'lustrous', 'matte', 'metallic', 'nubby', 'plush', 'quilted', 'ragged', 'ribbed', 'satiny', 'sheer', 'shimmery', 'silken', 'sleek', 'stiff', 'suede', 'tactile', 'threadbare', 'tweed', 'velvety', 'waxy', 'weathered', 'woolly'];
export const STYLE_FIT = ['Baggy', 'bespoked', 'billowy', 'bundled', 'cinched', 'constricted', 'draped', 'fitted', 'form-fitting', 'frayed', 'gaping', 'ill-fitting', 'loose', 'oversized', 'pinched', 'pleat-fronted', 'puckered', 'sagging', 'seamless', 'shapeless', 'skin-tight', 'slack', 'snug', 'starched', 'strained', 'streamlined', 'stretched', 'tailored', 'taut', 'tight', 'trim', 'voluminous', 'well-tailored', 'worn-out', 'wrinkled', 'crisp', 'rumpled', 'shredded', 'stained', 'pristine'];
export const STYLE_PATTERN = ['Amber', 'bicoloured', 'bleached', 'bold', 'brindled', 'checkered', 'clashing', 'crimson', 'dappled', 'dark-hued', 'drab', 'electric', 'emerald', 'faded', 'flamboyant', 'floral', 'fluorescent', 'gaudy', 'gilded', 'houndstooth', 'iridescent', 'jumbled', 'monochromatic', 'mottled', 'muted', 'neon', 'neutral', 'opaque', 'pale', 'pastel', 'pinstriped', 'polychromatic', 'psychedelic', 'somber', 'speckled', 'splashy', 'stark', 'subdued', 'vibrant', 'vivid'];
export const STYLE_ACCESSSORIES = ['Adorned', 'bangled', 'beaded', 'belted', 'buckled', 'buttoned-down', 'caped', 'chained', 'cloaked', 'collared', 'crowned', 'cufflinked', 'dangled', 'decked', 'embellished', 'feathered', 'fringed', 'garlanded', 'gem-encrusted', 'gloved', 'hooded', 'jeweled', 'laced', 'masked', 'medalled', 'necklaced', 'padded', 'patched', 'pinned', 'plumed', 'pocketed', 'ringed', 'sashed', 'sequined', 'shawled', 'spangled', 'studded', 'tasseled', 'veiled', 'wristbanded'];

export const AGE_CHILD_PHYSICAL = ['Baby-faced', 'babbly', 'bouncy', 'bright-eyed', 'chubby-cheeked', 'dimpled', 'doughy', 'energetic', 'fine-haired', 'fleet-footed', 'freckle-faced', 'gap-toothed', 'lanky', 'leggy', 'limber', 'lithe', 'nimble', 'petite', 'pint-sized', 'pouting', 'pudgy', 'restless', 'rosy-cheeked', 'scrawny', 'small-boned', 'smooth-skinned', 'soft', 'spindly', 'sprightly', 'squirmy', 'supple', 'tiny', 'toddling', 'uncoordinated', 'vibrant', 'wide-eyed', 'wiry', 'wobbling', 'youthful', 'zesty'];
export const AGE_CHILD_BEHAVIOR = ['Adorable', 'boisterous', 'bratty', 'carefree', 'curious', 'docile', 'eager', 'fanciful', 'fickle', 'fussy', 'gullible', 'imaginative', 'impish', 'innocent', 'inquisitive', 'jovial', 'malleable', 'mischievous', 'naive', 'obedient', 'observant', 'playful', 'precocious', 'rebellious', 'shy', 'spirited', 'spontaneous', 'stubborn', 'sulky', 'tantrum-prone', 'trusting', 'uninhibited', 'unrefined', 'venturesome', 'wayward', 'whimsical', 'wild', 'willful', 'wonder-filled', 'zealous'];
export const AGE_ELDER_PHYSICAL = ['Arthritic', 'ashen', 'balding', 'bent', 'boney', 'brittle', 'clouded-eyed', 'craggy', 'creased', 'crippled', 'crouching', 'doting', 'droopy', 'feeble', 'filmy-eyed', 'flaccid', 'frail', 'furrowed', 'gnarled', 'grey-haired', 'hollow-cheeked', 'hunched', 'leathery', 'mottled-skin', 'palsied', 'papery-skinned', 'rheumy-eyed', 'senescent', 'silver-haired', 'stooped', 'sunken', 'thin-blooded', 'toothless', 'trembling', 'venerable', 'weathered', 'white-haired', 'withered', 'wizened', 'wrinkled'];
export const AGE_ELDER_DEMEANOR = ['Ancestral', 'antiquated', 'calm', 'conservative', 'dignified', 'disciplined', 'experienced', 'fatherly', 'formal', 'grandfatherly', 'grandmotherly', 'gray', 'hallowed', 'historical', 'knowledgeable', 'learned', 'legendary', 'matriarchal', 'mature', 'meditative', 'nostalgic', 'old-fashioned', 'patriarchal', 'patient', 'pensive', 'persevering', 'persistent', 'philosophical', 'placid', 'prudent', 'reflective', 'resigned', 'sage', 'seasoned', 'serene', 'sober', 'steady', 'timeless', 'traditional', 'wise'];
export const AGE_VITALITY = ['Ailing', 'bedridden', 'blooming', 'convalescent', 'decaying', 'declining', 'decrepit', 'dying', 'fading', 'flourishing', 'fragile', 'hale', 'healthy', 'hearty', 'infirm', 'invalid', 'lively', 'long-lived', 'morbid', 'moribund', 'peak', 'perishing', 'prime', 'recovering', 'robust', 'senile', 'sickly', 'sound', 'spry', 'stagnant', 'stolid', 'strengthening', 'sturdy', 'thriving', 'tough', 'valetudinarian', 'valetudinary', 'vanishing', 'vibrant', 'vigorous'];

export const FANTASY_ALIEN = ['Amorphous', 'bioluminescent', 'bulbous', 'chitinous', 'clawed', 'gelatinous', 'iridescent', 'leathery', 'limbless', 'many-eyed', 'metallic', 'multi-limbed', 'mucousy', 'oozing', 'organic', 'parasitic', 'phosphorescent', 'pincer-like', 'porous', 'protoplasmic', 'pulsing', 'scaly', 'segmented', 'slimy', 'spindly', 'spongy', 'squelching', 'striated', 'succulent', 'symmetrical', 'tactile', 'tentacled', 'translucent', 'tubular', 'undulating', 'vascular', 'vein-ridged', 'vestigial', 'viscous', 'winged'];
export const FANTASY_MAGIC = ['Alchemical', 'angelic', 'astral', 'aura-cloaked', 'celestial', 'demonic', 'divine', 'dreamlike', 'eerie', 'elemental', 'elfin', 'enchanted', 'ethereal', 'fey', 'ghostly', 'glowing', 'hallowed', 'haunted', 'illusionary', 'immortal', 'intangible', 'luminous', 'magical', 'misty', 'mythical', 'nebulous', 'otherworldly', 'phantasmal', 'radiant', 'shadowy', 'shamanic', 'sorcerous', 'spectral', 'spirit-bound', 'subliminal', 'supernatural', 'transcendent', 'unearthly', 'vaporous', 'wraith-like'];
export const FANTASY_CYBORG = ['Android', 'augmented', 'automated', 'bionic', 'chrome', 'circuit-mapped', 'clockwork', 'cold', 'computed', 'copper-wired', 'cybernetic', 'digital', 'drone-like', 'electric', 'electronic', 'galvanized', 'hard-wired', 'hydraulic', 'industrial', 'inorganic', 'integrated', 'kinetic', 'mechanical', 'metallic', 'modular', 'motorized', 'neural-linked', 'ocular-lens', 'pneumatic', 'programmed', 'prosthetic', 'robotic', 'sensory-enhanced', 'sleek', 'solar-powered', 'stainless', 'synthetic', 'technical', 'titanium', 'welded'];
export const FANTASY_FERAL = ['Animalistic', 'antlered', 'avian', 'beastly', 'bovine', 'brutish', 'canine', 'carnivorous', 'cold-blooded', 'fanged', 'feline', 'feral', 'feathered', 'finned', 'furred', 'gorgon-like', 'hairy', 'herbivorous', 'hoofed', 'horn-rimmed', 'howling', 'lupine', 'mammalian', 'maned', 'monstrous', 'predatory', 'primal', 'primitive', 'reptilian', 'roaring', 'savage', 'serpentine', 'shaggy', 'snouted', 'taloned', 'tusked', 'ursine', 'vulturous', 'wild', 'zoological'];
export const FANTASY_ELEMENT = ['Aerial', 'aquatic', 'arctic', 'arid', 'baked', 'boggy', 'boreal', 'cavernous', 'clouded', 'craggy', 'crystalline', 'desert-worn', 'dusty', 'earthy', 'fiery', 'floral', 'flinty', 'frozen', 'humid', 'igneous', 'lush', 'maritime', 'marshy', 'metallic', 'mossy', 'mountainous', 'oceanic', 'rocky', 'sandy', 'scorched', 'silvan', 'smoky', 'snowy', 'stony', 'swampy', 'tectonic', 'terrestrial', 'tropical', 'volcanic', 'wintry'];

export const VOCATION_MEDICAL = ['Clinical', 'surgical', 'antiseptic', 'diagnostic', 'therapeutic', 'palliative', 'holistic', 'anatomical', 'pharmacological', 'trauma-informed', 'rehabilitative', 'geriatric', 'pediatric', 'psychiatric', 'obstetric', 'hygienic', 'sterile', 'attentive', 'nurturing', 'bedside-mannered', 'scrubbed', 'vigilant', 'precise', 'intuitive', 'curative', 'medicinal', 'sanitised', 'empathetic', 'procedural', 'scientific', 'osteopathic', 'neural', 'cardiac', 'genetic', 'metabolic', 'forensic', 'immune-focused', 'pharmaceutical', 'triage-ready', 'steady-handed', 'calm-under-pressure', 'analytical', 'patient-centric', 'systematic', 'rigorous', 'expert', 'specialist', 'generalist', 'resident', 'attending', 'observant', 'sterile', 'empathetic', 'resilient', 'detail-oriented', 'ethical', 'licensed', 'board-certified', 'life-saving', 'compassionate'];
export const VOCATION_CRAFT = ['Dexterous', 'meticulous', 'creative', 'aesthetic', 'tactile', 'masterful', 'precision-oriented', 'traditional', 'avant-garde', 'bespoke', 'rustic', 'ornamental', 'utilitarian', 'decorative', 'rhythmic', 'sculptural', 'structural', 'technical', 'visionary', 'expressive', 'delicate', 'rugged', 'calloused', 'seasoned', 'apprentice', 'journeyman', 'master-craft', 'expert', 'innovative', 'detailed', 'ornate', 'symmetrical', 'abstract', 'minimal', 'maximal', 'vibrant', 'textural', 'refined', 'raw', 'unpolished', 'burnished', 'etched', 'carved', 'woven', 'forged', 'glazed', 'tailored', 'stitched', 'knitted', 'cast', 'molded', 'sanded', 'varnished', 'primed', 'sketched', 'drafted', 'dyed', 'pigmented', 'layered', 'intricate', 'sturdy'];
export const VOCATION_ACADEMIC = ['Erudite', 'scholarly', 'pedagogical', 'didactic', 'administrative', 'bureaucratic', 'systematic', 'archival', 'literary', 'philosophical', 'analytical', 'theoretical', 'abstract', 'methodical', 'logical', 'documented', 'stenographic', 'editorial', 'inquisitive', 'studious', 'bookish', 'high-brow', 'intellectual', 'rigorous', 'factual', 'evidence-based', 'data-driven', 'precise', 'linguistic', 'polyglot', 'historical', 'classical', 'modernistic', 'theological', 'legalistic', 'statutory', 'compliant', 'organized', 'thorough', 'comprehensive', 'extensive', 'niche', 'specialized', 'broad-minded', 'critical', 'objective', 'impartial', 'neutral', 'inquisitive', 'pedantic', 'precise', 'articulate', 'well-read', 'researched', 'peer-reviewed', 'academic', 'formal', 'official', 'verified', 'cited'];
export const VOCATION_COMBAT = ['Tactical', 'strategic', 'defensive', 'offensive', 'lethal', 'non-lethal', 'disciplined', 'alert', 'vigilant', 'combat-hardened', 'seasoned', 'veteran', 'recruit', 'elite', 'covert', 'overt', 'stealthy', 'imposing', 'formidable', 'sturdy', 'armored', 'agile', 'rapid', 'lethal', 'sharp-eyed', 'protective', 'sentinel', 'guardian', 'watchful', 'assertive', 'brave', 'valiant', 'heroic', 'mercenary', 'stoic', 'resilient', 'tough', 'aggressive', 'calculated', 'cold-blooded', 'fierce', 'menacing', 'rugged', 'camouflaged', 'ballistic', 'forensic', 'law-abiding', 'authoritative', 'commanding', 'unyielding', 'resolute', 'determined', 'bold', 'daring', 'plucky', 'dauntless', 'disciplined', 'trained', 'expert', 'professional', 'lethal'];
export const VOCATION_AGRI = ['Nautical', 'seafaring', 'aquatic', 'maritime', 'pastoral', 'agrarian', 'horticultural', 'weather-beaten', 'sun-kissed', 'salty', 'rugged', 'earthy', 'rustic', 'provincial', 'rural', 'sturdy', 'industrious', 'seasoned', 'nomadic', 'navigational', 'celestial', 'tidal', 'oceanic', 'deep-sea', 'coastal', 'fertile', 'green-thumbed', 'silvan', 'woodsy', 'muddy', 'dusty', 'calloused', 'weathered', 'resilient', 'patient', 'observant', 'seasonal', 'rhythmic', 'traditional', 'practical', 'manual', 'heavy-duty', 'outdoor', 'survivalist', 'hardy', 'robust', 'tireless', 'grounded', 'naturalistic', 'organic', 'wild', 'cultivated', 'domesticated', 'fermented', 'harvested', 'sown', 'tilled', 'ploughed', 'anchored', 'adrift', 'buoyant'];

export const ALIGN_LAWFUL = ['Principled', 'disciplined', 'obedient', 'compliant', 'statutory', 'orthodox', 'traditional', 'conservative', 'rigid', 'structured', 'systematic', 'loyal', 'faithful', 'devoted', 'constant', 'reliable', 'predictable', 'honorable', 'upright', 'righteous', 'scrupulous', 'punctilious', 'formal', 'ceremonial', 'dutiful', 'responsible', 'accountable', 'transparent', 'ethical', 'legalistic', 'bureaucratic', 'administrative', 'regulated', 'standard', 'uniform', 'consistent', 'steadfast', 'unwavering', 'unyielding', 'strict', 'severe', 'stern', 'solemn', 'grave', 'earnest', 'serious', 'literal', 'objective', 'impartial', 'fair', 'just', 'egalitarian', 'neutral', 'balanced', 'stable', 'secure', 'safe', 'protective', 'defensive', 'sentinel', 'guardian'];
export const ALIGN_CHAOTIC = ['Unpredictable', 'erratic', 'volatile', 'spontaneous', 'impulsive', 'whimsical', 'eccentric', 'unconventional', 'nonconformist', 'radical', 'rebellious', 'revolutionary', 'subversive', 'dissident', 'insurgent', 'anarchic', 'lawless', 'wild', 'untamed', 'feral', 'fluid', 'shifting', 'mercurial', 'fickle', 'restless', 'adventurous', 'daring', 'bold', 'reckless', 'heedless', 'careless', 'free', 'liberated', 'emancipated', 'independent', 'self-reliant', 'individualistic', 'unique', 'quirky', 'zany', 'bizarre', 'strange', 'odd', 'peculiar', 'original', 'inventive', 'creative', 'abstract', 'fluid', 'loose', 'relaxed', 'informal', 'casual', 'easy-going', 'nonchalant', 'breezy', 'detached', 'independent', 'wandering', 'nomadic', 'transient'];
export const ALIGN_BENEVOLENT = ['Kind', 'compassionate', 'empathetic', 'sympathetic', 'merciful', 'forgiving', 'generous', 'philanthropic', 'charitable', 'selfless', 'sacrificial', 'nurturing', 'caring', 'gentle', 'tender', 'soft-hearted', 'warm', 'hospitable', 'welcoming', 'friendly', 'amiable', 'affable', 'cordial', 'genial', 'polite', 'courteous', 'civil', 'gracious', 'noble', 'virtuous', 'saintly', 'angelic', 'holy', 'pure', 'innocent', 'harmless', 'pacifistic', 'non-violent', 'peaceful', 'harmonious', 'unifying', 'cooperative', 'collaborative', 'helpful', 'supportive', 'encouraging', 'inspiring', 'empowering', 'optimistic', 'hopeful', 'bright', 'radiant', 'sunny', 'cheerful', 'joyful', 'blissful', 'content', 'serene', 'placid', 'calm'];
export const ALIGN_MALEVOLENT = ['Cruel', 'heartless', 'callous', 'cold', 'indifferent', 'selfish', 'greedy', 'avaricious', 'miserly', 'stingy', 'envious', 'jealous', 'resentful', 'spiteful', 'vindictive', 'vengeful', 'malicious', 'malevolent', 'sinister', 'wicked', 'evil', 'demonic', 'devilish', 'corrupted', 'tainted', 'depraved', 'decadent', 'dissolute', 'treacherous', 'deceitful', 'dishonest', 'lying', 'manipulative', 'exploitative', 'oppressive', 'tyrannical', 'autocratic', 'narcissistic', 'egotistical', 'vain', 'proud', 'arrogant', 'haughty', 'supercilious', 'condescending', 'patronizing', 'mocking', 'cynical', 'pessimistic', 'gloomy', 'dismal', 'dark', 'shadowy', 'murky', 'hidden', 'secretive', 'stealthy', 'sly', 'cunning', 'wily', 'shrewd'];
export const ALIGN_NEUTRAL = ['Practical', 'pragmatic', 'realistic', 'objective', 'impartial', 'detached', 'aloof', 'indifferent', 'dispassionate', 'logical', 'rational', 'calculated', 'strategic', 'tactical', 'cautious', 'wary', 'prudent', 'wise', 'judicious', 'moderate', 'temperate', 'balanced', 'stable', 'steady', 'consistent', 'reliable', 'dependable', 'functional', 'utilitarian', 'efficient', 'effective', 'productive', 'quiet', 'reserved', 'reticent', 'silent', 'taciturn', 'observant', 'watchful', 'vigilant', 'private', 'secluded', 'hermit-like', 'solitary', 'independent', 'self-contained', 'autonomous', 'aloof', 'distant', 'remote', 'cold', 'cool', 'collected', 'composed', 'poised', 'stoic', 'unbothered', 'unflappable', 'calm', 'serene', 'patient'];

export const MENTAL_VISIONARY = ['Imaginative', 'creative', 'innovative', 'original', 'inventive', 'ingenious', 'prophetic', 'visionary', 'philosophical', 'theoretical', 'abstract', 'complex', 'multifaceted', 'deep', 'profound', 'insightful', 'perceptive', 'observant', 'acute', 'keen', 'sharp', 'brilliant', 'genius', 'wise', 'sagacious', 'learned', 'scholarly', 'academic', 'intellectual', 'cerebral', 'mental', 'cognitive', 'focused', 'concentrated', 'intent', 'absorbed', 'preoccupied', 'pensive', 'reflective', 'meditative', 'contemplative', 'dreamy', 'ethereal', 'idealistic', 'utopian', 'hopeful', 'optimistic', 'forward-thinking', 'progressive', 'radical', 'revolutionary', 'visionary', 'inspired', 'artistic', 'poetic', 'lyrical', 'expressive', 'articulate', 'eloquent', 'profound'];
export const MENTAL_STABLE = ['Resilient', 'tough', 'hardy', 'robust', 'strong', 'solid', 'stable', 'steady', 'consistent', 'reliable', 'dependable', 'responsible', 'accountable', 'disciplined', 'organized', 'methodical', 'systematic', 'practical', 'pragmatic', 'realistic', 'grounded', 'earthy', 'humble', 'modest', 'unpretentious', 'simple', 'plain', 'honest', 'sincere', 'candid', 'frank', 'direct', 'straightforward', 'blunt', 'sturdy', 'durable', 'long-lasting', 'patient', 'persevering', 'persistent', 'tenacious', 'determined', 'resolute', 'unwavering', 'steadfast', 'constant', 'loyal', 'faithful', 'devoted', 'brave', 'courageous', 'valiant', 'heroic', 'stoic', 'calm', 'composed', 'poised', 'serene', 'peaceful'];
export const MENTAL_SENSITIVE = ['Emotional', 'sensitive', 'empathetic', 'intuitive', 'reactive', 'volatile', 'explosive', 'temperamental', 'moody', 'mercurial', 'fickle', 'shifting', 'unstable', 'fragile', 'delicate', 'thin-skinned', 'defensive', 'guarded', 'anxious', 'apprehensive', 'fearful', 'timid', 'shy', 'introverted', 'reserved', 'reticent', 'quiet', 'silent', 'withdrawn', 'isolated', 'lonely', 'melancholy', 'despondent', 'dejected', 'depressed', 'gloomy', 'dismal', 'pessimistic', 'cynical', 'bitter', 'resentful', 'angry', 'furious', 'irascible', 'irritable', 'prickly', 'touchy', 'nervous', 'high-strung', 'jittery', 'restless', 'erratic', 'unpredictable', 'spontaneous', 'impulsive', 'reckless', 'bold', 'daring', 'adventurous', 'passionate', 'intense', 'fiery', 'electric', 'vibrant'];
